from __future__ import annotations

import hashlib
import json
from collections.abc import Callable
from pathlib import Path
from typing import Any, Protocol


class CanonicalFormLike(Protocol):
    mnemonic: str
    kb_mnemonic: str
    local_form_index: int
    form_index: int
    syntax: str
    operand_kinds: tuple[str, ...]
    opword_base: int
    opword_mask: int
    bound_word_bases: tuple[int, int]
    bound_word_masks: tuple[int, int]


LoadForms = Callable[..., list[CanonicalFormLike]]


def form_identity_key(form: CanonicalFormLike) -> tuple[object, ...]:
    return (
        str(form.kb_mnemonic),
        int(form.local_form_index),
        str(form.syntax),
        str(form.mnemonic),
        int(form.opword_base),
        int(form.opword_mask),
        tuple(int(base) for base in form.bound_word_bases),
        tuple(int(mask) for mask in form.bound_word_masks),
    )


def load_all_loadable_forms(kb_path: Path, load_forms: LoadForms) -> list[CanonicalFormLike]:
    kb = json.loads(kb_path.read_text(encoding="utf-8"))
    mnemonics: list[str] = []
    instructions = kb.get("instructions", [])
    assert isinstance(instructions, list)
    for item in instructions:
        if not isinstance(item, dict) or "mnemonic" not in item:
            continue
        if item.get("forms") is None and item.get("form_template") is None:
            continue
        mnemonic = str(item["mnemonic"])
        try:
            load_forms(kb_path, supported_mnemonics=(mnemonic,))
        except AssertionError:
            continue
        mnemonics.append(mnemonic)
    return [
        form
        for form in load_forms(kb_path, supported_mnemonics=tuple(mnemonics))
        if not (int(form.opword_mask) == 0 and str(form.mnemonic).lower() in {"cpbcc", "cpdbcc", "cptrapcc"})
    ]


def load_canonical_forms(kb_path: Path, load_forms: LoadForms) -> list[CanonicalFormLike]:
    forms = list(load_forms(kb_path))
    seen = {form_identity_key(form) for form in forms}
    for form in load_all_loadable_forms(kb_path, load_forms):
        key = form_identity_key(form)
        if key in seen:
            continue
        seen.add(key)
        forms.append(form)
    validate_canonical_forms(forms)
    return forms


def canonical_form_id_map(canonical_forms: list[CanonicalFormLike]) -> dict[tuple[object, ...], int]:
    return {form_identity_key(form): index + 1 for index, form in enumerate(canonical_forms)}


def validate_canonical_forms(canonical_forms: list[CanonicalFormLike]) -> None:
    keys = [form_identity_key(form) for form in canonical_forms]
    if len(keys) != len(set(keys)):
        raise AssertionError("duplicate canonical form identity")
    expected_ids = list(range(1, len(canonical_forms) + 1))
    actual_ids = list(canonical_form_id_map(canonical_forms).values())
    if actual_ids != expected_ids:
        raise AssertionError("canonical form ids are not dense and stable")


def snapshot_digest(canonical_forms: list[CanonicalFormLike]) -> str:
    rows = [
        {
            "id": index + 1,
            "identity": form_identity_key(form),
        }
        for index, form in enumerate(canonical_forms)
    ]
    payload = json.dumps(rows, sort_keys=True, separators=(",", ":"), default=_json_default)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def render_form_model_header(forms: list[CanonicalFormLike]) -> str:
    form_rows = [
        (
            f"    {{ {index + 1}u, {index}u, \"{form.mnemonic}\", \"{form.kb_mnemonic}\", "
            f"{form.local_form_index}u, \"{form.syntax}\", {len(form.operand_kinds)}u }},"
        )
        for index, form in enumerate(forms)
    ]
    id_by_row = [f"    {index + 1}u," for index in range(len(forms))]
    row_by_id = ["    M68K_FORM_ROW_NONE,"] + [f"    {index}u," for index in range(len(forms))]
    return "\n".join([
        "/* Auto-generated by src/scripts/m68k_canonical_model.py. */",
        "#ifndef M68K_FORM_MODEL_H",
        "#define M68K_FORM_MODEL_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef uint16_t M68kFormId;",
        "typedef uint16_t M68kFormRow;",
        "typedef uint8_t M68kOperandSlot;",
        "",
        "enum {",
        "    M68K_FORM_ID_NONE = 0u,",
        "    M68K_FORM_ROW_NONE = 0xFFFFu,",
        "    M68K_OPERAND_SLOT_NONE = 0xFFu,",
        "    M68K_OPERAND_SLOT_COUNT = 4u,",
        f"    M68K_CANONICAL_FORM_COUNT = {len(forms)}u",
        "};",
        "",
        "typedef struct {",
        "    M68kFormId id;",
        "    M68kFormRow row;",
        "    const char *mnemonic;",
        "    const char *kb_mnemonic;",
        "    uint16_t local_form_index;",
        "    const char *syntax;",
        "    M68kOperandSlot operand_count;",
        "} M68kCanonicalFormDef;",
        "",
        "static const M68kCanonicalFormDef g_m68k_canonical_forms[M68K_CANONICAL_FORM_COUNT] = {",
        *form_rows,
        "};",
        "",
        "static const M68kFormId g_m68k_canonical_form_id_by_row[M68K_CANONICAL_FORM_COUNT] = {",
        *id_by_row,
        "};",
        "",
        "static const M68kFormRow g_m68k_canonical_form_row_by_id[M68K_CANONICAL_FORM_COUNT + 1u] = {",
        *row_by_id,
        "};",
        "",
        "static inline M68kFormId m68k_form_id_for_row(M68kFormRow row) {",
        "    return row < M68K_CANONICAL_FORM_COUNT ? g_m68k_canonical_form_id_by_row[row] : M68K_FORM_ID_NONE;",
        "}",
        "",
        "static inline M68kFormRow m68k_form_row_for_id(M68kFormId id) {",
        "    return id <= M68K_CANONICAL_FORM_COUNT ? g_m68k_canonical_form_row_by_id[id] : M68K_FORM_ROW_NONE;",
        "}",
        "",
        "#endif",
        "",
    ])


def _json_default(value: Any) -> Any:
    if isinstance(value, tuple):
        return list(value)
    raise TypeError(f"Cannot serialize {value!r}")
