from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from amiga_reversing.disasm.assembler_profiles import load_assembler_profile
from amiga_reversing.disasm.effective_metadata import (
    effective_metadata_file,
)
from amiga_reversing.disasm.project_paths import PROJECT_ROOT, resolve_project_paths
from amiga_reversing.disasm.source_rendering import render_source_from_binary_source

SOURCE_EXPORT_ASSEMBLER_PROFILES = ("vasm", "devpac")


class SourceExportRefused(RuntimeError):
    def __init__(self, payload: dict[str, object]) -> None:
        self.payload = payload
        super().__init__(str(payload.get("message") or "source export refused"))


def source_export_payload(
    target_name: str,
    *,
    assembler_profile: str = "vasm",
    project_root: Path = PROJECT_ROOT,
) -> dict[str, object]:
    try:
        return render_source_export(
            target_name,
            assembler_profile=assembler_profile,
            project_root=project_root,
        )
    except SourceExportRefused as exc:
        return exc.payload


def render_source_export(
    target_name: str,
    *,
    assembler_profile: str = "vasm",
    project_root: Path = PROJECT_ROOT,
) -> dict[str, object]:
    profile = _require_source_export_profile(assembler_profile)
    paths = resolve_project_paths(target_name, project_root=project_root)
    binary_source = paths.binary_source
    with effective_metadata_file(paths.target_dir) as metadata_path:
        rendering = render_source_from_binary_source(
            target_id=target_name,
            binary_source=binary_source,
            target_dir=paths.target_dir,
            metadata_path=metadata_path,
            project_root=project_root,
            workflow_id="source_export",
        )
    filename = f"{_safe_filename(target_name)}-{profile}.s"
    generated_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    if rendering.refused:
        raise SourceExportRefused(
            {
                "status": "refused",
                "target": target_name,
                "assembler_profile": profile,
                "filename": filename,
                "message": rendering.refusal_message,
                "listing_profile": rendering.listing_profile,
                "workflow_profile": rendering.workflow_profile,
                "metadata_hash": rendering.metadata_hash,
                "target_identity_sha256": rendering.target_identity_sha256,
                "generated_at": generated_at,
            }
        )
    header = _source_export_header(
        target_name,
        assembler_profile=profile,
        metadata_hash=rendering.metadata_hash,
        target_identity_sha256=rendering.target_identity_sha256,
        generated_at=generated_at,
    )
    return {
        "status": "ok",
        "target": target_name,
        "assembler_profile": profile,
        "filename": filename,
        "source_text": _join_header_and_source(header, rendering.source_text, assembler_profile=profile),
        "header": header,
        "metadata_hash": rendering.metadata_hash,
        "target_identity_sha256": rendering.target_identity_sha256,
        "generated_at": generated_at,
        "listing_profile": rendering.listing_profile,
        "workflow_profile": rendering.workflow_profile,
        "non_verification": True,
    }


def _require_source_export_profile(assembler_profile: str) -> str:
    if assembler_profile not in SOURCE_EXPORT_ASSEMBLER_PROFILES:
        allowed = ", ".join(SOURCE_EXPORT_ASSEMBLER_PROFILES)
        raise ValueError(f"invalid source export assembler profile {assembler_profile!r}; expected one of {allowed}")
    load_assembler_profile(assembler_profile)
    return assembler_profile


def _source_export_header(
    target_name: str,
    *,
    assembler_profile: str,
    metadata_hash: str,
    target_identity_sha256: str,
    generated_at: str,
) -> str:
    lines = [
        "; Generated by amiga-reversing source export",
        f"; Target: {target_name}",
        f"; Assembler profile: {assembler_profile}",
        f"; Metadata hash: {metadata_hash}",
        f"; Target identity sha256: {target_identity_sha256}",
        f"; Generated at: {generated_at}",
        "; Export is not verification; run reproduction or oracle checks separately.",
    ]
    return "\n".join(lines) + "\n"


def _join_header_and_source(header: str, source_text: str, *, assembler_profile: str) -> str:
    profile = load_assembler_profile(assembler_profile)
    newline = "\n" if profile.render.line_ending == "lf" else "\r\n"
    text = header + "\n" + source_text.lstrip("\r\n")
    return text.replace("\r\n", "\n").replace("\n", newline)


def _safe_filename(target_name: str) -> str:
    clean = "".join(char if char.isalnum() or char in {"-", "_"} else "-" for char in target_name)
    return clean.strip("-") or "source-export"
