from __future__ import annotations

import hashlib
import time
from datetime import UTC, datetime
from pathlib import Path

from amiga_reversing.disasm.assembler_profiles import load_assembler_profile
from amiga_reversing.disasm.c_backend import (
    listing_artifact_source_text_with_c_backend_profile,
)
from amiga_reversing.disasm.effective_metadata import (
    effective_metadata_file,
    effective_metadata_hash,
)
from amiga_reversing.disasm.facts_v2_source_refusal import (
    facts_v2_source_refusal_message,
    facts_v2_source_refused,
)
from amiga_reversing.disasm.project_paths import PROJECT_ROOT, resolve_project_paths
from amiga_reversing.disasm.workflow_profile import WorkflowProfile

SOURCE_EXPORT_ASSEMBLER_PROFILES = ("vasm", "devpac")


class SourceExportRefused(RuntimeError):
    def __init__(self, payload: dict[str, object]) -> None:
        self.payload = payload
        super().__init__(str(payload.get("message") or "source export refused"))


def source_export_payload(
    target_name: str,
    *,
    assembler_profile: str = "vasm",
    project_root: Path = PROJECT_ROOT,
) -> dict[str, object]:
    try:
        return render_source_export(
            target_name,
            assembler_profile=assembler_profile,
            project_root=project_root,
        )
    except SourceExportRefused as exc:
        return exc.payload


def render_source_export(
    target_name: str,
    *,
    assembler_profile: str = "vasm",
    project_root: Path = PROJECT_ROOT,
) -> dict[str, object]:
    profile = _require_source_export_profile(assembler_profile)
    paths = resolve_project_paths(target_name, project_root=project_root)
    binary_source = paths.binary_source
    with effective_metadata_file(paths.target_dir) as metadata_path:
        render_started_at = time.perf_counter()
        source_text, listing_profile = listing_artifact_source_text_with_c_backend_profile(
            binary_source,
            metadata_path=metadata_path,
            project_root=project_root,
        )
    workflow_profile = WorkflowProfile("source_export", target_id=target_name)
    workflow_profile.add_span(
        "source_rendering",
        time.perf_counter() - render_started_at,
        module="c_backend",
        detail={"listing_profile": listing_profile},
    )
    metadata_hash = effective_metadata_hash(paths.target_dir)
    identity_hash = _sha256_bytes(binary_source.read_bytes())
    filename = f"{_safe_filename(target_name)}-{profile}.s"
    generated_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    if facts_v2_source_refused(listing_profile):
        raise SourceExportRefused(
            {
                "status": "refused",
                "target": target_name,
                "assembler_profile": profile,
                "filename": filename,
                "message": facts_v2_source_refusal_message(listing_profile),
                "listing_profile": listing_profile,
                "workflow_profile": workflow_profile.to_payload(),
                "metadata_hash": metadata_hash,
                "target_identity_sha256": identity_hash,
                "generated_at": generated_at,
            }
        )
    header = _source_export_header(
        target_name,
        assembler_profile=profile,
        metadata_hash=metadata_hash,
        target_identity_sha256=identity_hash,
        generated_at=generated_at,
    )
    return {
        "status": "ok",
        "target": target_name,
        "assembler_profile": profile,
        "filename": filename,
        "source_text": _join_header_and_source(header, source_text, assembler_profile=profile),
        "header": header,
        "metadata_hash": metadata_hash,
        "target_identity_sha256": identity_hash,
        "generated_at": generated_at,
        "listing_profile": listing_profile,
        "workflow_profile": workflow_profile.to_payload(),
        "non_verification": True,
    }


def _require_source_export_profile(assembler_profile: str) -> str:
    if assembler_profile not in SOURCE_EXPORT_ASSEMBLER_PROFILES:
        allowed = ", ".join(SOURCE_EXPORT_ASSEMBLER_PROFILES)
        raise ValueError(f"invalid source export assembler profile {assembler_profile!r}; expected one of {allowed}")
    load_assembler_profile(assembler_profile)
    return assembler_profile


def _source_export_header(
    target_name: str,
    *,
    assembler_profile: str,
    metadata_hash: str,
    target_identity_sha256: str,
    generated_at: str,
) -> str:
    lines = [
        "; Generated by amiga-reversing source export",
        f"; Target: {target_name}",
        f"; Assembler profile: {assembler_profile}",
        f"; Metadata hash: {metadata_hash}",
        f"; Target identity sha256: {target_identity_sha256}",
        f"; Generated at: {generated_at}",
        "; Export is not verification; run reproduction or oracle checks separately.",
    ]
    return "\n".join(lines) + "\n"


def _join_header_and_source(header: str, source_text: str, *, assembler_profile: str) -> str:
    profile = load_assembler_profile(assembler_profile)
    newline = "\n" if profile.render.line_ending == "lf" else "\r\n"
    text = header + "\n" + source_text.lstrip("\r\n")
    return text.replace("\r\n", "\n").replace("\n", newline)


def _safe_filename(target_name: str) -> str:
    clean = "".join(char if char.isalnum() or char in {"-", "_"} else "-" for char in target_name)
    return clean.strip("-") or "source-export"


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()
