from __future__ import annotations

from pathlib import Path
from typing import Any

from amiga_reversing.tools import rendered_source_roundtrip_report as report_tool


def test_roundtrip_report_verifies_without_persisting_reproduction_report(monkeypatch) -> None:
    calls: list[dict[str, Any]] = []
    source_path = Path("targets/demo/asm.s")

    def run_reproduction(target: str, **kwargs: object) -> dict[str, object]:
        calls.append({"target": target, "kwargs": kwargs})
        return {
            "status": "exact",
            "comparison": {
                "full_file_exact": True,
                "content_exact": True,
                "failure_kinds": [],
                "diff_range_count": 0,
            },
        }

    monkeypatch.setattr(report_tool, "run_reproduction", run_reproduction)
    monkeypatch.setattr(Path, "read_text", lambda self, encoding=None: "rts\n")

    row = report_tool._run_target("amiga_hunk_demo", source_path)

    assert row["status"] == "exact"
    assert row["rendered_source_full_file_exact"] is True
    assert calls == [
        {
            "target": "amiga_hunk_demo",
            "kwargs": {
                "assembler": "our",
                "profile": True,
                "persist_report": False,
                "pre_rendered_source_text": "rts\n",
            },
        }
    ]


def test_roundtrip_report_update_mode_writes_then_verifies_pre_rendered_source(monkeypatch, tmp_path: Path) -> None:
    calls: list[dict[str, Any]] = []
    source_path = tmp_path / "demo.s"

    def update_rendered_source(target: str, path: Path) -> tuple[str, dict[str, object]]:
        assert target == "amiga_hunk_demo"
        assert path == source_path
        path.write_text("rts\n", encoding="utf-8")
        return "rts\n", {"generation": "facts_v2_asm_source"}

    def run_reproduction(target: str, **kwargs: object) -> dict[str, object]:
        calls.append({"target": target, "kwargs": kwargs})
        return {
            "status": "exact",
            "comparison": {
                "full_file_exact": True,
                "content_exact": True,
                "failure_kinds": [],
                "diff_range_count": 0,
            },
        }

    monkeypatch.setattr(report_tool, "_update_rendered_source", update_rendered_source)
    monkeypatch.setattr(report_tool, "run_reproduction", run_reproduction)

    row = report_tool._run_target("amiga_hunk_demo", source_path, update_rendered_source=True)

    assert source_path.read_text(encoding="utf-8") == "rts\n"
    assert row["source_updated"] is True
    assert calls == [
        {
            "target": "amiga_hunk_demo",
            "kwargs": {
                "assembler": "our",
                "profile": True,
                "persist_report": False,
                "pre_rendered_source_text": "rts\n",
                "pre_rendered_source_profile": {"generation": "facts_v2_asm_source"},
            },
        }
    ]


def test_roundtrip_report_update_mode_keeps_macos_unsupported(monkeypatch, tmp_path: Path) -> None:
    def update_rendered_source(target: str, path: Path) -> tuple[str, dict[str, object]]:
        raise AssertionError("Mac OS source should not be regenerated by round-trip update mode")

    monkeypatch.setattr(report_tool, "_update_rendered_source", update_rendered_source)

    row = report_tool._run_target(
        "macos_hfs_mpw_gm__macos_file_mpw_tools_asm",
        tmp_path / "targets" / "macos_file_mpw_tools_asm" / "asm.s",
        update_rendered_source=True,
    )

    assert row["status"] == "unsupported"
    assert row["source_updated"] is False
