; Generated by amiga-reversing source export
; Target: amiga_disk_midwinter-1990-rainbird__amiga_raw_bootblock
; Assembler profile: vasm
; Metadata hash: ca561bc122d2e9e51c910c5236fb424b00ce3c03ba96b729c6e88a038ad31389
; Target identity sha256: 127a0f70e3a0ecab154b67dbbd5aa0f8c61f8dbbed53f5ddf1294414bea97ba9
; Export is not verification; run reproduction or oracle checks separately.

; Memory map
;   Absolute memory refs:
;     absolute[$000314E0] refs=1 access=a
;     absolute[$00031500] refs=1 access=a
;     absolute[$00070000] refs=1 access=a

; OS compatibility
;   minimum required: 1.3
;   observed API availability: 1.3
;   observed FD/interface versions: none
;   max requirement drivers:
;     _LVOForbid at section_0+$00000012 requires 1.3

    INCLUDE "exec/exec_lib.i"
    INCLUDE "hardware/adkbits.i"
    INCLUDE "hardware/cia.i"
    INCLUDE "hardware/custom.i"
    INCLUDE "hardware/dmabits.i"
    INCLUDE "hardware/intbits.i"

_custom	EQU	$DFF000
INTF_CLRALL	EQU	$7FFF
m68k_vector_level_1_interrupt_autovector	EQU	$64
absolute_slot_000314E0	EQU	$314E0
runtime_address_00031500	EQU	$31500
_ciab	EQU	$BFD000
absolute_slot_00070000	EQU	$70000

    SECTION code,code
	dc.b "DOS",$00	; NOTE: boot magic
	dc.l $9E5237C2	; NOTE: boot checksum
	dc.l $00000370	; NOTE: boot root block
    ; KNOWN: base A6=exec.library:LIB; type A1=IOStdReq (open trackdisk.device):IO
boot_entry:
	movea.l $00000004.l,a6
	jsr _LVOForbid(a6)
	lea.l loc_0_000003DC(pc),a7
	lea.l _custom.l,a6
	move.w #INTF_CLRALL,intena(a6)
	move.w #INTF_CLRALL,intreq(a6)
	moveq.l #6,d0
	lea.l loc_0_0000007A(pc),a0
	lea.l $00000064.l,a1
loc_0_00000038:
	move.l a0,(a1)+
	dbf.w d0,loc_0_00000038
	move.l loc_0_0000009E(pc),m68k_vector_level_1_interrupt_autovector.l
	moveq.l #1,d0
	moveq.l #5,d1
	moveq.l #0,d2
	moveq.l #0,d3
	lea.l absolute_slot_000314E0.l,a0
	lea.l loc_0_000002FA(pc),a3
	bsr.w loc_0_0000019A
	tst.l d4
	bmi.w loc_0_00000068
	jmp runtime_address_00031500.l
loc_0_00000068:
	moveq.l #0,d0
loc_0_0000006A:
	addi.w #256,d0
	andi.w #3840,d0
	move.w d0,_custom+color.l	; palette color 0
	bra.b loc_0_0000006A
loc_0_0000007A:
	dc.b $48,$E7,$80,$02,$4D,$F9,$00,$DF,$F0,$00,$30,$2E,$00,$1C,$08,$00
	dc.b $00,$0E,$67,$0C,$C0,$6E,$00,$1E,$02,$40,$3F,$FF,$3D,$40,$00,$9C
	dc.b $4C,$DF,$40,$01
loc_0_0000009E:
	dc.b $4E,$73
loc_0_000000A0:
	lea.l _custom.l,a6
	move.w #DMAF_SETCLR|DMAF_BLITHOG|DMAF_MASTER|DMAF_BLITTER|DMAF_DISK,dmacon(a6)
	lea.l _ciab.l,a4
	move.l #$55555555,d5
	move.w $0010(a3),d2
	moveq.l #0,d3
	addi.w #3,d2
	bset d2,d3
	move.w $0012(a3),d2
	beq.b loc_0_000000CE
	bset #2,d3
loc_0_000000CE:
	move.b d3,$0014(a3)
	move.b #CIAF_DSKMOTOR|CIAF_DSKSEL3|CIAF_DSKSEL2|CIAF_DSKSEL1|CIAF_DSKSEL0|CIAF_DSKSIDE|CIAF_DSKDIREC|CIAF_DSKSTEP,ciaprb(a4)
	move.b #CIAF_DSKSEL3|CIAF_DSKSEL2|CIAF_DSKSEL1|CIAF_DSKSEL0|CIAF_DSKSIDE|CIAF_DSKDIREC|CIAF_DSKSTEP,ciaprb(a4)
	ori.b #128,d3
	not.b d3
	move.b d3,ciaprb(a4)
	move.w #$C000,d2
loc_0_000000EC:
	move.w d2,d4
	mulu.w d4,d4
	mulu.w d4,d4
	btst.b #5,$1001(a4)
	dbeq.w d2,loc_0_000000EC
	bne.w loc_0_00000246
	moveq.l #0,d4
	rts
loc_0_00000104:
	move.b #$FF,$0100(a4)
	move.b #$BF,$0100(a4)
	move.b #$DF,$0100(a4)
	move.b #$EF,$0100(a4)
	move.b #$F7,$0100(a4)
	move.b #$FF,$0100(a4)
	rts
loc_0_0000012A:
	btst.b #4,$1001(a4)
	beq.b loc_0_0000013A
	moveq.l #1,d0
	bsr.w loc_0_0000015C
	bra.b loc_0_0000012A
loc_0_0000013A:
	clr.w $0016(a3)
	rts
loc_0_00000140:
	move.w d0,d6
	tst.w $0016(a3)
	bpl.b loc_0_0000014C
	bsr.w loc_0_0000012A
loc_0_0000014C:
	sub.w $0016(a3),d6
	beq.b loc_0_00000198
	add.w d6,$0016(a3)
	move.w d6,d0
	bpl.b loc_0_00000166
	neg.w d0
loc_0_0000015C:
	move.b $0014(a3),d1
	ori.b #128,d1
	bra.b loc_0_0000016E
loc_0_00000166:
	move.b $0014(a3),d1
	ori.b #130,d1
loc_0_0000016E:
	move.b d1,d2
	ori.b #1,d2
	not.b d1
	not.b d2
	subq.w #1,d0
loc_0_0000017A:
	move.b d2,$0100(a4)
	bra.w loc_0_00000182
loc_0_00000182:
	bra.w loc_0_00000186
loc_0_00000186:
	move.b d1,$0100(a4)
	move.w #$208,d3
loc_0_0000018E:
	mulu.w d4,d4
	dbf.w d3,loc_0_0000018E
	dbf.w d0,loc_0_0000017A
loc_0_00000198:
	rts
loc_0_0000019A:
	move.w d2,$0010(a3)
	move.w d3,$0012(a3)
	bsr.w loc_0_000000A0
loc_0_000001A6:
	move.w #$2,$0018(a3)
	movem.w d0-d1,-(a7)
	move.l a0,-(a7)
	bsr.w loc_0_00000140
	bsr.w loc_0_000001F2
	nop
	nop
	nop
	nop
	nop
	nop
	addq.w #4,a7
	movem.w (a7)+,d0-d1
	addq.w #1,d0
	dbf.w d1,loc_0_000001A6
	moveq.l #0,d4
	bsr.w loc_0_00000104
	tst.w d4
	rts
	dc.b $20,$5F,$4C,$9F,$00,$03,$53,$6B,$00,$18,$6B,$00,$FF,$EC,$66,$C0
	dc.b $50,$EB,$00,$16,$60,$BA
loc_0_000001F2:
	movem.l d0-d7/a0-a6,-(a7)
loc_0_000001F6:
	moveq.l #10,d6
	lea.l absolute_slot_00070000.l,a2
	move.l a2,dskpt(a6)	; disk_buffer pointer $00070000
	move.w #INTF_DSKBLK,intreq(a6)
	move.w #DMAF_SETCLR|DMAF_MASTER|DMAF_DISK,dmacon(a6)
	move.w #$4489,d4
	move.w d4,dsksync(a6)
	move.w #ADKF_SETCLR|ADKF_WORDSYNC|ADKF_FAST,adkcon(a6)
	move.w #$4000,dsklen(a6)
	move.w #$9996,dsklen(a6)	; disk DMA read 13100 bytes
	move.w #$9996,dsklen(a6)	; disk DMA read 13100 bytes
loc_0_0000022E:
	move.w intreqr(a6),d0	; interrupt request state
	btst #1,d0
	beq.b loc_0_0000022E
loc_0_00000238:
	cmp.w (a2)+,d4
	bne.b loc_0_00000238
	cmp.w (a2),d4
	beq.b loc_0_00000238
	move.l #$55555555,d7
loc_0_00000246:
	move.l (a2)+,d0
	move.l (a2)+,d1
	and.l d7,d0
	add.l d0,d0
	and.l d7,d1
	or.l d1,d0
	add.w d0,d0
	andi.w #7680,d0
	cmp.w #$1400,d0
	bcs.b loc_0_00000264
	lea.l $0230(a2),a2
	bra.b loc_0_0000028E
loc_0_00000264:
	lea.l $0(a0,d0.w),a1
	lea.l $002C(a2),a2
	move.l (a2)+,d2
	moveq.l #127,d3
loc_0_00000270:
	move.l $0200(a2),d1
	eor.l d1,d2
	move.l (a2)+,d0
	eor.l d0,d2
	and.l d7,d0
	add.l d0,d0
	and.l d7,d1
	or.l d1,d0
	move.l d0,(a1)+
	dbf.w d3,loc_0_00000270
	and.l d7,d2
	bne.w loc_0_000001F6
loc_0_0000028E:
	dbf.w d6,loc_0_00000238
	movem.l (a7)+,d0-d7/a0-a6
	lea.l $1400(a0),a0
	rts
	dc.b $E4,$49,$20,$18,$55,$41,$24,$18,$B5,$80,$51,$C9,$FF,$FA,$C0,$85
	dc.b $4E,$75,$20,$18,$22,$18,$C0,$85,$C2,$85,$D0,$80,$80,$81,$4E,$75
	dc.b $43,$F0,$00,$00,$E4,$48,$53,$40,$22,$18,$24,$19,$C2,$85,$C4,$85
	dc.b $D2,$81,$82,$82,$2A,$C1,$51,$C8,$FF,$F0,$4E,$75,$4D,$61,$65,$6C
	dc.b $73,$74,$72,$6F,$6D,$20,$47,$61,$6D,$65,$73,$20,$50,$72,$65,$73
	dc.b $65,$6E,$74,$73,$20,$4D,$49,$44,$57,$49,$4E,$54,$45,$52
loc_0_000002FA:
	dcb.b $E2,$00
loc_0_000003DC:
	dcb.b $24,$00
