; Generated by amiga-reversing source export
; Target: amiga_disk_magicland-dizzy-1991-codemasters-trsi-lsd__amiga_raw_bootblock
; Assembler profile: vasm
; Metadata hash: 830455a47c96fa4506bc25b22521377b141f889beb0eb32f84cddd4a0685e4bf
; Target identity sha256: cc40c396928c31bb82b98a16206d42da8aab4934445f8d2a492ff659f8a053e8
; Generated at: 2026-05-27T22:54:14+00:00
; Export is not verification; run reproduction or oracle checks separately.

; OS compatibility
;   minimum required: 1.3
;   observed API availability: 1.3
;   observed FD/interface versions: none
;   max requirement drivers:
;     _LVOOpenLibrary at section_0+$00000012 requires 1.3
;     _LVOCloseLibrary at section_0+$00000022 requires 1.3
;     _LVOFindResident at section_0+$0000002A requires 1.3

    INCLUDE "exec/exec_lib.i"
    INCLUDE "exec/resident.i"
    INCLUDE "libraries/expansionbase.i"


    SECTION code,code
	dc.b "DOS",$00	; NOTE: boot magic
	dc.l $42454552	; NOTE: boot checksum
	dc.l $00000370	; NOTE: boot root block
    ; KNOWN: base A6=exec.library:LIB; type A1=IOStdReq (open trackdisk.device):IO
boot_entry:
	lea.l loc_0_0000004C(pc),a1
	moveq.l #37,d0
	jsr _LVOOpenLibrary(a6)
	tst.l d0
	beq.b loc_0_00000026
	movea.l d0,a1
	bset.b #6,eb_Flags(a1)
	jsr _LVOCloseLibrary(a6)
loc_0_00000026:
	lea.l loc_0_00000040(pc),a1
	jsr _LVOFindResident(a6)
	tst.l d0
	beq.b loc_0_0000003C
	movea.l d0,a0
	movea.l RT_INIT(a0),a0
	moveq.l #0,d0
	rts
loc_0_0000003C:
	moveq.l #-1,d0
	rts
loc_0_00000040:
	dc.b "dos.library",$00	; string
loc_0_0000004C:
	dc.b "expansion.library",$00	; string
	dc.b $00,$00,$A0,$F7,$C9,$21
	dcb.b $39C,$00
