; Generated by amiga-reversing source export
; Target: amiga_disk_magicland-dizzy-1991-codemasters-trsi-lsd__amiga_hunk_cacheoff_77b2e4f4
; Assembler profile: vasm
; Metadata hash: 2dc738453d7edcbc050659715a0058ca28d95d4338c8853142856305d94ed665
; Target identity sha256: e54c46a13451115bc48c7d9c2f8d5eae901a1288f56bfa139bcf04f9dbcb47b2
; Export is not verification; run reproduction or oracle checks separately.

; OS compatibility
;   minimum required: 1.3
;   observed API availability: 1.3
;   observed FD/interface versions: none
;   max requirement drivers:
;     _LVOSupervisor at section_0+$00000010 requires 1.3

    INCLUDE "exec/exec_lib.i"

    RSSET 0
    RS.B 297
app_0129 RS.B 1
app_SIZEOF EQU __RS


    SECTION section,code
loc_0_00000000:
	movea.l $0004.w,a6
	btst.b #1,app_0129(a6)
	beq.b loc_0_00000014
	lea.l loc_0_00000018(pc),a5
	jsr _LVOSupervisor(a6)
loc_0_00000014:
	clr.l d0
	rts
loc_0_00000018:
	dc.b $4E,$7A,$00,$02,$02,$40,$EE,$EE,$4E,$7B,$00,$02,$4E,$73,$00,$00
