/* Auto-generated by src/scripts/generate_c99_assembler_subset.py. */
#ifndef M68K_ASM_TABLES_H
#define M68K_ASM_TABLES_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
    M68K_ASM_MNEMONIC_ASL = 0,
    M68K_ASM_MNEMONIC_ASR = 1,
    M68K_ASM_MNEMONIC_LSL = 2,
    M68K_ASM_MNEMONIC_LSR = 3,
    M68K_ASM_MNEMONIC_BCHG = 4,
    M68K_ASM_MNEMONIC_BCLR = 5,
    M68K_ASM_MNEMONIC_BSET = 6,
    M68K_ASM_MNEMONIC_BTST = 7,
    M68K_ASM_MNEMONIC_BFCHG = 8,
    M68K_ASM_MNEMONIC_BFCLR = 9,
    M68K_ASM_MNEMONIC_BFEXTS = 10,
    M68K_ASM_MNEMONIC_BFEXTU = 11,
    M68K_ASM_MNEMONIC_BFFFO = 12,
    M68K_ASM_MNEMONIC_BFINS = 13,
    M68K_ASM_MNEMONIC_BFSET = 14,
    M68K_ASM_MNEMONIC_BFTST = 15,
    M68K_ASM_MNEMONIC_ABCD = 16,
    M68K_ASM_MNEMONIC_ADD = 17,
    M68K_ASM_MNEMONIC_ADDX = 18,
    M68K_ASM_MNEMONIC_ADDI = 19,
    M68K_ASM_MNEMONIC_ADDA = 20,
    M68K_ASM_MNEMONIC_ADDQ = 21,
    M68K_ASM_MNEMONIC_AND = 22,
    M68K_ASM_MNEMONIC_ANDI = 23,
    M68K_ASM_MNEMONIC_CAS = 24,
    M68K_ASM_MNEMONIC_CAS2 = 25,
    M68K_ASM_MNEMONIC_CHK = 26,
    M68K_ASM_MNEMONIC_CHK2 = 27,
    M68K_ASM_MNEMONIC_CMP = 28,
    M68K_ASM_MNEMONIC_CMPA = 29,
    M68K_ASM_MNEMONIC_CMPI = 30,
    M68K_ASM_MNEMONIC_CMP2 = 31,
    M68K_ASM_MNEMONIC_CMPM = 32,
    M68K_ASM_MNEMONIC_DIVS = 33,
    M68K_ASM_MNEMONIC_DIVU = 34,
    M68K_ASM_MNEMONIC_EOR = 35,
    M68K_ASM_MNEMONIC_EORI = 36,
    M68K_ASM_MNEMONIC_ROL = 37,
    M68K_ASM_MNEMONIC_ROR = 38,
    M68K_ASM_MNEMONIC_ROXL = 39,
    M68K_ASM_MNEMONIC_ROXR = 40,
    M68K_ASM_MNEMONIC_NEG = 41,
    M68K_ASM_MNEMONIC_NEGX = 42,
    M68K_ASM_MNEMONIC_NOT = 43,
    M68K_ASM_MNEMONIC_OR = 44,
    M68K_ASM_MNEMONIC_ORI = 45,
    M68K_ASM_MNEMONIC_SBCD = 46,
    M68K_ASM_MNEMONIC_SUB = 47,
    M68K_ASM_MNEMONIC_SUBX = 48,
    M68K_ASM_MNEMONIC_SUBA = 49,
    M68K_ASM_MNEMONIC_SUBI = 50,
    M68K_ASM_MNEMONIC_SUBQ = 51,
    M68K_ASM_MNEMONIC_TST = 52,
    M68K_ASM_MNEMONIC_BHI = 53,
    M68K_ASM_MNEMONIC_BLS = 54,
    M68K_ASM_MNEMONIC_BCC = 55,
    M68K_ASM_MNEMONIC_BCS = 56,
    M68K_ASM_MNEMONIC_BNE = 57,
    M68K_ASM_MNEMONIC_BEQ = 58,
    M68K_ASM_MNEMONIC_BVC = 59,
    M68K_ASM_MNEMONIC_BVS = 60,
    M68K_ASM_MNEMONIC_BPL = 61,
    M68K_ASM_MNEMONIC_BMI = 62,
    M68K_ASM_MNEMONIC_BGE = 63,
    M68K_ASM_MNEMONIC_BLT = 64,
    M68K_ASM_MNEMONIC_BGT = 65,
    M68K_ASM_MNEMONIC_BLE = 66,
    M68K_ASM_MNEMONIC_BRA = 67,
    M68K_ASM_MNEMONIC_BSR = 68,
    M68K_ASM_MNEMONIC_DBT = 69,
    M68K_ASM_MNEMONIC_DBF = 70,
    M68K_ASM_MNEMONIC_DBHI = 71,
    M68K_ASM_MNEMONIC_DBLS = 72,
    M68K_ASM_MNEMONIC_DBCC = 73,
    M68K_ASM_MNEMONIC_DBCS = 74,
    M68K_ASM_MNEMONIC_DBNE = 75,
    M68K_ASM_MNEMONIC_DBEQ = 76,
    M68K_ASM_MNEMONIC_DBVC = 77,
    M68K_ASM_MNEMONIC_DBVS = 78,
    M68K_ASM_MNEMONIC_DBPL = 79,
    M68K_ASM_MNEMONIC_DBMI = 80,
    M68K_ASM_MNEMONIC_DBGE = 81,
    M68K_ASM_MNEMONIC_DBLT = 82,
    M68K_ASM_MNEMONIC_DBGT = 83,
    M68K_ASM_MNEMONIC_DBLE = 84,
    M68K_ASM_MNEMONIC_RTS = 85,
    M68K_ASM_MNEMONIC_ST = 86,
    M68K_ASM_MNEMONIC_SF = 87,
    M68K_ASM_MNEMONIC_SHI = 88,
    M68K_ASM_MNEMONIC_SLS = 89,
    M68K_ASM_MNEMONIC_SCC = 90,
    M68K_ASM_MNEMONIC_SCS = 91,
    M68K_ASM_MNEMONIC_SNE = 92,
    M68K_ASM_MNEMONIC_SEQ = 93,
    M68K_ASM_MNEMONIC_SVC = 94,
    M68K_ASM_MNEMONIC_SVS = 95,
    M68K_ASM_MNEMONIC_SPL = 96,
    M68K_ASM_MNEMONIC_SMI = 97,
    M68K_ASM_MNEMONIC_SGE = 98,
    M68K_ASM_MNEMONIC_SLT = 99,
    M68K_ASM_MNEMONIC_SGT = 100,
    M68K_ASM_MNEMONIC_SLE = 101,
    M68K_ASM_MNEMONIC_EXG = 102,
    M68K_ASM_MNEMONIC_EXT = 103,
    M68K_ASM_MNEMONIC_EXTB = 104,
    M68K_ASM_MNEMONIC_JMP = 105,
    M68K_ASM_MNEMONIC_JSR = 106,
    M68K_ASM_MNEMONIC_LEA = 107,
    M68K_ASM_MNEMONIC_LINK = 108,
    M68K_ASM_MNEMONIC_MOVE = 109,
    M68K_ASM_MNEMONIC_MOVEA = 110,
    M68K_ASM_MNEMONIC_MOVE16 = 111,
    M68K_ASM_MNEMONIC_MOVEM = 112,
    M68K_ASM_MNEMONIC_MOVEC = 113,
    M68K_ASM_MNEMONIC_MOVEP = 114,
    M68K_ASM_MNEMONIC_MOVEQ = 115,
    M68K_ASM_MNEMONIC_MULS = 116,
    M68K_ASM_MNEMONIC_MULU = 117,
    M68K_ASM_MNEMONIC_MOVES = 118,
    M68K_ASM_MNEMONIC_PACK = 119,
    M68K_ASM_MNEMONIC_PEA = 120,
    M68K_ASM_MNEMONIC_UNLK = 121,
    M68K_ASM_MNEMONIC_UNPK = 122,
    M68K_ASM_MNEMONIC_SWAP = 123,
    M68K_ASM_MNEMONIC_CLR = 124,
    M68K_ASM_MNEMONIC_NBCD = 125,
    M68K_ASM_MNEMONIC_TAS = 126,
    M68K_ASM_MNEMONIC_BKPT = 127,
    M68K_ASM_MNEMONIC_CALLM = 128,
    M68K_ASM_MNEMONIC_CINVL = 129,
    M68K_ASM_MNEMONIC_CINVP = 130,
    M68K_ASM_MNEMONIC_CINVA = 131,
    M68K_ASM_MNEMONIC_CPUSHL = 132,
    M68K_ASM_MNEMONIC_CPUSHP = 133,
    M68K_ASM_MNEMONIC_CPUSHA = 134,
    M68K_ASM_MNEMONIC_FRESTORE = 135,
    M68K_ASM_MNEMONIC_FSAVE = 136,
    M68K_ASM_MNEMONIC_ILLEGAL = 137,
    M68K_ASM_MNEMONIC_NOP = 138,
    M68K_ASM_MNEMONIC_PFLUSHA = 139,
    M68K_ASM_MNEMONIC_PFLUSH = 140,
    M68K_ASM_MNEMONIC_PFLUSHR = 141,
    M68K_ASM_MNEMONIC_PLOADR = 142,
    M68K_ASM_MNEMONIC_PLOADW = 143,
    M68K_ASM_MNEMONIC_PMOVE = 144,
    M68K_ASM_MNEMONIC_PRESTORE = 145,
    M68K_ASM_MNEMONIC_PSAVE = 146,
    M68K_ASM_MNEMONIC_PTESTR = 147,
    M68K_ASM_MNEMONIC_PTESTW = 148,
    M68K_ASM_MNEMONIC_PVALID = 149,
    M68K_ASM_MNEMONIC_RESET = 150,
    M68K_ASM_MNEMONIC_RTM = 151,
    M68K_ASM_MNEMONIC_RTD = 152,
    M68K_ASM_MNEMONIC_STOP = 153,
    M68K_ASM_MNEMONIC_RTE = 154,
    M68K_ASM_MNEMONIC_RTR = 155,
    M68K_ASM_MNEMONIC_TRAPT = 156,
    M68K_ASM_MNEMONIC_TRAPF = 157,
    M68K_ASM_MNEMONIC_TRAPHI = 158,
    M68K_ASM_MNEMONIC_TRAPLS = 159,
    M68K_ASM_MNEMONIC_TRAPCC = 160,
    M68K_ASM_MNEMONIC_TRAPCS = 161,
    M68K_ASM_MNEMONIC_TRAPNE = 162,
    M68K_ASM_MNEMONIC_TRAPEQ = 163,
    M68K_ASM_MNEMONIC_TRAPVC = 164,
    M68K_ASM_MNEMONIC_TRAPVS = 165,
    M68K_ASM_MNEMONIC_TRAPPL = 166,
    M68K_ASM_MNEMONIC_TRAPMI = 167,
    M68K_ASM_MNEMONIC_TRAPGE = 168,
    M68K_ASM_MNEMONIC_TRAPLT = 169,
    M68K_ASM_MNEMONIC_TRAPGT = 170,
    M68K_ASM_MNEMONIC_TRAPLE = 171,
    M68K_ASM_MNEMONIC_TRAPV = 172,
    M68K_ASM_MNEMONIC_TRAP = 173,
    M68K_ASM_MNEMONIC_COUNT = 174
} M68kAsmMnemonicId;

typedef enum {
    M68K_ASM_CPU_68000 = 0,
    M68K_ASM_CPU_68010 = 1,
    M68K_ASM_CPU_68020 = 2,
    M68K_ASM_CPU_68030 = 3,
    M68K_ASM_CPU_68040 = 4,
    M68K_ASM_CPU_68060 = 5
} M68kAsmCpuMin;

#define M68K_ASM_CPU_MASK_68000 (1u << M68K_ASM_CPU_68000)
#define M68K_ASM_CPU_MASK_68010 (1u << M68K_ASM_CPU_68010)
#define M68K_ASM_CPU_MASK_68020 (1u << M68K_ASM_CPU_68020)
#define M68K_ASM_CPU_MASK_68030 (1u << M68K_ASM_CPU_68030)
#define M68K_ASM_CPU_MASK_68040 (1u << M68K_ASM_CPU_68040)
#define M68K_ASM_CPU_MASK_68060 (1u << M68K_ASM_CPU_68060)

#define M68K_ASM_CPU_ANY 0xFF
#define M68K_ASM_EA_FULL_EXTENSION_CPU_MIN M68K_ASM_CPU_68020

typedef enum {
    M68K_ASM_OPERAND_NONE = 0,
    M68K_ASM_OPERAND_AN,
    M68K_ASM_OPERAND_ABSL,
    M68K_ASM_OPERAND_BF_EA,
    M68K_ASM_OPERAND_CACHE_SEL,
    M68K_ASM_OPERAND_CCR,
    M68K_ASM_OPERAND_CTRL_REG,
    M68K_ASM_OPERAND_DN,
    M68K_ASM_OPERAND_DN_PAIR,
    M68K_ASM_OPERAND_EA,
    M68K_ASM_OPERAND_IMM,
    M68K_ASM_OPERAND_IND,
    M68K_ASM_OPERAND_LABEL,
    M68K_ASM_OPERAND_POSTINC,
    M68K_ASM_OPERAND_REGLIST,
    M68K_ASM_OPERAND_RN,
    M68K_ASM_OPERAND_RN_PAIR,
    M68K_ASM_OPERAND_SR,
    M68K_ASM_OPERAND_USP
} M68kAsmOperandKind;

typedef enum {
    M68K_ASM_FIELD_REGISTER = 0,
    M68K_ASM_FIELD_BITFIELD_OFFSET_DA,
    M68K_ASM_FIELD_BITFIELD_WIDTH_DA,
    M68K_ASM_FIELD_CACHE,
    M68K_ASM_FIELD_DA,
    M68K_ASM_FIELD_MODE,
    M68K_ASM_FIELD_OPMODE,
    M68K_ASM_FIELD_OFFSET,
    M68K_ASM_FIELD_SIZE,
    M68K_ASM_FIELD_DATA,
    M68K_ASM_FIELD_DISPLACEMENT_8,
    M68K_ASM_FIELD_DISPLACEMENT_16,
    M68K_ASM_FIELD_REGLIST_MASK,
    M68K_ASM_FIELD_WIDTH
} M68kAsmFieldKind;

typedef enum {
    M68K_ASM_VALUE_NONE = 0,
    M68K_ASM_VALUE_BF_OFFSET,
    M68K_ASM_VALUE_BF_OFFSET_KIND,
    M68K_ASM_VALUE_BF_WIDTH,
    M68K_ASM_VALUE_BF_WIDTH_KIND,
    M68K_ASM_VALUE_OPMODE,
    M68K_ASM_VALUE_REG,
    M68K_ASM_VALUE_REG_FIRST,
    M68K_ASM_VALUE_REG_SECOND,
    M68K_ASM_VALUE_REG_KIND,
    M68K_ASM_VALUE_REG_KIND_FIRST,
    M68K_ASM_VALUE_REG_KIND_SECOND,
    M68K_ASM_VALUE_EA_REG,
    M68K_ASM_VALUE_EA_MODE,
    M68K_ASM_VALUE_VALUE_HI16,
    M68K_ASM_VALUE_VALUE_LO16,
    M68K_ASM_VALUE_VALUE
} M68kAsmValueSource;

typedef enum {
    M68K_ASM_EXTENSION_EA_SINGLE_WORD = 0,
    M68K_ASM_EXTENSION_EA_LONG_ADDRESS = 1,
    M68K_ASM_EXTENSION_EA_IMMEDIATE = 2,
    M68K_ASM_EXTENSION_EA_INDEX = 3,
    M68K_ASM_EXTENSION_LABEL_DISP16_IF_ZERO = 4,
    M68K_ASM_EXTENSION_LABEL_DISP16_ALWAYS = 5,
    M68K_ASM_EXTENSION_DISP16_ALWAYS = 6
} M68kAsmExtensionKind;

typedef enum {
    M68K_ASM_EA_TEXT_REG_DIRECT = 0,
    M68K_ASM_EA_TEXT_IMMEDIATE = 1,
    M68K_ASM_EA_TEXT_AN_INDIRECT = 2,
    M68K_ASM_EA_TEXT_AN_POSTINC = 3,
    M68K_ASM_EA_TEXT_AN_PREDEC = 4,
    M68K_ASM_EA_TEXT_AN_DISP = 5,
    M68K_ASM_EA_TEXT_AN_INDEX = 6,
    M68K_ASM_EA_TEXT_PC_DISP = 7,
    M68K_ASM_EA_TEXT_PC_INDEX = 8,
    M68K_ASM_EA_TEXT_ABSOLUTE = 9,
} M68kAsmEaTextSyntaxFamily;

typedef enum {
    M68K_ASM_EA_VALUE_NONE = 0,
    M68K_ASM_EA_VALUE_NUMERIC,
    M68K_ASM_EA_VALUE_NUMERIC_OR_LABEL
} M68kAsmEaTextValueKind;

enum {
    M68K_ASM_SIZE_B = 1 << 0,
    M68K_ASM_SIZE_W = 1 << 1,
    M68K_ASM_SIZE_L = 1 << 2
};

enum {
    M68K_ASM_FIELD_VALUE_UNSET = 255
};

enum {
    M68K_ASM_BRIEF_EXT_DA_BIT_LO = 15,
    M68K_ASM_BRIEF_EXT_REGISTER_BIT_LO = 12,
    M68K_ASM_BRIEF_EXT_WL_BIT_LO = 11,
    M68K_ASM_BRIEF_EXT_SCALE_BIT_LO = 9,
    M68K_ASM_BRIEF_EXT_FORMAT_BIT_LO = 8,
    M68K_ASM_BRIEF_EXT_DISPLACEMENT_BIT_LO = 0
};

enum {
    M68K_ASM_FULL_EXT_DA_BIT_LO = 15,
    M68K_ASM_FULL_EXT_REGISTER_BIT_LO = 12,
    M68K_ASM_FULL_EXT_WL_BIT_LO = 11,
    M68K_ASM_FULL_EXT_SCALE_BIT_LO = 9,
    M68K_ASM_FULL_EXT_FORMAT_BIT_LO = 8,
    M68K_ASM_FULL_EXT_BS_BIT_LO = 7,
    M68K_ASM_FULL_EXT_IS_BIT_LO = 6,
    M68K_ASM_FULL_EXT_BD_SIZE_BIT_LO = 4,
    M68K_ASM_FULL_EXT_IIS_BIT_LO = 0
};

enum {
    M68K_ASM_FULL_EXT_BD_RESERVED = 0,
    M68K_ASM_FULL_EXT_BD_NULL = 1,
    M68K_ASM_FULL_EXT_BD_WORD = 2,
    M68K_ASM_FULL_EXT_BD_LONG = 3
};

typedef struct {
    uint8_t field_kind;
    uint8_t word_index;
    uint8_t occurrence;
    uint8_t bit_hi;
    uint8_t bit_lo;
    int8_t operand_index;
    uint8_t value_source;
} M68kAsmFieldPatch;

typedef struct {
    uint8_t kind;
    uint8_t operand_index;
    uint8_t patch_index;
} M68kAsmExtensionDef;

typedef struct {
    const char *name;
    uint16_t id;
    uint16_t value;
    uint8_t cpu_mask;
} M68kAsmControlRegisterDef;

typedef struct {
    const char *name;
    uint8_t syntax_family;
    uint8_t ea_mode;
    int8_t ea_reg;
    uint8_t cpu_mask;
    const char *base_token;
    uint8_t uses_base_register;
    const char *prefix_token;
    const char *suffix_token;
    char register_prefix;
    char size_suffix;
    uint8_t allow_label;
    uint8_t value_kind;
    uint8_t index_required;
} M68kAsmEaTextFormDef;

typedef struct {
    uint8_t kind;
    uint8_t reg;
    uint8_t pair_reg;
    uint8_t reg_is_address;
    uint8_t pair_reg_is_address;
    uint8_t bf_offset_is_register;
    uint8_t bf_offset;
    uint8_t bf_width_is_register;
    uint8_t bf_width;
    uint8_t ea_mode;
    uint8_t ea_reg;
    uint32_t value;
    uint8_t index_is_address;
    uint8_t index_reg;
    uint8_t index_long;
    uint8_t scale;
    uint8_t full_ext_base_suppress;
    uint8_t full_ext_index_suppress;
    uint8_t full_ext_base_disp_size;
    uint8_t full_ext_outer_disp_size;
    uint8_t full_ext_iis;
    uint32_t full_ext_base_disp_value;
    uint32_t full_ext_outer_disp_value;
} M68kAsmOperandValue;

typedef struct {
    const char *mnemonic;
    char size_suffix;
    uint8_t target_cpu;
    size_t operand_count;
    const uint16_t *patch_values;
    size_t patch_value_count;
    const M68kAsmOperandValue *operands;
} M68kAsmInstructionSpec;

typedef struct {
    const char *mnemonic;
    const char *syntax;
    uint8_t mnemonic_id;
    uint8_t form_index;
    uint8_t operand_count;
    uint8_t operand_kinds[4];
    uint8_t size_mask;
    uint8_t size_mask_68000;
    uint8_t ea_dn_size_mask;
    uint8_t ea_memory_size_mask;
    uint8_t cpu_mask;
    uint16_t control_register_start;
    uint8_t control_register_count;
    uint16_t opword_base;
    uint16_t opword_mask;
    uint16_t patch_start;
    uint8_t patch_count;
    uint8_t bound_word_count;
    uint16_t extension_start;
    uint8_t extension_count;
    uint16_t bound_word_bases[2];
    uint16_t bound_word_masks[2];
    uint8_t size_value_b;
    uint8_t size_value_w;
    uint8_t size_value_l;
    uint8_t opmode_value_b;
    uint8_t opmode_value_w;
    uint8_t opmode_value_l;
    uint8_t branch_word_signal;
    uint8_t branch_word_bytes;
    uint8_t branch_long_signal;
    uint8_t branch_long_bytes;
    uint8_t has_bound_word_extension;
} M68kAsmFormDef;

extern const M68kAsmFormDef g_m68k_asm_forms[282];
extern const M68kAsmFieldPatch g_m68k_asm_patches[592];
extern const M68kAsmExtensionDef g_m68k_asm_extensions[530];
extern const M68kAsmControlRegisterDef g_m68k_asm_control_registers[];
extern const uint16_t g_m68k_asm_form_control_register_ids[];
extern const M68kAsmEaTextFormDef g_m68k_asm_ea_text_forms[12];
extern const char *const g_m68k_asm_routed_immediate_mnemonics[];
extern const size_t g_m68k_asm_routed_immediate_mnemonic_count;
extern const size_t g_m68k_asm_control_register_count;
extern const size_t g_m68k_asm_ea_text_form_count;
extern const char *const g_m68k_asm_movem_mask_normal[16];
extern const char *const g_m68k_asm_movem_mask_predecrement[16];

size_t m68k_asm_form_count(void);
size_t m68k_asm_routed_immediate_count(void);
const M68kAsmControlRegisterDef *m68k_asm_find_control_register(const char *name, uint8_t target_cpu);
const M68kAsmEaTextFormDef *m68k_asm_find_ea_text_form(uint8_t syntax_family, char size_suffix, char register_prefix, uint8_t target_cpu);
int m68k_asm_has_routed_immediate(const char *mnemonic);
const M68kAsmFormDef *m68k_asm_find_form(const char *mnemonic, size_t operand_count);
uint8_t m68k_asm_form_effective_size_mask(const M68kAsmFormDef *form);
uint8_t m68k_asm_form_effective_size_mask_for_operands(const M68kAsmFormDef *form, const M68kAsmOperandValue *operands,
    size_t operand_count);
int m68k_asm_form_supports_size_suffix(const M68kAsmFormDef *form, char size_suffix);
int m68k_asm_form_supports_cpu(const M68kAsmFormDef *form, uint8_t target_cpu);
char m68k_asm_choose_size_suffix(const M68kAsmFormDef *form, const M68kAsmOperandValue *operands, size_t operand_count,
    char explicit_suffix);
const M68kAsmFormDef *m68k_asm_find_form_for_operands(const char *mnemonic, const M68kAsmOperandValue *operands, size_t operand_count,
    char size_suffix, uint8_t target_cpu);
size_t m68k_asm_operand_extension_word_count(const M68kAsmFormDef *form, const M68kAsmOperandValue *operand, char size_suffix);
int m68k_asm_encode_opword(const M68kAsmFormDef *form, const uint16_t *field_values, size_t field_value_count, uint16_t *out_opword);
int m68k_asm_emit_extensions(const M68kAsmFormDef *form, const uint16_t *field_values, size_t field_value_count,
    const M68kAsmOperandValue *operands, size_t operand_count, uint16_t *out_words, size_t max_words, size_t *out_word_count);
int m68k_asm_build_patch_values(const M68kAsmFormDef *form, char size_suffix, const M68kAsmOperandValue *operands, size_t operand_count,
    uint16_t *out_field_values, size_t max_field_values);
int m68k_asm_assemble_instruction(const M68kAsmInstructionSpec *spec, uint8_t *out_bytes, size_t max_bytes, size_t *out_byte_count);
uint16_t m68k_asm_encode_full_ext_word(const M68kAsmOperandValue *operand);
uint16_t m68k_asm_branch_signal_value(const M68kAsmFormDef *form, char size_suffix);
size_t m68k_asm_branch_extension_bytes(const M68kAsmFormDef *form, char size_suffix);

#endif
