#ifndef M68K_SOURCE_EXPORT_H
#define M68K_SOURCE_EXPORT_H

typedef enum M68kSourceExportFailureKind {
  M68K_SOURCE_EXPORT_FAILURE_NONE = 0,
  M68K_SOURCE_EXPORT_FAILURE_RENDER = 1,
  M68K_SOURCE_EXPORT_FAILURE_BYTE_MISMATCH = 2,
  M68K_SOURCE_EXPORT_FAILURE_INSTRUCTION_RELOCATION = 3,
  M68K_SOURCE_EXPORT_FAILURE_UNRESOLVED_LABEL = 4,
  M68K_SOURCE_EXPORT_FAILURE_INTERIOR_CONFLICT = 5,
  M68K_SOURCE_EXPORT_FAILURE_RELOCATION = 6,
  M68K_SOURCE_EXPORT_FAILURE_RELOCATION_ANCHOR = 7,
  M68K_SOURCE_EXPORT_FAILURE_UNASSEMBLABLE_HUNK_DATA_RELOCATION = 8,
  M68K_SOURCE_EXPORT_FAILURE_UNASSEMBLABLE_HUNK_BASE_REGISTER_RELOCATION = 9,
  M68K_SOURCE_EXPORT_FAILURE_REQUIRED_INSTRUCTION = 10,
  M68K_SOURCE_EXPORT_FAILURE_TABLE_TARGET_SET_LIMIT = 11,
  M68K_SOURCE_EXPORT_FAILURE_SOURCE_QUALITY = 12
} M68kSourceExportFailureKind;

#endif
