"""Generated runtime M68K analysis knowledge artifact. Do not edit directly."""

from __future__ import annotations

from enum import StrEnum

class Processor(StrEnum):
    M68000 = '68000'
    M68008 = '68008'
    M68010 = '68010'
    M68020 = '68020'
    M68030 = '68030'
    M68040 = '68040'
    CPU32 = 'CPU32'
    MC68851 = '68851'

class FlowType(StrEnum):
    SEQUENTIAL = 'sequential'
    BRANCH = 'branch'
    JUMP = 'jump'
    CALL = 'call'
    RETURN = 'return'
    TRAP = 'trap'

class OperationType(StrEnum):
    ADD = 'add'
    ADD_DECIMAL = 'add_decimal'
    ADDX = 'addx'
    AND = 'and'
    BIT_TEST = 'bit_test'
    BITFIELD = 'bitfield'
    BOUNDS_CHECK = 'bounds_check'
    CCR_OP = 'ccr_op'
    CLEAR = 'clear'
    COMPARE = 'compare'
    COMPARE_SWAP = 'compare_swap'
    DIVIDE = 'divide'
    MOVE = 'move'
    MULTIPLY = 'multiply'
    NEG = 'neg'
    NEGX = 'negx'
    NOT = 'not'
    OR = 'or'
    ROTATE = 'rotate'
    ROTATE_EXTEND = 'rotate_extend'
    SHIFT = 'shift'
    SIGN_EXTEND = 'sign_extend'
    SR_OP = 'sr_op'
    SUB = 'sub'
    SUB_DECIMAL = 'sub_decimal'
    SUBX = 'subx'
    SWAP = 'swap'
    TEST = 'test'
    XOR = 'xor'

class OperationClass(StrEnum):
    LOAD_EFFECTIVE_ADDRESS = 'load_effective_address'
    MULTI_REGISTER_TRANSFER = 'multi_register_transfer'

class ComputeOp(StrEnum):
    ADD = 'add'
    ADD_DECIMAL = 'add_decimal'
    ASSIGN = 'assign'
    BIT_CHANGE = 'bit_change'
    BIT_CLEAR = 'bit_clear'
    BIT_SET = 'bit_set'
    BIT_TEST = 'bit_test'
    BITWISE_AND = 'bitwise_and'
    BITWISE_COMPLEMENT = 'bitwise_complement'
    BITWISE_OR = 'bitwise_or'
    BITWISE_XOR = 'bitwise_xor'
    DIVIDE = 'divide'
    EXCHANGE = 'exchange'
    MULTIPLY = 'multiply'
    ROTATE = 'rotate'
    ROTATE_EXTEND = 'rotate_extend'
    SHIFT = 'shift'
    SIGN_EXTEND = 'sign_extend'
    SUBTRACT = 'subtract'
    SUBTRACT_DECIMAL = 'subtract_decimal'
    TEST = 'test'

class FormulaTerm(StrEnum):
    SOURCE = 'source'
    DESTINATION = 'destination'
    EXTEND = 'X'
    IMPLICIT = 'implicit'

class TruncationMode(StrEnum):
    TOWARD_ZERO = 'toward_zero'

class SpEffectAction(StrEnum):
    DECREMENT = 'decrement'
    INCREMENT = 'increment'
    ADJUST = 'adjust'
    SAVE_TO_REG = 'save_to_reg'
    LOAD_FROM_REG = 'load_from_reg'

OPWORD_BYTES = 2
DEFAULT_OPERAND_SIZE = 'w'
SIZE_BYTE_COUNT = {'b': 1, 'w': 2, 'l': 4}
EA_MODE_ENCODING = {'dn': [0, None],
 'an': [1, None],
 'ind': [2, None],
 'postinc': [3, None],
 'predec': [4, None],
 'disp': [5, None],
 'index': [6, None],
 'absw': [7, 0],
 'absl': [7, 1],
 'pcdisp': [7, 2],
 'pcindex': [7, 3],
 'imm': [7, 4]}
EA_REVERSE = {(0, 0): 'dn',
 (0, 1): 'dn',
 (0, 2): 'dn',
 (0, 3): 'dn',
 (0, 4): 'dn',
 (0, 5): 'dn',
 (0, 6): 'dn',
 (0, 7): 'dn',
 (1, 0): 'an',
 (1, 1): 'an',
 (1, 2): 'an',
 (1, 3): 'an',
 (1, 4): 'an',
 (1, 5): 'an',
 (1, 6): 'an',
 (1, 7): 'an',
 (2, 0): 'ind',
 (2, 1): 'ind',
 (2, 2): 'ind',
 (2, 3): 'ind',
 (2, 4): 'ind',
 (2, 5): 'ind',
 (2, 6): 'ind',
 (2, 7): 'ind',
 (3, 0): 'postinc',
 (3, 1): 'postinc',
 (3, 2): 'postinc',
 (3, 3): 'postinc',
 (3, 4): 'postinc',
 (3, 5): 'postinc',
 (3, 6): 'postinc',
 (3, 7): 'postinc',
 (4, 0): 'predec',
 (4, 1): 'predec',
 (4, 2): 'predec',
 (4, 3): 'predec',
 (4, 4): 'predec',
 (4, 5): 'predec',
 (4, 6): 'predec',
 (4, 7): 'predec',
 (5, 0): 'disp',
 (5, 1): 'disp',
 (5, 2): 'disp',
 (5, 3): 'disp',
 (5, 4): 'disp',
 (5, 5): 'disp',
 (5, 6): 'disp',
 (5, 7): 'disp',
 (6, 0): 'index',
 (6, 1): 'index',
 (6, 2): 'index',
 (6, 3): 'index',
 (6, 4): 'index',
 (6, 5): 'index',
 (6, 6): 'index',
 (6, 7): 'index',
 (7, 0): 'absw',
 (7, 1): 'absl',
 (7, 2): 'pcdisp',
 (7, 3): 'pcindex',
 (7, 4): 'imm'}
EA_BRIEF_FIELDS = {'D/A': (15, 15, 1),
 'REGISTER': (14, 12, 3),
 'W/L': (11, 11, 1),
 'SCALE': (10, 9, 2),
 'DISPLACEMENT': (7, 0, 8)}
EA_MODE_SIZES = {'dn': ['b', 'w', 'l'],
 'an': ['w', 'l'],
 'ind': ['b', 'w', 'l'],
 'postinc': ['b', 'w', 'l'],
 'predec': ['b', 'w', 'l'],
 'disp': ['b', 'w', 'l'],
 'index': ['b', 'w', 'l'],
 'absw': ['b', 'w', 'l'],
 'absl': ['b', 'w', 'l'],
 'pcdisp': ['b', 'w', 'l'],
 'pcindex': ['b', 'w', 'l'],
 'imm': ['b', 'w', 'l']}
MOVEM_REG_MASKS = {'normal': ['d0',
            'd1',
            'd2',
            'd3',
            'd4',
            'd5',
            'd6',
            'd7',
            'a0',
            'a1',
            'a2',
            'a3',
            'a4',
            'a5',
            'a6',
            'a7'],
 'predecrement': ['a7',
                  'a6',
                  'a5',
                  'a4',
                  'a3',
                  'a2',
                  'a1',
                  'a0',
                  'd7',
                  'd6',
                  'd5',
                  'd4',
                  'd3',
                  'd2',
                  'd1',
                  'd0']}
CC_TEST_DEFINITIONS = {'t': (0, 'true'),
 'f': (1, 'false'),
 'hi': (2, '!C & !Z'),
 'ls': (3, 'C | Z'),
 'cc': (4, '!C'),
 'cs': (5, 'C'),
 'ne': (6, '!Z'),
 'eq': (7, 'Z'),
 'vc': (8, '!V'),
 'vs': (9, 'V'),
 'pl': (10, '!N'),
 'mi': (11, 'N'),
 'ge': (12, '(N & V) | (!N & !V)'),
 'lt': (13, '(N & !V) | (!N & V)'),
 'gt': (14, '(N & V & !Z) | (!N & !V & !Z)'),
 'le': (15, 'Z | (N & !V) | (!N & V)')}
CC_ALIASES = {'lo': 'cs', 'ra': 'f'}
REGISTER_ALIASES = {'sp': 'a7'}
NUM_DATA_REGS = 8
NUM_ADDR_REGS = 8
SP_REG_NUM = 7
RTS_SP_INC = 4
ADDR_SIZE = 'l'
ADDR_MASK = 4294967295
CCR_FLAG_NAMES = ('C', 'V', 'Z', 'N', 'X')
OPERATION_TYPES = {'ABCD': OperationType.ADD_DECIMAL,
 'ADD': OperationType.ADD,
 'ADDA': OperationType.ADD,
 'ADDI': OperationType.ADD,
 'ADDQ': OperationType.ADD,
 'ADDX': OperationType.ADDX,
 'AND': OperationType.AND,
 'ANDI': OperationType.AND,
 'ANDI to CCR': OperationType.CCR_OP,
 'ANDI to SR': OperationType.SR_OP,
 'ASL, ASR': OperationType.SHIFT,
 'BCHG': OperationType.BIT_TEST,
 'BCLR': OperationType.BIT_TEST,
 'BFCHG': OperationType.BITFIELD,
 'BFCLR': OperationType.BITFIELD,
 'BFEXTS': OperationType.BITFIELD,
 'BFEXTU': OperationType.BITFIELD,
 'BFFFO': OperationType.BITFIELD,
 'BFINS': OperationType.BITFIELD,
 'BFSET': OperationType.BITFIELD,
 'BFTST': OperationType.BITFIELD,
 'BKPT': None,
 'BRA': OperationType.ADD,
 'BSET': OperationType.BIT_TEST,
 'BSR': OperationType.SUB,
 'BTST': OperationType.BIT_TEST,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': OperationType.COMPARE_SWAP,
 'CHK': OperationType.BOUNDS_CHECK,
 'CHK2': OperationType.BOUNDS_CHECK,
 'CINV': OperationType.SR_OP,
 'CLR': OperationType.CLEAR,
 'CMP': OperationType.COMPARE,
 'CMP2': OperationType.BOUNDS_CHECK,
 'CMPA': OperationType.COMPARE,
 'CMPI': OperationType.COMPARE,
 'CMPM': OperationType.COMPARE,
 'CPUSH': OperationType.SR_OP,
 'DBcc': None,
 'DIVS, DIVSL': OperationType.DIVIDE,
 'DIVU, DIVUL': OperationType.DIVIDE,
 'EOR': OperationType.XOR,
 'EORI': OperationType.XOR,
 'EORI to CCR': OperationType.CCR_OP,
 'EORI to SR': OperationType.SR_OP,
 'EXG': OperationType.SWAP,
 'EXT, EXTB': OperationType.SIGN_EXTEND,
 'FRESTORE': OperationType.SR_OP,
 'FSAVE': OperationType.SR_OP,
 'ILLEGAL': OperationType.SUB,
 'JMP': OperationType.MOVE,
 'JSR': OperationType.SUB,
 'LEA': OperationType.MOVE,
 'LINK': OperationType.SUB,
 'LSL, LSR': OperationType.SHIFT,
 'MOVE': OperationType.MOVE,
 'MOVE USP': OperationType.SR_OP,
 'MOVE from CCR': OperationType.CCR_OP,
 'MOVE from SR': OperationType.MOVE,
 'MOVE to CCR': OperationType.CCR_OP,
 'MOVE to SR': OperationType.SR_OP,
 'MOVE16': OperationType.MOVE,
 'MOVEA': OperationType.MOVE,
 'MOVEC': OperationType.SR_OP,
 'MOVEM': OperationType.MOVE,
 'MOVEP': OperationType.MOVE,
 'MOVEQ': OperationType.MOVE,
 'MOVES': OperationType.SR_OP,
 'MULS': OperationType.MULTIPLY,
 'MULU': OperationType.MULTIPLY,
 'NBCD': OperationType.NEGX,
 'NEG': OperationType.NEG,
 'NEGX': OperationType.NEGX,
 'NOP': None,
 'NOT': OperationType.NOT,
 'OR': OperationType.OR,
 'ORI': OperationType.OR,
 'ORI to CCR': OperationType.CCR_OP,
 'ORI to SR': OperationType.SR_OP,
 'PACK': OperationType.ADD,
 'PBcc': OperationType.SR_OP,
 'PDBcc': OperationType.SR_OP,
 'PEA': OperationType.SUB,
 'PFLUSH': OperationType.SR_OP,
 'PFLUSH PFLUSHA': OperationType.SR_OP,
 'PFLUSHR': OperationType.SR_OP,
 'PLOAD': OperationType.SR_OP,
 'PMOVE': OperationType.SR_OP,
 'PRESTORE': OperationType.SR_OP,
 'PSAVE': OperationType.SR_OP,
 'PScc': OperationType.SR_OP,
 'PTEST': OperationType.SR_OP,
 'PTRAPcc': OperationType.SR_OP,
 'PVALID': OperationType.MOVE,
 'RESET': OperationType.SR_OP,
 'ROL, ROR': OperationType.ROTATE,
 'ROXL, ROXR': OperationType.ROTATE_EXTEND,
 'RTD': OperationType.ADD,
 'RTE': OperationType.SR_OP,
 'RTM': None,
 'RTR': OperationType.CCR_OP,
 'RTS': OperationType.ADD,
 'SBCD': OperationType.SUB_DECIMAL,
 'STOP': OperationType.SR_OP,
 'SUB': OperationType.SUB,
 'SUBA': OperationType.SUB,
 'SUBI': OperationType.SUB,
 'SUBQ': OperationType.SUB,
 'SUBX': OperationType.SUBX,
 'SWAP': OperationType.SWAP,
 'Scc': None,
 'TAS': OperationType.TEST,
 'TRAP': OperationType.MOVE,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': OperationType.TEST,
 'UNLK': OperationType.ADD,
 'UNPK': OperationType.ADD,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': OperationType.SR_OP,
 'cpSAVE': OperationType.SR_OP,
 'cpScc': None,
 'cpTRAPcc': None}
OPERATION_CLASSES = {'ABCD': None,
 'ADD': None,
 'ADDA': None,
 'ADDI': None,
 'ADDQ': None,
 'ADDX': None,
 'AND': None,
 'ANDI': None,
 'ANDI to CCR': None,
 'ANDI to SR': None,
 'ASL, ASR': None,
 'BCHG': None,
 'BCLR': None,
 'BFCHG': None,
 'BFCLR': None,
 'BFEXTS': None,
 'BFEXTU': None,
 'BFFFO': None,
 'BFINS': None,
 'BFSET': None,
 'BFTST': None,
 'BKPT': None,
 'BRA': None,
 'BSET': None,
 'BSR': None,
 'BTST': None,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': None,
 'CHK': None,
 'CHK2': None,
 'CINV': None,
 'CLR': None,
 'CMP': None,
 'CMP2': None,
 'CMPA': None,
 'CMPI': None,
 'CMPM': None,
 'CPUSH': None,
 'DBcc': None,
 'DIVS, DIVSL': None,
 'DIVU, DIVUL': None,
 'EOR': None,
 'EORI': None,
 'EORI to CCR': None,
 'EORI to SR': None,
 'EXG': None,
 'EXT, EXTB': None,
 'FRESTORE': None,
 'FSAVE': None,
 'ILLEGAL': None,
 'JMP': None,
 'JSR': None,
 'LEA': OperationClass.LOAD_EFFECTIVE_ADDRESS,
 'LINK': None,
 'LSL, LSR': None,
 'MOVE': None,
 'MOVE USP': None,
 'MOVE from CCR': None,
 'MOVE from SR': None,
 'MOVE to CCR': None,
 'MOVE to SR': None,
 'MOVE16': None,
 'MOVEA': None,
 'MOVEC': None,
 'MOVEM': OperationClass.MULTI_REGISTER_TRANSFER,
 'MOVEP': None,
 'MOVEQ': None,
 'MOVES': None,
 'MULS': None,
 'MULU': None,
 'NBCD': None,
 'NEG': None,
 'NEGX': None,
 'NOP': None,
 'NOT': None,
 'OR': None,
 'ORI': None,
 'ORI to CCR': None,
 'ORI to SR': None,
 'PACK': None,
 'PBcc': None,
 'PDBcc': None,
 'PEA': None,
 'PFLUSH': None,
 'PFLUSH PFLUSHA': None,
 'PFLUSHR': None,
 'PLOAD': None,
 'PMOVE': None,
 'PRESTORE': None,
 'PSAVE': None,
 'PScc': None,
 'PTEST': None,
 'PTRAPcc': None,
 'PVALID': None,
 'RESET': None,
 'ROL, ROR': None,
 'ROXL, ROXR': None,
 'RTD': None,
 'RTE': None,
 'RTM': None,
 'RTR': None,
 'RTS': None,
 'SBCD': None,
 'STOP': None,
 'SUB': None,
 'SUBA': None,
 'SUBI': None,
 'SUBQ': None,
 'SUBX': None,
 'SWAP': None,
 'Scc': None,
 'TAS': None,
 'TRAP': None,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': None,
 'UNLK': None,
 'UNPK': None,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': None,
 'cpSAVE': None,
 'cpScc': None,
 'cpTRAPcc': None}
SOURCE_SIGN_EXTEND = ('ADDA', 'CMPA', 'MOVEA', 'SUBA')
FLOW_TYPES = {'ABCD': FlowType.SEQUENTIAL,
 'ADD': FlowType.SEQUENTIAL,
 'ADDA': FlowType.SEQUENTIAL,
 'ADDI': FlowType.SEQUENTIAL,
 'ADDQ': FlowType.SEQUENTIAL,
 'ADDX': FlowType.SEQUENTIAL,
 'AND': FlowType.SEQUENTIAL,
 'ANDI': FlowType.SEQUENTIAL,
 'ANDI to CCR': FlowType.SEQUENTIAL,
 'ANDI to SR': FlowType.SEQUENTIAL,
 'ASL, ASR': FlowType.SEQUENTIAL,
 'BCHG': FlowType.SEQUENTIAL,
 'BCLR': FlowType.SEQUENTIAL,
 'BFCHG': FlowType.SEQUENTIAL,
 'BFCLR': FlowType.SEQUENTIAL,
 'BFEXTS': FlowType.SEQUENTIAL,
 'BFEXTU': FlowType.SEQUENTIAL,
 'BFFFO': FlowType.SEQUENTIAL,
 'BFINS': FlowType.SEQUENTIAL,
 'BFSET': FlowType.SEQUENTIAL,
 'BFTST': FlowType.SEQUENTIAL,
 'BKPT': FlowType.TRAP,
 'BRA': FlowType.BRANCH,
 'BSET': FlowType.SEQUENTIAL,
 'BSR': FlowType.CALL,
 'BTST': FlowType.SEQUENTIAL,
 'Bcc': FlowType.BRANCH,
 'CALLM': FlowType.SEQUENTIAL,
 'CAS CAS2': FlowType.SEQUENTIAL,
 'CHK': FlowType.SEQUENTIAL,
 'CHK2': FlowType.SEQUENTIAL,
 'CINV': FlowType.SEQUENTIAL,
 'CLR': FlowType.SEQUENTIAL,
 'CMP': FlowType.SEQUENTIAL,
 'CMP2': FlowType.SEQUENTIAL,
 'CMPA': FlowType.SEQUENTIAL,
 'CMPI': FlowType.SEQUENTIAL,
 'CMPM': FlowType.SEQUENTIAL,
 'CPUSH': FlowType.SEQUENTIAL,
 'DBcc': FlowType.BRANCH,
 'DIVS, DIVSL': FlowType.SEQUENTIAL,
 'DIVU, DIVUL': FlowType.SEQUENTIAL,
 'EOR': FlowType.SEQUENTIAL,
 'EORI': FlowType.SEQUENTIAL,
 'EORI to CCR': FlowType.SEQUENTIAL,
 'EORI to SR': FlowType.SEQUENTIAL,
 'EXG': FlowType.SEQUENTIAL,
 'EXT, EXTB': FlowType.SEQUENTIAL,
 'FRESTORE': FlowType.SEQUENTIAL,
 'FSAVE': FlowType.SEQUENTIAL,
 'ILLEGAL': FlowType.TRAP,
 'JMP': FlowType.JUMP,
 'JSR': FlowType.CALL,
 'LEA': FlowType.SEQUENTIAL,
 'LINK': FlowType.SEQUENTIAL,
 'LSL, LSR': FlowType.SEQUENTIAL,
 'MOVE': FlowType.SEQUENTIAL,
 'MOVE USP': FlowType.SEQUENTIAL,
 'MOVE from CCR': FlowType.SEQUENTIAL,
 'MOVE from SR': FlowType.SEQUENTIAL,
 'MOVE to CCR': FlowType.SEQUENTIAL,
 'MOVE to SR': FlowType.SEQUENTIAL,
 'MOVE16': FlowType.SEQUENTIAL,
 'MOVEA': FlowType.SEQUENTIAL,
 'MOVEC': FlowType.SEQUENTIAL,
 'MOVEM': FlowType.SEQUENTIAL,
 'MOVEP': FlowType.SEQUENTIAL,
 'MOVEQ': FlowType.SEQUENTIAL,
 'MOVES': FlowType.SEQUENTIAL,
 'MULS': FlowType.SEQUENTIAL,
 'MULU': FlowType.SEQUENTIAL,
 'NBCD': FlowType.SEQUENTIAL,
 'NEG': FlowType.SEQUENTIAL,
 'NEGX': FlowType.SEQUENTIAL,
 'NOP': FlowType.SEQUENTIAL,
 'NOT': FlowType.SEQUENTIAL,
 'OR': FlowType.SEQUENTIAL,
 'ORI': FlowType.SEQUENTIAL,
 'ORI to CCR': FlowType.SEQUENTIAL,
 'ORI to SR': FlowType.SEQUENTIAL,
 'PACK': FlowType.SEQUENTIAL,
 'PBcc': FlowType.BRANCH,
 'PDBcc': FlowType.BRANCH,
 'PEA': FlowType.SEQUENTIAL,
 'PFLUSH': FlowType.SEQUENTIAL,
 'PFLUSH PFLUSHA': FlowType.SEQUENTIAL,
 'PFLUSHR': FlowType.SEQUENTIAL,
 'PLOAD': FlowType.SEQUENTIAL,
 'PMOVE': FlowType.SEQUENTIAL,
 'PRESTORE': FlowType.SEQUENTIAL,
 'PSAVE': FlowType.SEQUENTIAL,
 'PScc': FlowType.SEQUENTIAL,
 'PTEST': FlowType.SEQUENTIAL,
 'PTRAPcc': FlowType.TRAP,
 'PVALID': FlowType.SEQUENTIAL,
 'RESET': FlowType.SEQUENTIAL,
 'ROL, ROR': FlowType.SEQUENTIAL,
 'ROXL, ROXR': FlowType.SEQUENTIAL,
 'RTD': FlowType.RETURN,
 'RTE': FlowType.RETURN,
 'RTM': FlowType.SEQUENTIAL,
 'RTR': FlowType.RETURN,
 'RTS': FlowType.RETURN,
 'SBCD': FlowType.SEQUENTIAL,
 'STOP': FlowType.TRAP,
 'SUB': FlowType.SEQUENTIAL,
 'SUBA': FlowType.SEQUENTIAL,
 'SUBI': FlowType.SEQUENTIAL,
 'SUBQ': FlowType.SEQUENTIAL,
 'SUBX': FlowType.SEQUENTIAL,
 'SWAP': FlowType.SEQUENTIAL,
 'Scc': FlowType.SEQUENTIAL,
 'TAS': FlowType.SEQUENTIAL,
 'TRAP': FlowType.TRAP,
 'TRAPV': FlowType.TRAP,
 'TRAPcc': FlowType.TRAP,
 'TST': FlowType.SEQUENTIAL,
 'UNLK': FlowType.SEQUENTIAL,
 'UNPK': FlowType.SEQUENTIAL,
 'cpBcc': FlowType.BRANCH,
 'cpDBcc': FlowType.BRANCH,
 'cpGEN': FlowType.SEQUENTIAL,
 'cpRESTORE': FlowType.SEQUENTIAL,
 'cpSAVE': FlowType.SEQUENTIAL,
 'cpScc': FlowType.SEQUENTIAL,
 'cpTRAPcc': FlowType.TRAP}
FLOW_CONDITIONAL = {'ABCD': False,
 'ADD': False,
 'ADDA': False,
 'ADDI': False,
 'ADDQ': False,
 'ADDX': False,
 'AND': False,
 'ANDI': False,
 'ANDI to CCR': False,
 'ANDI to SR': False,
 'ASL, ASR': False,
 'BCHG': False,
 'BCLR': False,
 'BFCHG': False,
 'BFCLR': False,
 'BFEXTS': False,
 'BFEXTU': False,
 'BFFFO': False,
 'BFINS': False,
 'BFSET': False,
 'BFTST': False,
 'BKPT': False,
 'BRA': False,
 'BSET': False,
 'BSR': False,
 'BTST': False,
 'Bcc': True,
 'CALLM': False,
 'CAS CAS2': False,
 'CHK': False,
 'CHK2': False,
 'CINV': False,
 'CLR': False,
 'CMP': False,
 'CMP2': False,
 'CMPA': False,
 'CMPI': False,
 'CMPM': False,
 'CPUSH': False,
 'DBcc': True,
 'DIVS, DIVSL': False,
 'DIVU, DIVUL': False,
 'EOR': False,
 'EORI': False,
 'EORI to CCR': False,
 'EORI to SR': False,
 'EXG': False,
 'EXT, EXTB': False,
 'FRESTORE': False,
 'FSAVE': False,
 'ILLEGAL': False,
 'JMP': False,
 'JSR': False,
 'LEA': False,
 'LINK': False,
 'LSL, LSR': False,
 'MOVE': False,
 'MOVE USP': False,
 'MOVE from CCR': False,
 'MOVE from SR': False,
 'MOVE to CCR': False,
 'MOVE to SR': False,
 'MOVE16': False,
 'MOVEA': False,
 'MOVEC': False,
 'MOVEM': False,
 'MOVEP': False,
 'MOVEQ': False,
 'MOVES': False,
 'MULS': False,
 'MULU': False,
 'NBCD': False,
 'NEG': False,
 'NEGX': False,
 'NOP': False,
 'NOT': False,
 'OR': False,
 'ORI': False,
 'ORI to CCR': False,
 'ORI to SR': False,
 'PACK': False,
 'PBcc': True,
 'PDBcc': True,
 'PEA': False,
 'PFLUSH': False,
 'PFLUSH PFLUSHA': False,
 'PFLUSHR': False,
 'PLOAD': False,
 'PMOVE': False,
 'PRESTORE': False,
 'PSAVE': False,
 'PScc': False,
 'PTEST': False,
 'PTRAPcc': True,
 'PVALID': False,
 'RESET': False,
 'ROL, ROR': False,
 'ROXL, ROXR': False,
 'RTD': False,
 'RTE': False,
 'RTM': False,
 'RTR': False,
 'RTS': False,
 'SBCD': False,
 'STOP': False,
 'SUB': False,
 'SUBA': False,
 'SUBI': False,
 'SUBQ': False,
 'SUBX': False,
 'SWAP': False,
 'Scc': False,
 'TAS': False,
 'TRAP': False,
 'TRAPV': True,
 'TRAPcc': True,
 'TST': False,
 'UNLK': False,
 'UNPK': False,
 'cpBcc': True,
 'cpDBcc': True,
 'cpGEN': False,
 'cpRESTORE': False,
 'cpSAVE': False,
 'cpScc': False,
 'cpTRAPcc': True}
BOUNDS_CHECKS = {'ABCD': None,
 'ADD': None,
 'ADDA': None,
 'ADDI': None,
 'ADDQ': None,
 'ADDX': None,
 'AND': None,
 'ANDI': None,
 'ANDI to CCR': None,
 'ANDI to SR': None,
 'ASL, ASR': None,
 'BCHG': None,
 'BCLR': None,
 'BFCHG': None,
 'BFCLR': None,
 'BFEXTS': None,
 'BFEXTU': None,
 'BFFFO': None,
 'BFINS': None,
 'BFSET': None,
 'BFTST': None,
 'BKPT': None,
 'BRA': None,
 'BSET': None,
 'BSR': None,
 'BTST': None,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': None,
 'CHK': ('destination', 'zero', 'source', 'signed', False, True),
 'CHK2': ('rn', 'ea_lower', 'ea_upper', None, True, True),
 'CINV': None,
 'CLR': None,
 'CMP': None,
 'CMP2': ('rn', 'ea_lower', 'ea_upper', None, True, False),
 'CMPA': None,
 'CMPI': None,
 'CMPM': None,
 'CPUSH': None,
 'DBcc': None,
 'DIVS, DIVSL': None,
 'DIVU, DIVUL': None,
 'EOR': None,
 'EORI': None,
 'EORI to CCR': None,
 'EORI to SR': None,
 'EXG': None,
 'EXT, EXTB': None,
 'FRESTORE': None,
 'FSAVE': None,
 'ILLEGAL': None,
 'JMP': None,
 'JSR': None,
 'LEA': None,
 'LINK': None,
 'LSL, LSR': None,
 'MOVE': None,
 'MOVE USP': None,
 'MOVE from CCR': None,
 'MOVE from SR': None,
 'MOVE to CCR': None,
 'MOVE to SR': None,
 'MOVE16': None,
 'MOVEA': None,
 'MOVEC': None,
 'MOVEM': None,
 'MOVEP': None,
 'MOVEQ': None,
 'MOVES': None,
 'MULS': None,
 'MULU': None,
 'NBCD': None,
 'NEG': None,
 'NEGX': None,
 'NOP': None,
 'NOT': None,
 'OR': None,
 'ORI': None,
 'ORI to CCR': None,
 'ORI to SR': None,
 'PACK': None,
 'PBcc': None,
 'PDBcc': None,
 'PEA': None,
 'PFLUSH': None,
 'PFLUSH PFLUSHA': None,
 'PFLUSHR': None,
 'PLOAD': None,
 'PMOVE': None,
 'PRESTORE': None,
 'PSAVE': None,
 'PScc': None,
 'PTEST': None,
 'PTRAPcc': None,
 'PVALID': None,
 'RESET': None,
 'ROL, ROR': None,
 'ROXL, ROXR': None,
 'RTD': None,
 'RTE': None,
 'RTM': None,
 'RTR': None,
 'RTS': None,
 'SBCD': None,
 'STOP': None,
 'SUB': None,
 'SUBA': None,
 'SUBI': None,
 'SUBQ': None,
 'SUBX': None,
 'SWAP': None,
 'Scc': None,
 'TAS': None,
 'TRAP': None,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': None,
 'UNLK': None,
 'UNPK': None,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': None,
 'cpSAVE': None,
 'cpScc': None,
 'cpTRAPcc': None}
COMPUTE_FORMULAS = {'ABCD': (ComputeOp.ADD_DECIMAL, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION, FormulaTerm.EXTEND), None, None, (), None),
 'ADD': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ADDA': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ADDI': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ADDQ': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ADDX': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION, FormulaTerm.EXTEND), None, None, (), None),
 'AND': (ComputeOp.BITWISE_AND, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ANDI': (ComputeOp.BITWISE_AND, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ASL, ASR': (ComputeOp.SHIFT, (), None, None, (), None),
 'BCHG': (ComputeOp.BIT_CHANGE, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'BCLR': (ComputeOp.BIT_CLEAR, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'BRA': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'BSET': (ComputeOp.BIT_SET, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'BTST': (ComputeOp.BIT_TEST, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'CLR': (ComputeOp.ASSIGN, (FormulaTerm.IMPLICIT,), None, None, (), None),
 'CMP': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'CMPA': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'CMPI': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'CMPM': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'DIVS, DIVSL': (ComputeOp.DIVIDE, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), TruncationMode.TOWARD_ZERO),
 'DIVU, DIVUL': (ComputeOp.DIVIDE, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), TruncationMode.TOWARD_ZERO),
 'EOR': (ComputeOp.BITWISE_XOR, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'EORI': (ComputeOp.BITWISE_XOR, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'EXT, EXTB': (ComputeOp.SIGN_EXTEND, (FormulaTerm.DESTINATION,), None, None, (('w', 8), ('l', 16), ('extb_l', 8)), None),
 'JMP': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'LEA': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'LSL, LSR': (ComputeOp.SHIFT, (), None, None, (), None),
 'MOVE': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVE from SR': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVE16': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVEA': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVEM': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVEP': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MOVEQ': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'MULS': (ComputeOp.MULTIPLY, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'MULU': (ComputeOp.MULTIPLY, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'NBCD': (ComputeOp.SUBTRACT_DECIMAL, (FormulaTerm.IMPLICIT, FormulaTerm.DESTINATION, FormulaTerm.EXTEND), None, None, (), None),
 'NEG': (ComputeOp.SUBTRACT, (FormulaTerm.IMPLICIT, FormulaTerm.DESTINATION), None, None, (), None),
 'NEGX': (ComputeOp.SUBTRACT, (FormulaTerm.IMPLICIT, FormulaTerm.DESTINATION, FormulaTerm.EXTEND), None, None, (), None),
 'NOT': (ComputeOp.BITWISE_COMPLEMENT, (FormulaTerm.DESTINATION,), None, None, (), None),
 'OR': (ComputeOp.BITWISE_OR, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'ORI': (ComputeOp.BITWISE_OR, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'PACK': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None),
 'PEA': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'PVALID': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'ROL, ROR': (ComputeOp.ROTATE, (), None, None, (), None),
 'ROXL, ROXR': (ComputeOp.ROTATE_EXTEND, (), None, None, (), None),
 'SBCD': (ComputeOp.SUBTRACT_DECIMAL, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE, FormulaTerm.EXTEND), None, None, (), None),
 'SUB': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'SUBA': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'SUBI': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'SUBQ': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE), None, None, (), None),
 'SUBX': (ComputeOp.SUBTRACT, (FormulaTerm.DESTINATION, FormulaTerm.SOURCE, FormulaTerm.EXTEND), None, None, (), None),
 'SWAP': (ComputeOp.EXCHANGE, (), (31, 16), (15, 0), (), None),
 'TAS': (ComputeOp.TEST, (FormulaTerm.DESTINATION,), None, None, (), None),
 'TRAP': (ComputeOp.ASSIGN, (FormulaTerm.SOURCE,), None, None, (), None),
 'TST': (ComputeOp.TEST, (FormulaTerm.DESTINATION,), None, None, (), None),
 'UNPK': (ComputeOp.ADD, (FormulaTerm.SOURCE, FormulaTerm.DESTINATION), None, None, (), None)}
SP_EFFECTS = {'BSR': ((SpEffectAction.DECREMENT, 4, None),),
 'ILLEGAL': ((SpEffectAction.DECREMENT, 2, None),),
 'JSR': ((SpEffectAction.DECREMENT, 4, None),),
 'LINK': ((SpEffectAction.DECREMENT, 4, None), (SpEffectAction.SAVE_TO_REG, None, 'An'), (SpEffectAction.ADJUST, None, 'd'),),
 'PEA': ((SpEffectAction.DECREMENT, 4, None),),
 'RTD': ((SpEffectAction.INCREMENT, 4, None), (SpEffectAction.ADJUST, None, 'd'),),
 'RTR': ((SpEffectAction.INCREMENT, 2, None), (SpEffectAction.INCREMENT, 4, None),),
 'RTS': ((SpEffectAction.INCREMENT, 4, None),),
 'UNLK': ((SpEffectAction.LOAD_FROM_REG, None, 'An'), (SpEffectAction.INCREMENT, 4, None),)}
EA_MODE_TABLES = {'ABCD': ((), (), ()),
 'ADD': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'ADDA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'ADDI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ADDQ': ((), ('dn', 'an', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ADDX': ((), (), ()),
 'AND': (('dn',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'ANDI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ANDI to CCR': ((), (), ()),
 'ANDI to SR': ((), (), ()),
 'ASL, ASR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'BCHG': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BCLR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BFCHG': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFCLR': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFEXTS': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFEXTU': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFFFO': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFINS': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFSET': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFTST': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BKPT': ((), (), ()),
 'BRA': ((), (), ()),
 'BSET': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BSR': ((), (), ()),
 'BTST': ((),
          ('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          ()),
 'Bcc': ((), (), ()),
 'CALLM': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CAS CAS2': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'CHK': ((),
         (),
         ('dn',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm')),
 'CHK2': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CINV': ((), (), ()),
 'CLR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'CMP': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         (),
         ()),
 'CMP2': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CMPA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'CMPI': ((),
          ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex'),
          ()),
 'CMPM': ((), (), ()),
 'CPUSH': ((), (), ()),
 'DBcc': ((), (), ()),
 'DIVS, DIVSL': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'DIVU, DIVUL': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'EOR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'EORI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'EORI to CCR': ((), (), ()),
 'EORI to SR': ((), (), ()),
 'EXG': ((), (), ()),
 'EXT, EXTB': ((), (), ()),
 'FRESTORE': ((), (), ('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'FSAVE': ((), (), ('ind', 'predec', 'disp', 'index', 'absw', 'absl')),
 'ILLEGAL': ((), (), ()),
 'JMP': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'JSR': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'LEA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'LINK': ((), (), ()),
 'LSL, LSR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'MOVE': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
          ()),
 'MOVE USP': ((), (), ()),
 'MOVE from CCR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'MOVE from SR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'MOVE to CCR': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'MOVE to SR': (('dn',
                 'ind',
                 'postinc',
                 'predec',
                 'disp',
                 'index',
                 'absw',
                 'absl',
                 'pcdisp',
                 'pcindex',
                 'imm'),
                (),
                ()),
 'MOVE16': ((), (), ()),
 'MOVEA': (('dn',
            'an',
            'ind',
            'postinc',
            'predec',
            'disp',
            'index',
            'absw',
            'absl',
            'pcdisp',
            'pcindex',
            'imm'),
           (),
           ()),
 'MOVEC': ((), (), ()),
 'MOVEM': ((),
           (),
           ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'MOVEP': ((), (), ()),
 'MOVEQ': ((), (), ()),
 'MOVES': (('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), (), ()),
 'MULS': (('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'MULU': (('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'NBCD': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NEG': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NEGX': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NOP': ((), (), ()),
 'NOT': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'OR': (('dn',
         'ind',
         'postinc',
         'predec',
         'disp',
         'index',
         'absw',
         'absl',
         'pcdisp',
         'pcindex',
         'imm'),
        ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
        ()),
 'ORI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ORI to CCR': ((), (), ()),
 'ORI to SR': ((), (), ()),
 'PACK': ((), (), ()),
 'PBcc': ((), (), ()),
 'PDBcc': ((), (), ()),
 'PEA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'PFLUSH': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PFLUSH PFLUSHA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PFLUSHR': ((),
             (),
             ('ind',
              'postinc',
              'predec',
              'disp',
              'index',
              'absw',
              'absl',
              'pcdisp',
              'pcindex',
              'imm')),
 'PLOAD': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PMOVE': ((),
           (),
           ('dn',
            'an',
            'ind',
            'postinc',
            'predec',
            'disp',
            'index',
            'absw',
            'absl',
            'pcdisp',
            'pcindex',
            'imm')),
 'PRESTORE': (('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex'), (), ()),
 'PSAVE': ((), ('ind', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'PScc': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'PTEST': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PTRAPcc': ((), (), ()),
 'PVALID': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'RESET': ((), (), ()),
 'ROL, ROR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index')),
 'ROXL, ROXR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'RTD': ((), (), ()),
 'RTE': ((), (), ()),
 'RTM': ((), (), ()),
 'RTR': ((), (), ()),
 'RTS': ((), (), ()),
 'SBCD': ((), (), ()),
 'STOP': ((), (), ()),
 'SUB': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'SUBA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'SUBI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'SUBQ': ((), ('dn', 'an', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'SUBX': ((), (), ()),
 'SWAP': ((), (), ()),
 'Scc': ((), (), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'TAS': ((), (), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'TRAP': ((), (), ()),
 'TRAPV': ((), (), ()),
 'TRAPcc': ((), (), ()),
 'TST': ((),
         ('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ()),
 'UNLK': ((), (), ()),
 'UNPK': ((), (), ()),
 'cpBcc': ((), (), ()),
 'cpDBcc': ((), (), ()),
 'cpGEN': ((), (), ()),
 'cpRESTORE': ((),
               (),
               ('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex', 'imm')),
 'cpSAVE': ((), (), ('ind', 'predec', 'disp', 'index', 'absw', 'absl')),
 'cpScc': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'cpTRAPcc': ((), (), ())}
AN_SIZES = {'ABCD': (),
 'ADD': (),
 'ADDA': (),
 'ADDI': (),
 'ADDQ': ('w', 'l'),
 'ADDX': (),
 'AND': (),
 'ANDI': (),
 'ANDI to CCR': (),
 'ANDI to SR': (),
 'ASL, ASR': (),
 'BCHG': (),
 'BCLR': (),
 'BFCHG': (),
 'BFCLR': (),
 'BFEXTS': (),
 'BFEXTU': (),
 'BFFFO': (),
 'BFINS': (),
 'BFSET': (),
 'BFTST': (),
 'BKPT': (),
 'BRA': (),
 'BSET': (),
 'BSR': (),
 'BTST': (),
 'Bcc': (),
 'CALLM': (),
 'CAS CAS2': (),
 'CHK': (),
 'CHK2': (),
 'CINV': (),
 'CLR': (),
 'CMP': (),
 'CMP2': (),
 'CMPA': (),
 'CMPI': (),
 'CMPM': (),
 'CPUSH': (),
 'DBcc': (),
 'DIVS, DIVSL': (),
 'DIVU, DIVUL': (),
 'EOR': (),
 'EORI': (),
 'EORI to CCR': (),
 'EORI to SR': (),
 'EXG': (),
 'EXT, EXTB': (),
 'FRESTORE': (),
 'FSAVE': (),
 'ILLEGAL': (),
 'JMP': (),
 'JSR': (),
 'LEA': (),
 'LINK': (),
 'LSL, LSR': (),
 'MOVE': (),
 'MOVE USP': (),
 'MOVE from CCR': (),
 'MOVE from SR': (),
 'MOVE to CCR': (),
 'MOVE to SR': (),
 'MOVE16': (),
 'MOVEA': (),
 'MOVEC': (),
 'MOVEM': (),
 'MOVEP': (),
 'MOVEQ': (),
 'MOVES': (),
 'MULS': (),
 'MULU': (),
 'NBCD': (),
 'NEG': (),
 'NEGX': (),
 'NOP': (),
 'NOT': (),
 'OR': (),
 'ORI': (),
 'ORI to CCR': (),
 'ORI to SR': (),
 'PACK': (),
 'PBcc': (),
 'PDBcc': (),
 'PEA': (),
 'PFLUSH': (),
 'PFLUSH PFLUSHA': (),
 'PFLUSHR': (),
 'PLOAD': (),
 'PMOVE': (),
 'PRESTORE': (),
 'PSAVE': (),
 'PScc': (),
 'PTEST': (),
 'PTRAPcc': (),
 'PVALID': (),
 'RESET': (),
 'ROL, ROR': (),
 'ROXL, ROXR': (),
 'RTD': (),
 'RTE': (),
 'RTM': (),
 'RTR': (),
 'RTS': (),
 'SBCD': (),
 'STOP': (),
 'SUB': (),
 'SUBA': (),
 'SUBI': (),
 'SUBQ': ('w', 'l'),
 'SUBX': (),
 'SWAP': (),
 'Scc': (),
 'TAS': (),
 'TRAP': (),
 'TRAPV': (),
 'TRAPcc': (),
 'TST': (),
 'UNLK': (),
 'UNPK': (),
 'cpBcc': (),
 'cpDBcc': (),
 'cpGEN': (),
 'cpRESTORE': (),
 'cpSAVE': (),
 'cpScc': (),
 'cpTRAPcc': ()}
PROCESSOR_MINS = {'abcd': Processor.M68000,
 'add': Processor.M68000,
 'adda': Processor.M68000,
 'addi': Processor.M68000,
 'addq': Processor.M68000,
 'addx': Processor.M68000,
 'and': Processor.M68000,
 'andi': Processor.M68000,
 'asl': Processor.M68000,
 'asr': Processor.M68000,
 'bcc': Processor.M68000,
 'bchg': Processor.M68000,
 'bclr': Processor.M68000,
 'bfchg': Processor.M68020,
 'bfclr': Processor.M68020,
 'bfexts': Processor.M68020,
 'bfextu': Processor.M68020,
 'bfffo': Processor.M68020,
 'bfins': Processor.M68020,
 'bfset': Processor.M68020,
 'bftst': Processor.M68020,
 'bkpt': Processor.M68000,
 'bra': Processor.M68000,
 'bset': Processor.M68000,
 'bsr': Processor.M68000,
 'btst': Processor.M68000,
 'callm': Processor.M68020,
 'cas': Processor.M68020,
 'cas2': Processor.M68020,
 'ccr': Processor.M68000,
 'chk': Processor.M68000,
 'chk2': Processor.M68020,
 'cinv': Processor.M68040,
 'clr': Processor.M68000,
 'cmp': Processor.M68000,
 'cmp2': Processor.M68020,
 'cmpa': Processor.M68000,
 'cmpi': Processor.M68000,
 'cmpm': Processor.M68000,
 'cpbcc': Processor.M68020,
 'cpdbcc': Processor.M68020,
 'cpgen': Processor.M68020,
 'cprestore': Processor.M68020,
 'cpsave': Processor.M68020,
 'cpscc': Processor.M68020,
 'cptrapcc': Processor.M68020,
 'cpush': Processor.M68040,
 'dbcc': Processor.M68000,
 'divs': Processor.M68000,
 'divsl': Processor.M68000,
 'divu': Processor.M68000,
 'divul': Processor.M68000,
 'eor': Processor.M68000,
 'eori': Processor.M68000,
 'exg': Processor.M68000,
 'ext': Processor.M68000,
 'extb': Processor.M68000,
 'frestore': Processor.M68020,
 'from': Processor.M68000,
 'fsave': Processor.M68020,
 'illegal': Processor.M68000,
 'jmp': Processor.M68000,
 'jsr': Processor.M68000,
 'lea': Processor.M68000,
 'link': Processor.M68000,
 'lsl': Processor.M68000,
 'lsr': Processor.M68000,
 'move': Processor.M68000,
 'move16': Processor.M68040,
 'movea': Processor.M68000,
 'movec': Processor.M68010,
 'movem': Processor.M68000,
 'movep': Processor.M68000,
 'moveq': Processor.M68000,
 'moves': Processor.M68010,
 'muls': Processor.M68000,
 'mulu': Processor.M68000,
 'nbcd': Processor.M68000,
 'neg': Processor.M68000,
 'negx': Processor.M68000,
 'nop': Processor.M68000,
 'not': Processor.M68000,
 'or': Processor.M68000,
 'ori': Processor.M68000,
 'pack': Processor.M68020,
 'pbcc': Processor.M68020,
 'pdbcc': Processor.M68020,
 'pea': Processor.M68000,
 'pflush': Processor.M68020,
 'pflusha': Processor.M68020,
 'pflushr': Processor.M68020,
 'pload': Processor.M68020,
 'pmove': Processor.M68030,
 'prestore': Processor.M68020,
 'psave': Processor.M68020,
 'pscc': Processor.M68020,
 'ptest': Processor.M68030,
 'ptrapcc': Processor.M68000,
 'pvalid': Processor.M68020,
 'reset': Processor.M68000,
 'rol': Processor.M68000,
 'ror': Processor.M68000,
 'roxl': Processor.M68000,
 'roxr': Processor.M68000,
 'rtd': Processor.M68010,
 'rte': Processor.M68000,
 'rtm': Processor.M68020,
 'rtr': Processor.M68000,
 'rts': Processor.M68000,
 'sbcd': Processor.M68000,
 'scc': Processor.M68000,
 'sr': Processor.M68000,
 'stop': Processor.M68000,
 'sub': Processor.M68000,
 'suba': Processor.M68000,
 'subi': Processor.M68000,
 'subq': Processor.M68000,
 'subx': Processor.M68000,
 'swap': Processor.M68000,
 'tas': Processor.M68000,
 'to': Processor.M68000,
 'trap': Processor.M68000,
 'trapcc': Processor.M68020,
 'trapv': Processor.M68000,
 'tst': Processor.M68000,
 'unlk': Processor.M68000,
 'unpk': Processor.M68020,
 'usp': Processor.M68000}
PROCESSOR_020_VARIANTS = {'DIVS, DIVSL': frozenset({'DIVSL'}),
 'DIVU, DIVUL': frozenset({'DIVUL'}),
 'EXT, EXTB': frozenset({'EXTB'})}
LOOKUP_UPPER = {'ABCD': 'ABCD',
 'ADD': 'ADD',
 'ADDA': 'ADDA',
 'ADDI': 'ADDI',
 'ADDQ': 'ADDQ',
 'ADDX': 'ADDX',
 'AND': 'AND',
 'ANDI': 'ANDI',
 'ANDI TO CCR': 'ANDI to CCR',
 'ANDI TO SR': 'ANDI to SR',
 'ASL': 'ASL, ASR',
 'ASL, ASR': 'ASL, ASR',
 'ASR': 'ASL, ASR',
 'BCC': 'Bcc',
 'BCHG': 'BCHG',
 'BCLR': 'BCLR',
 'BFCHG': 'BFCHG',
 'BFCLR': 'BFCLR',
 'BFEXTS': 'BFEXTS',
 'BFEXTU': 'BFEXTU',
 'BFFFO': 'BFFFO',
 'BFINS': 'BFINS',
 'BFSET': 'BFSET',
 'BFTST': 'BFTST',
 'BKPT': 'BKPT',
 'BRA': 'BRA',
 'BSET': 'BSET',
 'BSR': 'BSR',
 'BTST': 'BTST',
 'CALLM': 'CALLM',
 'CAS CAS2': 'CAS CAS2',
 'CHK': 'CHK',
 'CHK2': 'CHK2',
 'CINV': 'CINV',
 'CLR': 'CLR',
 'CMP': 'CMP',
 'CMP2': 'CMP2',
 'CMPA': 'CMPA',
 'CMPI': 'CMPI',
 'CMPM': 'CMPM',
 'CPBCC': 'cpBcc',
 'CPDBCC': 'cpDBcc',
 'CPGEN': 'cpGEN',
 'CPRESTORE': 'cpRESTORE',
 'CPSAVE': 'cpSAVE',
 'CPSCC': 'cpScc',
 'CPTRAPCC': 'cpTRAPcc',
 'CPUSH': 'CPUSH',
 'DBCC': 'DBcc',
 'DIVS': 'DIVS, DIVSL',
 'DIVS, DIVSL': 'DIVS, DIVSL',
 'DIVSL': 'DIVS, DIVSL',
 'DIVU': 'DIVU, DIVUL',
 'DIVU, DIVUL': 'DIVU, DIVUL',
 'DIVUL': 'DIVU, DIVUL',
 'EOR': 'EOR',
 'EORI': 'EORI',
 'EORI TO CCR': 'EORI to CCR',
 'EORI TO SR': 'EORI to SR',
 'EXG': 'EXG',
 'EXT': 'EXT, EXTB',
 'EXT, EXTB': 'EXT, EXTB',
 'EXTB': 'EXT, EXTB',
 'FRESTORE': 'FRESTORE',
 'FSAVE': 'FSAVE',
 'ILLEGAL': 'ILLEGAL',
 'JMP': 'JMP',
 'JSR': 'JSR',
 'LEA': 'LEA',
 'LINK': 'LINK',
 'LSL': 'LSL, LSR',
 'LSL, LSR': 'LSL, LSR',
 'LSR': 'LSL, LSR',
 'MOVE': 'MOVE',
 'MOVE FROM CCR': 'MOVE from CCR',
 'MOVE FROM SR': 'MOVE from SR',
 'MOVE TO CCR': 'MOVE to CCR',
 'MOVE TO SR': 'MOVE to SR',
 'MOVE USP': 'MOVE USP',
 'MOVE16': 'MOVE16',
 'MOVEA': 'MOVEA',
 'MOVEC': 'MOVEC',
 'MOVEM': 'MOVEM',
 'MOVEP': 'MOVEP',
 'MOVEQ': 'MOVEQ',
 'MOVES': 'MOVES',
 'MULS': 'MULS',
 'MULU': 'MULU',
 'NBCD': 'NBCD',
 'NEG': 'NEG',
 'NEGX': 'NEGX',
 'NOP': 'NOP',
 'NOT': 'NOT',
 'OR': 'OR',
 'ORI': 'ORI',
 'ORI TO CCR': 'ORI to CCR',
 'ORI TO SR': 'ORI to SR',
 'PACK': 'PACK',
 'PBCC': 'PBcc',
 'PDBCC': 'PDBcc',
 'PEA': 'PEA',
 'PFLUSH': 'PFLUSH',
 'PFLUSH PFLUSHA': 'PFLUSH PFLUSHA',
 'PFLUSHA': 'PFLUSH PFLUSHA',
 'PFLUSHR': 'PFLUSHR',
 'PLOAD': 'PLOAD',
 'PMOVE': 'PMOVE',
 'PRESTORE': 'PRESTORE',
 'PSAVE': 'PSAVE',
 'PSCC': 'PScc',
 'PTEST': 'PTEST',
 'PTRAPCC': 'PTRAPcc',
 'PVALID': 'PVALID',
 'RESET': 'RESET',
 'ROL': 'ROL, ROR',
 'ROL, ROR': 'ROL, ROR',
 'ROR': 'ROL, ROR',
 'ROXL': 'ROXL, ROXR',
 'ROXL, ROXR': 'ROXL, ROXR',
 'ROXR': 'ROXL, ROXR',
 'RTD': 'RTD',
 'RTE': 'RTE',
 'RTM': 'RTM',
 'RTR': 'RTR',
 'RTS': 'RTS',
 'SBCD': 'SBCD',
 'SCC': 'Scc',
 'STOP': 'STOP',
 'SUB': 'SUB',
 'SUBA': 'SUBA',
 'SUBI': 'SUBI',
 'SUBQ': 'SUBQ',
 'SUBX': 'SUBX',
 'SWAP': 'SWAP',
 'TAS': 'TAS',
 'TRAP': 'TRAP',
 'TRAPCC': 'TRAPcc',
 'TRAPV': 'TRAPV',
 'TST': 'TST',
 'UNLK': 'UNLK',
 'UNPK': 'UNPK'}
LOOKUP_CANONICAL = {'ABCD': 'ABCD',
 'ADD': 'ADD',
 'ADDA': 'ADDA',
 'ADDI': 'ADDI',
 'ADDQ': 'ADDQ',
 'ADDX': 'ADDX',
 'AND': 'AND',
 'ANDI': 'ANDI',
 'ANDI TO CCR': 'ANDI to CCR',
 'ANDI TO SR': 'ANDI to SR',
 'ASL': 'ASL, ASR',
 'ASL, ASR': 'ASL, ASR',
 'ASR': 'ASL, ASR',
 'BCC': 'Bcc',
 'BCHG': 'BCHG',
 'BCLR': 'BCLR',
 'BCS': 'Bcc',
 'BEQ': 'Bcc',
 'BF': 'Bcc',
 'BFCHG': 'BFCHG',
 'BFCLR': 'BFCLR',
 'BFEXTS': 'BFEXTS',
 'BFEXTU': 'BFEXTU',
 'BFFFO': 'BFFFO',
 'BFINS': 'BFINS',
 'BFSET': 'BFSET',
 'BFTST': 'BFTST',
 'BGE': 'Bcc',
 'BGT': 'Bcc',
 'BHI': 'Bcc',
 'BKPT': 'BKPT',
 'BLE': 'Bcc',
 'BLO': 'Bcc',
 'BLS': 'Bcc',
 'BLT': 'Bcc',
 'BMI': 'Bcc',
 'BNE': 'Bcc',
 'BPL': 'Bcc',
 'BRA': 'Bcc',
 'BSET': 'BSET',
 'BSR': 'BSR',
 'BT': 'Bcc',
 'BTST': 'BTST',
 'BVC': 'Bcc',
 'BVS': 'Bcc',
 'CALLM': 'CALLM',
 'CAS CAS2': 'CAS CAS2',
 'CHK': 'CHK',
 'CHK2': 'CHK2',
 'CINV': 'CINV',
 'CLR': 'CLR',
 'CMP': 'CMP',
 'CMP2': 'CMP2',
 'CMPA': 'CMPA',
 'CMPI': 'CMPI',
 'CMPM': 'CMPM',
 'CPBCC': 'cpBcc',
 'CPBCS': 'cpBcc',
 'CPBEQ': 'cpBcc',
 'CPBF': 'cpBcc',
 'CPBGE': 'cpBcc',
 'CPBGT': 'cpBcc',
 'CPBHI': 'cpBcc',
 'CPBLE': 'cpBcc',
 'CPBLO': 'cpBcc',
 'CPBLS': 'cpBcc',
 'CPBLT': 'cpBcc',
 'CPBMI': 'cpBcc',
 'CPBNE': 'cpBcc',
 'CPBPL': 'cpBcc',
 'CPBRA': 'cpBcc',
 'CPBT': 'cpBcc',
 'CPBVC': 'cpBcc',
 'CPBVS': 'cpBcc',
 'CPDBCC': 'cpDBcc',
 'CPDBCS': 'cpDBcc',
 'CPDBEQ': 'cpDBcc',
 'CPDBF': 'cpDBcc',
 'CPDBGE': 'cpDBcc',
 'CPDBGT': 'cpDBcc',
 'CPDBHI': 'cpDBcc',
 'CPDBLE': 'cpDBcc',
 'CPDBLO': 'cpDBcc',
 'CPDBLS': 'cpDBcc',
 'CPDBLT': 'cpDBcc',
 'CPDBMI': 'cpDBcc',
 'CPDBNE': 'cpDBcc',
 'CPDBPL': 'cpDBcc',
 'CPDBRA': 'cpDBcc',
 'CPDBT': 'cpDBcc',
 'CPDBVC': 'cpDBcc',
 'CPDBVS': 'cpDBcc',
 'CPGEN': 'cpGEN',
 'CPRESTORE': 'cpRESTORE',
 'CPSAVE': 'cpSAVE',
 'CPSCC': 'cpScc',
 'CPSCS': 'cpScc',
 'CPSEQ': 'cpScc',
 'CPSF': 'cpScc',
 'CPSGE': 'cpScc',
 'CPSGT': 'cpScc',
 'CPSHI': 'cpScc',
 'CPSLE': 'cpScc',
 'CPSLO': 'cpScc',
 'CPSLS': 'cpScc',
 'CPSLT': 'cpScc',
 'CPSMI': 'cpScc',
 'CPSNE': 'cpScc',
 'CPSPL': 'cpScc',
 'CPSRA': 'cpScc',
 'CPST': 'cpScc',
 'CPSVC': 'cpScc',
 'CPSVS': 'cpScc',
 'CPTRAPCC': 'cpTRAPcc',
 'CPTRAPCS': 'cpTRAPcc',
 'CPTRAPEQ': 'cpTRAPcc',
 'CPTRAPF': 'cpTRAPcc',
 'CPTRAPGE': 'cpTRAPcc',
 'CPTRAPGT': 'cpTRAPcc',
 'CPTRAPHI': 'cpTRAPcc',
 'CPTRAPLE': 'cpTRAPcc',
 'CPTRAPLO': 'cpTRAPcc',
 'CPTRAPLS': 'cpTRAPcc',
 'CPTRAPLT': 'cpTRAPcc',
 'CPTRAPMI': 'cpTRAPcc',
 'CPTRAPNE': 'cpTRAPcc',
 'CPTRAPPL': 'cpTRAPcc',
 'CPTRAPRA': 'cpTRAPcc',
 'CPTRAPT': 'cpTRAPcc',
 'CPTRAPVC': 'cpTRAPcc',
 'CPTRAPVS': 'cpTRAPcc',
 'CPUSH': 'CPUSH',
 'DBCC': 'DBcc',
 'DBCS': 'DBcc',
 'DBEQ': 'DBcc',
 'DBF': 'DBcc',
 'DBGE': 'DBcc',
 'DBGT': 'DBcc',
 'DBHI': 'DBcc',
 'DBLE': 'DBcc',
 'DBLO': 'DBcc',
 'DBLS': 'DBcc',
 'DBLT': 'DBcc',
 'DBMI': 'DBcc',
 'DBNE': 'DBcc',
 'DBPL': 'DBcc',
 'DBRA': 'DBcc',
 'DBT': 'DBcc',
 'DBVC': 'DBcc',
 'DBVS': 'DBcc',
 'DIVS': 'DIVS, DIVSL',
 'DIVS, DIVSL': 'DIVS, DIVSL',
 'DIVSL': 'DIVS, DIVSL',
 'DIVU': 'DIVU, DIVUL',
 'DIVU, DIVUL': 'DIVU, DIVUL',
 'DIVUL': 'DIVU, DIVUL',
 'EOR': 'EOR',
 'EORI': 'EORI',
 'EORI TO CCR': 'EORI to CCR',
 'EORI TO SR': 'EORI to SR',
 'EXG': 'EXG',
 'EXT': 'EXT, EXTB',
 'EXT, EXTB': 'EXT, EXTB',
 'EXTB': 'EXT, EXTB',
 'FRESTORE': 'FRESTORE',
 'FSAVE': 'FSAVE',
 'ILLEGAL': 'ILLEGAL',
 'JMP': 'JMP',
 'JSR': 'JSR',
 'LEA': 'LEA',
 'LINK': 'LINK',
 'LSL': 'LSL, LSR',
 'LSL, LSR': 'LSL, LSR',
 'LSR': 'LSL, LSR',
 'MOVE': 'MOVE',
 'MOVE FROM CCR': 'MOVE from CCR',
 'MOVE FROM SR': 'MOVE from SR',
 'MOVE TO CCR': 'MOVE to CCR',
 'MOVE TO SR': 'MOVE to SR',
 'MOVE USP': 'MOVE USP',
 'MOVE16': 'MOVE16',
 'MOVEA': 'MOVEA',
 'MOVEC': 'MOVEC',
 'MOVEM': 'MOVEM',
 'MOVEP': 'MOVEP',
 'MOVEQ': 'MOVEQ',
 'MOVES': 'MOVES',
 'MULS': 'MULS',
 'MULU': 'MULU',
 'NBCD': 'NBCD',
 'NEG': 'NEG',
 'NEGX': 'NEGX',
 'NOP': 'NOP',
 'NOT': 'NOT',
 'OR': 'OR',
 'ORI': 'ORI',
 'ORI TO CCR': 'ORI to CCR',
 'ORI TO SR': 'ORI to SR',
 'PACK': 'PACK',
 'PBAC': 'PBcc',
 'PBAS': 'PBcc',
 'PBBC': 'PBcc',
 'PBBS': 'PBcc',
 'PBCC': 'PBcc',
 'PBCS': 'PBcc',
 'PBGC': 'PBcc',
 'PBGS': 'PBcc',
 'PBIC': 'PBcc',
 'PBIS': 'PBcc',
 'PBLC': 'PBcc',
 'PBLS': 'PBcc',
 'PBSC': 'PBcc',
 'PBSS': 'PBcc',
 'PBWC': 'PBcc',
 'PBWS': 'PBcc',
 'PDBAC': 'PDBcc',
 'PDBAS': 'PDBcc',
 'PDBBC': 'PDBcc',
 'PDBBS': 'PDBcc',
 'PDBCC': 'PDBcc',
 'PDBCS': 'PDBcc',
 'PDBGC': 'PDBcc',
 'PDBGS': 'PDBcc',
 'PDBIC': 'PDBcc',
 'PDBIS': 'PDBcc',
 'PDBLC': 'PDBcc',
 'PDBLS': 'PDBcc',
 'PDBSC': 'PDBcc',
 'PDBSS': 'PDBcc',
 'PDBWC': 'PDBcc',
 'PDBWS': 'PDBcc',
 'PEA': 'PEA',
 'PFLUSH': 'PFLUSH',
 'PFLUSH PFLUSHA': 'PFLUSH PFLUSHA',
 'PFLUSHA': 'PFLUSH PFLUSHA',
 'PFLUSHR': 'PFLUSHR',
 'PLOAD': 'PLOAD',
 'PMOVE': 'PMOVE',
 'PRESTORE': 'PRESTORE',
 'PSAC': 'PScc',
 'PSAS': 'PScc',
 'PSAVE': 'PSAVE',
 'PSBC': 'PScc',
 'PSBS': 'PScc',
 'PSCC': 'PScc',
 'PSCS': 'PScc',
 'PSGC': 'PScc',
 'PSGS': 'PScc',
 'PSIC': 'PScc',
 'PSIS': 'PScc',
 'PSLC': 'PScc',
 'PSLS': 'PScc',
 'PSSC': 'PScc',
 'PSSS': 'PScc',
 'PSWC': 'PScc',
 'PSWS': 'PScc',
 'PTEST': 'PTEST',
 'PTRAPAC': 'PTRAPcc',
 'PTRAPAS': 'PTRAPcc',
 'PTRAPBC': 'PTRAPcc',
 'PTRAPBS': 'PTRAPcc',
 'PTRAPCC': 'PTRAPcc',
 'PTRAPCS': 'PTRAPcc',
 'PTRAPGC': 'PTRAPcc',
 'PTRAPGS': 'PTRAPcc',
 'PTRAPIC': 'PTRAPcc',
 'PTRAPIS': 'PTRAPcc',
 'PTRAPLC': 'PTRAPcc',
 'PTRAPLS': 'PTRAPcc',
 'PTRAPSC': 'PTRAPcc',
 'PTRAPSS': 'PTRAPcc',
 'PTRAPWC': 'PTRAPcc',
 'PTRAPWS': 'PTRAPcc',
 'PVALID': 'PVALID',
 'RESET': 'RESET',
 'ROL': 'ROL, ROR',
 'ROL, ROR': 'ROL, ROR',
 'ROR': 'ROL, ROR',
 'ROXL': 'ROXL, ROXR',
 'ROXL, ROXR': 'ROXL, ROXR',
 'ROXR': 'ROXL, ROXR',
 'RTD': 'RTD',
 'RTE': 'RTE',
 'RTM': 'RTM',
 'RTR': 'RTR',
 'RTS': 'RTS',
 'SBCD': 'SBCD',
 'SCC': 'Scc',
 'SCS': 'Scc',
 'SEQ': 'Scc',
 'SF': 'Scc',
 'SGE': 'Scc',
 'SGT': 'Scc',
 'SHI': 'Scc',
 'SLE': 'Scc',
 'SLO': 'Scc',
 'SLS': 'Scc',
 'SLT': 'Scc',
 'SMI': 'Scc',
 'SNE': 'Scc',
 'SPL': 'Scc',
 'SRA': 'Scc',
 'ST': 'Scc',
 'STOP': 'STOP',
 'SUB': 'SUB',
 'SUBA': 'SUBA',
 'SUBI': 'SUBI',
 'SUBQ': 'SUBQ',
 'SUBX': 'SUBX',
 'SVC': 'Scc',
 'SVS': 'Scc',
 'SWAP': 'SWAP',
 'TAS': 'TAS',
 'TRAP': 'TRAP',
 'TRAPCC': 'TRAPcc',
 'TRAPCS': 'TRAPcc',
 'TRAPEQ': 'TRAPcc',
 'TRAPF': 'TRAPcc',
 'TRAPGE': 'TRAPcc',
 'TRAPGT': 'TRAPcc',
 'TRAPHI': 'TRAPcc',
 'TRAPLE': 'TRAPcc',
 'TRAPLO': 'TRAPcc',
 'TRAPLS': 'TRAPcc',
 'TRAPLT': 'TRAPcc',
 'TRAPMI': 'TRAPcc',
 'TRAPNE': 'TRAPcc',
 'TRAPPL': 'TRAPcc',
 'TRAPRA': 'TRAPcc',
 'TRAPT': 'TRAPcc',
 'TRAPV': 'TRAPV',
 'TRAPVC': 'TRAPcc',
 'TRAPVS': 'TRAPcc',
 'TST': 'TST',
 'UNLK': 'UNLK',
 'UNPK': 'UNPK'}
LOOKUP_NUMERIC_CC_PREFIXES = {'PB': 'PBcc', 'PDB': 'PDBcc', 'PS': 'PScc', 'PTRAP': 'PTRAPcc'}
LOOKUP_CC_FAMILIES = {'b': ('Bcc',
       ('cc',
        'cs',
        'eq',
        'f',
        'ge',
        'gt',
        'hi',
        'le',
        'lo',
        'ls',
        'lt',
        'mi',
        'ne',
        'pl',
        'ra',
        't',
        'vc',
        'vs'),
       False),
 'cpb': ('cpBcc',
         ('cc',
          'cs',
          'eq',
          'f',
          'ge',
          'gt',
          'hi',
          'le',
          'lo',
          'ls',
          'lt',
          'mi',
          'ne',
          'pl',
          'ra',
          't',
          'vc',
          'vs'),
         False),
 'cpdb': ('cpDBcc',
          ('cc',
           'cs',
           'eq',
           'f',
           'ge',
           'gt',
           'hi',
           'le',
           'lo',
           'ls',
           'lt',
           'mi',
           'ne',
           'pl',
           'ra',
           't',
           'vc',
           'vs'),
          False),
 'cps': ('cpScc',
         ('cc',
          'cs',
          'eq',
          'f',
          'ge',
          'gt',
          'hi',
          'le',
          'lo',
          'ls',
          'lt',
          'mi',
          'ne',
          'pl',
          'ra',
          't',
          'vc',
          'vs'),
         False),
 'cptrap': ('cpTRAPcc',
            ('cc',
             'cs',
             'eq',
             'f',
             'ge',
             'gt',
             'hi',
             'le',
             'lo',
             'ls',
             'lt',
             'mi',
             'ne',
             'pl',
             'ra',
             't',
             'vc',
             'vs'),
            False),
 'db': ('DBcc',
        ('cc',
         'cs',
         'eq',
         'f',
         'ge',
         'gt',
         'hi',
         'le',
         'lo',
         'ls',
         'lt',
         'mi',
         'ne',
         'pl',
         'ra',
         't',
         'vc',
         'vs'),
        False),
 'pb': ('PBcc',
        ('bs',
         'bc',
         'ls',
         'lc',
         'ss',
         'sc',
         'as',
         'ac',
         'ws',
         'wc',
         'is',
         'ic',
         'gs',
         'gc',
         'cs',
         'cc'),
        True),
 'pdb': ('PDBcc',
         ('bs',
          'bc',
          'ls',
          'lc',
          'ss',
          'sc',
          'as',
          'ac',
          'ws',
          'wc',
          'is',
          'ic',
          'gs',
          'gc',
          'cs',
          'cc'),
         True),
 'ps': ('PScc',
        ('bs',
         'bc',
         'ls',
         'lc',
         'ss',
         'sc',
         'as',
         'ac',
         'ws',
         'wc',
         'is',
         'ic',
         'gs',
         'gc',
         'cs',
         'cc'),
        True),
 'ptrap': ('PTRAPcc',
           ('bs',
            'bc',
            'ls',
            'lc',
            'ss',
            'sc',
            'as',
            'ac',
            'ws',
            'wc',
            'is',
            'ic',
            'gs',
            'gc',
            'cs',
            'cc'),
           True),
 's': ('Scc',
       ('cc',
        'cs',
        'eq',
        'f',
        'ge',
        'gt',
        'hi',
        'le',
        'lo',
        'ls',
        'lt',
        'mi',
        'ne',
        'pl',
        'ra',
        't',
        'vc',
        'vs'),
       False),
 'trap': ('TRAPcc',
          ('cc',
           'cs',
           'eq',
           'f',
           'ge',
           'gt',
           'hi',
           'le',
           'lo',
           'ls',
           'lt',
           'mi',
           'ne',
           'pl',
           'ra',
           't',
           'vc',
           'vs'),
          False)}
LOOKUP_ASM_MNEMONIC_INDEX = {'cptrapcc': 'cpTRAPcc',
 'illegal': 'ILLEGAL',
 'nop': 'NOP',
 'pflusha': 'PFLUSH PFLUSHA',
 'ptrapcc': 'PTRAPcc',
 'reset': 'RESET',
 'rte': 'RTE',
 'rtr': 'RTR',
 'rts': 'RTS',
 'trapcc': 'TRAPcc',
 'trapv': 'TRAPV'}
