"""Generated runtime M68K disassembly knowledge artifact. Do not edit directly."""

from __future__ import annotations

from enum import StrEnum

from typing import TypeAlias

DisasmSizeEncoding: TypeAlias = tuple[int | None, int | None, int | None, int | None]
ShiftFieldInfo: TypeAlias = tuple[tuple[int, int, int], tuple[str | None, ...], int]
RmFieldInfo: TypeAlias = tuple[int, tuple[str | None, ...]]
class OperationType(StrEnum):
    ADD = 'add'
    ADD_DECIMAL = 'add_decimal'
    ADDX = 'addx'
    AND = 'and'
    BIT_TEST = 'bit_test'
    BITFIELD = 'bitfield'
    BOUNDS_CHECK = 'bounds_check'
    CCR_OP = 'ccr_op'
    CLEAR = 'clear'
    COMPARE = 'compare'
    COMPARE_SWAP = 'compare_swap'
    DIVIDE = 'divide'
    MOVE = 'move'
    MULTIPLY = 'multiply'
    NEG = 'neg'
    NEGX = 'negx'
    NOT = 'not'
    OR = 'or'
    ROTATE = 'rotate'
    ROTATE_EXTEND = 'rotate_extend'
    SHIFT = 'shift'
    SIGN_EXTEND = 'sign_extend'
    SR_OP = 'sr_op'
    SUB = 'sub'
    SUB_DECIMAL = 'sub_decimal'
    SUBX = 'subx'
    SWAP = 'swap'
    TEST = 'test'
    XOR = 'xor'
class OperationClass(StrEnum):
    LOAD_EFFECTIVE_ADDRESS = 'load_effective_address'
    MULTI_REGISTER_TRANSFER = 'multi_register_transfer'

MNEMONIC_INDEX = {'abcd': ('ABCD',),
 'add': ('ADD',),
 'adda': ('ADDA',),
 'addi': ('ADDI',),
 'addq': ('ADDQ',),
 'addx': ('ADDX',),
 'and': ('AND',),
 'andi': ('ANDI', 'ANDI to CCR', 'ANDI to SR'),
 'andi to ccr': ('ANDI to CCR',),
 'andi to sr': ('ANDI to SR',),
 'asl': ('ASL, ASR',),
 'asl,': ('ASL, ASR',),
 'asl, asr': ('ASL, ASR',),
 'asr': ('ASL, ASR',),
 'bcc': ('Bcc',),
 'bchg': ('BCHG',),
 'bclr': ('BCLR',),
 'bfchg': ('BFCHG',),
 'bfclr': ('BFCLR',),
 'bfexts': ('BFEXTS',),
 'bfextu': ('BFEXTU',),
 'bfffo': ('BFFFO',),
 'bfins': ('BFINS',),
 'bfset': ('BFSET',),
 'bftst': ('BFTST',),
 'bkpt': ('BKPT',),
 'bra': ('BRA',),
 'bset': ('BSET',),
 'bsr': ('BSR',),
 'btst': ('BTST',),
 'callm': ('CALLM',),
 'cas': ('CAS CAS2',),
 'cas cas2': ('CAS CAS2',),
 'cas2': ('CAS CAS2',),
 'ccr': ('ANDI to CCR', 'EORI to CCR', 'MOVE from CCR', 'MOVE to CCR', 'ORI to CCR'),
 'chk': ('CHK',),
 'chk2': ('CHK2',),
 'cinv': ('CINV',),
 'clr': ('CLR',),
 'cmp': ('CMP',),
 'cmp2': ('CMP2',),
 'cmpa': ('CMPA',),
 'cmpi': ('CMPI',),
 'cmpm': ('CMPM',),
 'cpbcc': ('cpBcc',),
 'cpdbcc': ('cpDBcc',),
 'cpgen': ('cpGEN',),
 'cprestore': ('cpRESTORE',),
 'cpsave': ('cpSAVE',),
 'cpscc': ('cpScc',),
 'cptrapcc': ('cpTRAPcc',),
 'cpush': ('CPUSH',),
 'dbcc': ('DBcc',),
 'divs': ('DIVS, DIVSL',),
 'divs,': ('DIVS, DIVSL',),
 'divs, divsl': ('DIVS, DIVSL',),
 'divsl': ('DIVS, DIVSL',),
 'divu': ('DIVU, DIVUL',),
 'divu,': ('DIVU, DIVUL',),
 'divu, divul': ('DIVU, DIVUL',),
 'divul': ('DIVU, DIVUL',),
 'eor': ('EOR',),
 'eori': ('EORI', 'EORI to CCR', 'EORI to SR'),
 'eori to ccr': ('EORI to CCR',),
 'eori to sr': ('EORI to SR',),
 'exg': ('EXG',),
 'ext': ('EXT, EXTB',),
 'ext,': ('EXT, EXTB',),
 'ext, extb': ('EXT, EXTB',),
 'extb': ('EXT, EXTB',),
 'frestore': ('FRESTORE',),
 'from': ('MOVE from CCR', 'MOVE from SR'),
 'fsave': ('FSAVE',),
 'illegal': ('ILLEGAL',),
 'jmp': ('JMP',),
 'jsr': ('JSR',),
 'lea': ('LEA',),
 'link': ('LINK',),
 'lsl': ('LSL, LSR',),
 'lsl,': ('LSL, LSR',),
 'lsl, lsr': ('LSL, LSR',),
 'lsr': ('LSL, LSR',),
 'move': ('MOVE', 'MOVE from CCR', 'MOVE to CCR', 'MOVE from SR', 'MOVE to SR', 'MOVE USP'),
 'move from ccr': ('MOVE from CCR',),
 'move from sr': ('MOVE from SR',),
 'move to ccr': ('MOVE to CCR',),
 'move to sr': ('MOVE to SR',),
 'move usp': ('MOVE USP',),
 'move16': ('MOVE16',),
 'movea': ('MOVEA',),
 'movec': ('MOVEC',),
 'movem': ('MOVEM',),
 'movep': ('MOVEP',),
 'moveq': ('MOVEQ',),
 'moves': ('MOVES',),
 'muls': ('MULS',),
 'mulu': ('MULU',),
 'nbcd': ('NBCD',),
 'neg': ('NEG',),
 'negx': ('NEGX',),
 'nop': ('NOP',),
 'not': ('NOT',),
 'or': ('OR',),
 'ori': ('ORI', 'ORI to CCR', 'ORI to SR'),
 'ori to ccr': ('ORI to CCR',),
 'ori to sr': ('ORI to SR',),
 'pack': ('PACK',),
 'pbcc': ('PBcc',),
 'pdbcc': ('PDBcc',),
 'pea': ('PEA',),
 'pflush': ('PFLUSH', 'PFLUSH PFLUSHA'),
 'pflush pflusha': ('PFLUSH PFLUSHA',),
 'pflusha': ('PFLUSH PFLUSHA',),
 'pflushr': ('PFLUSHR',),
 'pload': ('PLOAD',),
 'pmove': ('PMOVE',),
 'prestore': ('PRESTORE',),
 'psave': ('PSAVE',),
 'pscc': ('PScc',),
 'ptest': ('PTEST',),
 'ptrapcc': ('PTRAPcc',),
 'pvalid': ('PVALID',),
 'reset': ('RESET',),
 'rol': ('ROL, ROR',),
 'rol,': ('ROL, ROR',),
 'rol, ror': ('ROL, ROR',),
 'ror': ('ROL, ROR',),
 'roxl': ('ROXL, ROXR',),
 'roxl,': ('ROXL, ROXR',),
 'roxl, roxr': ('ROXL, ROXR',),
 'roxr': ('ROXL, ROXR',),
 'rtd': ('RTD',),
 'rte': ('RTE',),
 'rtm': ('RTM',),
 'rtr': ('RTR',),
 'rts': ('RTS',),
 'sbcd': ('SBCD',),
 'scc': ('Scc',),
 'sr': ('MOVE from SR', 'ANDI to SR', 'EORI to SR', 'MOVE to SR', 'ORI to SR'),
 'stop': ('STOP',),
 'sub': ('SUB',),
 'suba': ('SUBA',),
 'subi': ('SUBI',),
 'subq': ('SUBQ',),
 'subx': ('SUBX',),
 'swap': ('SWAP',),
 'tas': ('TAS',),
 'to': ('ANDI to CCR',
        'EORI to CCR',
        'MOVE to CCR',
        'ORI to CCR',
        'ANDI to SR',
        'EORI to SR',
        'MOVE to SR',
        'ORI to SR'),
 'trap': ('TRAP',),
 'trapcc': ('TRAPcc',),
 'trapv': ('TRAPV',),
 'tst': ('TST',),
 'unlk': ('UNLK',),
 'unpk': ('UNPK',),
 'usp': ('MOVE USP',)}
ENCODING_COUNTS = {'ABCD': 1,
 'ADD': 1,
 'ADDA': 1,
 'ADDI': 1,
 'ADDQ': 1,
 'ADDX': 1,
 'AND': 1,
 'ANDI': 1,
 'ANDI to CCR': 1,
 'ANDI to SR': 1,
 'ASL, ASR': 2,
 'BCHG': 3,
 'BCLR': 3,
 'BFCHG': 2,
 'BFCLR': 2,
 'BFEXTS': 2,
 'BFEXTU': 2,
 'BFFFO': 2,
 'BFINS': 2,
 'BFSET': 2,
 'BFTST': 2,
 'BKPT': 1,
 'BRA': 1,
 'BSET': 3,
 'BSR': 1,
 'BTST': 3,
 'Bcc': 1,
 'CALLM': 2,
 'CAS CAS2': 5,
 'CHK': 1,
 'CHK2': 2,
 'CINV': 1,
 'CLR': 1,
 'CMP': 1,
 'CMP2': 2,
 'CMPA': 1,
 'CMPI': 1,
 'CMPM': 1,
 'CPUSH': 1,
 'DBcc': 2,
 'DIVS, DIVSL': 3,
 'DIVU, DIVUL': 3,
 'EOR': 1,
 'EORI': 1,
 'EORI to CCR': 1,
 'EORI to SR': 1,
 'EXG': 1,
 'EXT, EXTB': 1,
 'FRESTORE': 1,
 'FSAVE': 1,
 'ILLEGAL': 1,
 'JMP': 1,
 'JSR': 1,
 'LEA': 1,
 'LINK': 5,
 'LSL, LSR': 2,
 'MOVE': 1,
 'MOVE USP': 1,
 'MOVE from CCR': 1,
 'MOVE from SR': 1,
 'MOVE to CCR': 1,
 'MOVE to SR': 1,
 'MOVE16': 5,
 'MOVEA': 1,
 'MOVEC': 2,
 'MOVEM': 1,
 'MOVEP': 2,
 'MOVEQ': 1,
 'MOVES': 2,
 'MULS': 3,
 'MULU': 3,
 'NBCD': 1,
 'NEG': 1,
 'NEGX': 1,
 'NOP': 1,
 'NOT': 1,
 'OR': 1,
 'ORI': 1,
 'ORI to CCR': 1,
 'ORI to SR': 1,
 'PACK': 1,
 'PBcc': 1,
 'PDBcc': 3,
 'PEA': 1,
 'PFLUSH': 4,
 'PFLUSH PFLUSHA': 2,
 'PFLUSHR': 2,
 'PLOAD': 2,
 'PMOVE': 16,
 'PRESTORE': 1,
 'PSAVE': 1,
 'PScc': 2,
 'PTEST': 8,
 'PTRAPcc': 2,
 'PVALID': 4,
 'RESET': 1,
 'ROL, ROR': 2,
 'ROXL, ROXR': 2,
 'RTD': 2,
 'RTE': 1,
 'RTM': 1,
 'RTR': 1,
 'RTS': 1,
 'SBCD': 1,
 'STOP': 2,
 'SUB': 1,
 'SUBA': 1,
 'SUBI': 1,
 'SUBQ': 1,
 'SUBX': 1,
 'SWAP': 1,
 'Scc': 1,
 'TAS': 1,
 'TRAP': 1,
 'TRAPV': 1,
 'TRAPcc': 2,
 'TST': 1,
 'UNLK': 1,
 'UNPK': 1,
 'cpBcc': 1,
 'cpDBcc': 2,
 'cpGEN': 2,
 'cpRESTORE': 1,
 'cpSAVE': 1,
 'cpScc': 2,
 'cpTRAPcc': 2}
ENCODING_MASKS = ({'ABCD': (61936, 49408),
  'ADD': (61440, 53248),
  'ADDA': (61440, 53248),
  'ADDI': (65280, 1536),
  'ADDQ': (61696, 20480),
  'ADDX': (61744, 53504),
  'AND': (61440, 49152),
  'ANDI': (65280, 512),
  'ANDI to CCR': (65535, 572),
  'ANDI to SR': (65535, 636),
  'ASL, ASR': (61464, 57344),
  'BCHG': (61888, 320),
  'BCLR': (61888, 384),
  'BFCHG': (65472, 60096),
  'BFCLR': (65472, 60608),
  'BFEXTS': (65472, 60352),
  'BFEXTU': (65472, 59840),
  'BFFFO': (65472, 60864),
  'BFINS': (65472, 61376),
  'BFSET': (65472, 61120),
  'BFTST': (65472, 59584),
  'BKPT': (65528, 18504),
  'BRA': (65280, 24576),
  'BSET': (61888, 448),
  'BSR': (65280, 24832),
  'BTST': (61888, 256),
  'Bcc': (61440, 24576),
  'CALLM': (65472, 1728),
  'CAS CAS2': (63936, 2240),
  'CHK': (61504, 16384),
  'CHK2': (63936, 192),
  'CINV': (65312, 62464),
  'CLR': (65280, 16896),
  'CMP': (61440, 45056),
  'CMP2': (63936, 192),
  'CMPA': (61440, 45056),
  'CMPI': (65280, 3072),
  'CMPM': (61752, 45320),
  'CPUSH': (65312, 62496),
  'DBcc': (61688, 20680),
  'DIVS, DIVSL': (61888, 33216),
  'DIVU, DIVUL': (61888, 32960),
  'EOR': (61440, 45056),
  'EORI': (65280, 2560),
  'EORI to CCR': (65535, 2620),
  'EORI to SR': (65535, 2684),
  'EXG': (61696, 49408),
  'EXT, EXTB': (65080, 18432),
  'FRESTORE': (61888, 61760),
  'FSAVE': (61888, 61696),
  'ILLEGAL': (65535, 19196),
  'JMP': (65472, 20160),
  'JSR': (65472, 20096),
  'LEA': (61888, 16832),
  'LINK': (65528, 20048),
  'LSL, LSR': (61464, 57352),
  'MOVE': (49152, 0),
  'MOVE USP': (65520, 20064),
  'MOVE from CCR': (65472, 17088),
  'MOVE from SR': (65472, 16576),
  'MOVE to CCR': (65472, 17600),
  'MOVE to SR': (65472, 18112),
  'MOVE16': (65528, 63008),
  'MOVEA': (49600, 64),
  'MOVEC': (65534, 20090),
  'MOVEM': (64384, 18560),
  'MOVEP': (61496, 8),
  'MOVEQ': (61696, 28672),
  'MOVES': (65280, 3584),
  'MULS': (61888, 49600),
  'MULU': (61888, 49344),
  'NBCD': (65472, 18432),
  'NEG': (65280, 17408),
  'NEGX': (65280, 16384),
  'NOP': (65535, 20081),
  'NOT': (65280, 17920),
  'OR': (61440, 32768),
  'ORI': (65280, 0),
  'ORI to CCR': (65535, 60),
  'ORI to SR': (65535, 124),
  'PACK': (61936, 33088),
  'PBcc': (65408, 61568),
  'PDBcc': (65528, 61512),
  'PEA': (65472, 18496),
  'PFLUSH': (65472, 61440),
  'PFLUSH PFLUSHA': (65472, 61440),
  'PFLUSHR': (65472, 61440),
  'PLOAD': (65472, 61440),
  'PMOVE': (65472, 61440),
  'PRESTORE': (65472, 61760),
  'PSAVE': (65472, 61696),
  'PScc': (65472, 61504),
  'PTEST': (65472, 61440),
  'PTRAPcc': (65528, 61560),
  'PVALID': (65472, 61440),
  'RESET': (65535, 20080),
  'ROL, ROR': (61464, 57368),
  'ROXL, ROXR': (61464, 57360),
  'RTD': (65535, 20084),
  'RTE': (65535, 20083),
  'RTM': (65520, 1728),
  'RTR': (65535, 20087),
  'RTS': (65535, 20085),
  'SBCD': (61936, 33024),
  'STOP': (65535, 20082),
  'SUB': (61440, 36864),
  'SUBA': (61440, 36864),
  'SUBI': (65280, 1024),
  'SUBQ': (61696, 20736),
  'SUBX': (61744, 37120),
  'SWAP': (65528, 18496),
  'Scc': (61632, 20672),
  'TAS': (65472, 19136),
  'TRAP': (65520, 20032),
  'TRAPV': (65535, 20086),
  'TRAPcc': (61688, 20728),
  'TST': (65280, 18944),
  'UNLK': (65528, 20056),
  'UNPK': (61936, 33152),
  'cpBcc': (0, 0),
  'cpDBcc': (0, 0),
  'cpGEN': (0, 0),
  'cpRESTORE': (61888, 61760),
  'cpSAVE': (61888, 61696),
  'cpScc': (61888, 61504),
  'cpTRAPcc': (0, 0)},
 {'ASL, ASR': (65216, 57536),
  'BCHG': (65472, 2112),
  'BCLR': (65472, 2176),
  'BFCHG': (61440, 0),
  'BFCLR': (61440, 0),
  'BFEXTS': (32768, 0),
  'BFEXTU': (32768, 0),
  'BFFFO': (32768, 0),
  'BFINS': (32768, 0),
  'BFSET': (61440, 0),
  'BFTST': (61440, 0),
  'BSET': (65472, 2240),
  'BTST': (65472, 2048),
  'CALLM': (65280, 0),
  'CAS CAS2': (65080, 0),
  'CHK2': (4095, 2048),
  'CMP2': (4095, 0),
  'DBcc': (0, 0),
  'DIVS, DIVSL': (65472, 19520),
  'DIVU, DIVUL': (65472, 19520),
  'LINK': (0, 0),
  'LSL, LSR': (65216, 58048),
  'MOVE16': (36863, 32768),
  'MOVEC': (0, 0),
  'MOVEP': (0, 0),
  'MOVES': (2047, 0),
  'MULS': (65472, 19456),
  'MULU': (65472, 19456),
  'PDBcc': (65472, 0),
  'PFLUSH': (58112, 8192),
  'PFLUSH PFLUSHA': (57856, 8192),
  'PFLUSHR': (65535, 40960),
  'PLOAD': (64992, 8192),
  'PMOVE': (57599, 16384),
  'PScc': (65472, 0),
  'PTEST': (57344, 32768),
  'PTRAPcc': (65472, 0),
  'PVALID': (65535, 10240),
  'ROL, ROR': (65216, 59072),
  'ROXL, ROXR': (65216, 58560),
  'RTD': (0, 0),
  'STOP': (0, 0),
  'TRAPcc': (0, 0),
  'cpDBcc': (65472, 0),
  'cpGEN': (0, 0),
  'cpScc': (65472, 0),
  'cpTRAPcc': (65472, 0)},
 {'BCHG': (65280, 0),
  'BCLR': (65280, 0),
  'BSET': (65024, 0),
  'BTST': (65280, 0),
  'CAS CAS2': (63999, 2300),
  'DIVS, DIVSL': (35832, 2048),
  'DIVU, DIVUL': (35832, 0),
  'LINK': (65528, 18440),
  'MOVE16': (65504, 62976),
  'MULS': (35832, 2048),
  'MULU': (35832, 0),
  'PDBcc': (0, 0),
  'PFLUSH': (65504, 62720),
  'PMOVE': (65472, 61440),
  'PTEST': (65472, 61440),
  'PVALID': (65472, 61440)},
 {'CAS CAS2': (3640, 0),
  'LINK': (0, 0),
  'MOVE16': (0, 0),
  'PFLUSH': (65504, 62720),
  'PMOVE': (65023, 24576),
  'PTEST': (64768, 32768),
  'PVALID': (65528, 10240)},
 {'CAS CAS2': (3640, 0),
  'LINK': (0, 0),
  'MOVE16': (0, 0),
  'PMOVE': (65472, 61440),
  'PTEST': (65496, 62792)},
 {'PMOVE': (57599, 0), 'PTEST': (65496, 62792)},
 {'PMOVE': (65472, 61440), 'PTEST': (65472, 61440)},
 {'PMOVE': (65023, 24576), 'PTEST': (57344, 32768)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 0)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 16384)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57827, 24576)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 24576)})
FIXED_OPCODES = {60: 'ORI to CCR',
 124: 'ORI to SR',
 572: 'ANDI to CCR',
 636: 'ANDI to SR',
 2620: 'EORI to CCR',
 2684: 'EORI to SR',
 19196: 'ILLEGAL',
 20080: 'RESET',
 20081: 'NOP',
 20082: 'STOP',
 20083: 'RTE',
 20084: 'RTD',
 20085: 'RTS',
 20086: 'TRAPV',
 20087: 'RTR'}
EXT_FIELD_NAMES = {'ASL, ASR': ('MODE', 'REGISTER', 'dr'),
 'BCHG': ('MODE', 'REGISTER'),
 'BCLR': ('MODE', 'REGISTER'),
 'BFCHG': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFCLR': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFEXTS': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFEXTU': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFFFO': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFINS': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFSET': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFTST': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BSET': ('MODE', 'REGISTER'),
 'BTST': ('MODE', 'REGISTER'),
 'CALLM': ('ARGUMENT COUNT',),
 'CAS CAS2': ('Dc', 'Du'),
 'CHK2': ('D/A', 'REGISTER'),
 'CMP2': ('D/A', 'REGISTER'),
 'DBcc': ('16-BIT DISPLACEMENT',),
 'DIVS, DIVSL': ('MODE', 'REGISTER'),
 'DIVU, DIVUL': ('MODE', 'REGISTER'),
 'LINK': ('WORD DISPLACEMENT',),
 'LSL, LSR': ('MODE', 'REGISTER', 'dr'),
 'MOVE16': ('REGISTER Ay',),
 'MOVEC': ('A/D', 'CONTROL REGISTER', 'REGISTER'),
 'MOVEP': ('16-BIT DISPLACEMENT',),
 'MOVES': ('A/D', 'REGISTER', 'dr'),
 'MULS': ('MODE', 'REGISTER'),
 'MULU': ('MODE', 'REGISTER'),
 'PDBcc': ('MC68851 CONDITION',),
 'PFLUSH': ('FC', 'MASK', 'MODE'),
 'PFLUSH PFLUSHA': ('FC', 'MASK', 'MODE'),
 'PFLUSHR': (),
 'PLOAD': ('FC', 'R/ W'),
 'PMOVE': ('FD', 'P-REGISTER', 'R/ W'),
 'PScc': ('MC68851 CONDITION',),
 'PTEST': ('A', 'FC', 'LEVEL', 'R/ W', 'REGISTER'),
 'PTRAPcc': ('MC68851 CONDITION',),
 'PVALID': (),
 'ROL, ROR': ('MODE', 'REGISTER', 'dr'),
 'ROXL, ROXR': ('MODE', 'REGISTER', 'dr'),
 'RTD': ('16-BIT DISPLACEMENT',),
 'STOP': ('IMMEDIATE DATA',),
 'TRAPcc': ('OPTIONAL WORD',),
 'cpDBcc': ('COPROCESSOR CONDITION',),
 'cpGEN': ('MODE', 'REGISTER'),
 'cpScc': ('COPROCESSOR CONDITION',),
 'cpTRAPcc': ('COPROCESSOR CONDITION',)}
FIELD_MAPS = ({'ABCD': {'REGISTER Rx': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Ry': (2, 0, 3)},
  'ADD': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDX': {'REGISTER Rx': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Ry': (2, 0, 3)},
  'AND': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ANDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ANDI to CCR': {},
  'ANDI to SR': {},
  'ASL, ASR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'BCHG': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BCLR': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BFCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFFFO': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFINS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BKPT': {'VECTOR': (2, 0, 3)},
  'BRA': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BSET': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BSR': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BTST': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'Bcc': {'CONDITION': (11, 8, 4), '8-BIT DISPLACEMENT': (7, 0, 8)},
  'CALLM': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CAS CAS2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CHK': {'REGISTER': (2, 0, 3), 'SIZE': (8, 7, 2), 'MODE': (5, 3, 3)},
  'CHK2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CINV': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'CLR': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMP': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMP2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMPI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPM': {'REGISTER Ax': (11, 9, 3), 'SIZE': (7, 6, 2), 'REGISTER Ay': (2, 0, 3)},
  'CPUSH': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'DBcc': {'CONDITION': (11, 8, 4), 'REGISTER': (2, 0, 3)},
  'DIVS, DIVSL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'DIVU, DIVUL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'EOR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'EORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'EORI to CCR': {},
  'EORI to SR': {},
  'EXG': {'REGISTER Rx': (11, 9, 3), 'OPMODE': (7, 3, 5), 'REGISTER Ry': (2, 0, 3)},
  'EXT, EXTB': {'OPMODE': (8, 6, 3), 'REGISTER': (2, 0, 3)},
  'FRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'FSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ILLEGAL': {},
  'JMP': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'JSR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LEA': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'LSL, LSR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'MOVE': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVE USP': {'dr': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'MOVE from CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE from SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ax': (2, 0, 3)},
  'MOVEA': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVEC': {'dr': (0, 0, 1)},
  'MOVEM': {'dr': (10, 10, 1), 'SIZE': (6, 6, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVEP': {'DATA REGISTER': (11, 9, 3), 'OPMODE': (8, 6, 3), 'ADDRESS REGISTER': (2, 0, 3)},
  'MOVEQ': {'REGISTER': (11, 9, 3), 'DATA': (7, 0, 8)},
  'MOVES': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULS': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MULU': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'NBCD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEG': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEGX': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NOP': {},
  'NOT': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'OR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ORI to CCR': {},
  'ORI to SR': {},
  'PACK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'PBcc': {'SIZE': (6, 6, 1), 'MC68851 CONDITION': (5, 0, 6)},
  'PDBcc': {'COUNT REGISTER': (2, 0, 3)},
  'PEA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH PFLUSHA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSHR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PLOAD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PRESTORE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PSAVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PScc': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTRAPcc': {'OPMODE': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'RESET': {},
  'ROL, ROR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'ROXL, ROXR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'RTD': {},
  'RTE': {},
  'RTM': {'D/A': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'RTR': {},
  'RTS': {},
  'SBCD': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'STOP': {},
  'SUB': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBX': {'REGISTER Dy/Ay': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Dx/Ax': (2, 0, 3)},
  'SWAP': {'REGISTER': (2, 0, 3)},
  'Scc': {'CONDITION': (11, 8, 4), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TAS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TRAP': {'VECTOR': (3, 0, 4)},
  'TRAPV': {},
  'TRAPcc': {'CONDITION': (11, 8, 4), 'OPMODE': (2, 0, 3)},
  'TST': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'UNLK': {'REGISTER': (2, 0, 3)},
  'UNPK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'cpBcc': {'ID': (15, 0, 16)},
  'cpDBcc': {'ID': (15, 0, 16)},
  'cpGEN': {'ID': (15, 0, 16)},
  'cpRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpScc': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpTRAPcc': {'ID': (15, 0, 16)}},
 {'ASL, ASR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCHG': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFCLR': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFEXTS': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFEXTU': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFFFO': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFINS': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFSET': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFTST': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CALLM': {'ARGUMENT COUNT': (7, 0, 8)},
  'CAS CAS2': {'Du': (8, 6, 3), 'Dc': (2, 0, 3)},
  'CHK2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'CMP2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'DBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'DIVS, DIVSL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'DIVU, DIVUL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LINK': {'WORD DISPLACEMENT': (15, 0, 16)},
  'LSL, LSR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ay': (14, 12, 3)},
  'MOVEC': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'CONTROL REGISTER': (11, 0, 12)},
  'MOVEP': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'MOVES': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'dr': (11, 11, 1)},
  'MULS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PDBcc': {'MC68851 CONDITION': (5, 0, 6)},
  'PFLUSH': {'MODE': (12, 10, 3), 'MASK': (7, 4, 4), 'FC': (3, 0, 4)},
  'PFLUSH PFLUSHA': {'MODE': (12, 10, 3), 'MASK': (7, 5, 3), 'FC': (3, 0, 4)},
  'PFLUSHR': {},
  'PLOAD': {'R/ W': (9, 9, 1), 'FC': (4, 0, 5)},
  'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PScc': {'MC68851 CONDITION': (5, 0, 6)},
  'PTEST': {'LEVEL': (12, 10, 3),
            'R/ W': (9, 9, 1),
            'A': (8, 8, 1),
            'REGISTER': (7, 3, 5),
            'FC': (2, 0, 3)},
  'PTRAPcc': {'MC68851 CONDITION': (5, 0, 6)},
  'PVALID': {},
  'ROL, ROR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ROXL, ROXR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'RTD': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'STOP': {'IMMEDIATE DATA': (15, 0, 16)},
  'TRAPcc': {'OPTIONAL WORD': (15, 0, 16)},
  'cpDBcc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpGEN': {'MODE': (15, 3, 13), 'REGISTER': (2, 0, 3)},
  'cpScc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpTRAPcc': {'COPROCESSOR CONDITION': (5, 0, 6)}},
 {'BCHG': {'BIT NUMBER': (7, 0, 8)},
  'BCLR': {'BIT NUMBER': (7, 0, 8)},
  'BSET': {'BIT NUMBER': (8, 0, 9)},
  'BTST': {'BIT NUMBER': (7, 0, 8)},
  'CAS CAS2': {'SIZE': (10, 9, 2)},
  'DIVS, DIVSL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'DIVU, DIVUL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'MOVE16': {'OPMODE': (4, 3, 2), 'REGISTER Ay': (2, 0, 3)},
  'MULS': {'REGISTER DI': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'MULU': {'REGISTER Dl': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'PDBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A1': (15, 15, 1), 'Rn1': (14, 12, 3), 'Du1': (8, 6, 3), 'Dc1': (2, 0, 3)},
  'LINK': {'HIGH-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'HIGH-ORDER ADDRESS': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'R/ W': (9, 9, 1)},
  'PTEST': {'R/ W': (9, 9, 1), 'REGISTER': (7, 4, 4), 'FC': (3, 0, 4)},
  'PVALID': {'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A2': (15, 15, 1), 'Rn2': (14, 12, 3), 'Du2': (8, 6, 3), 'Dc2': (2, 0, 3)},
  'LINK': {'LOW-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'LOW-ORDER ADDRESS': (15, 0, 16)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'R/W': (9, 9, 1)},
  'PTEST': {'LEVEL': (12, 10, 3), 'R/ W': (9, 9, 1), 'A-REGISTER': (8, 6, 3), 'FC': (5, 0, 6)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'NUM': (4, 2, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}})
RAW_FIELDS = ({'ABCD': (('REGISTER Rx', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Ry', 2, 0, 3)),
  'ADD': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDX': (('REGISTER Rx', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Ry', 2, 0, 3)),
  'AND': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ANDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ANDI to CCR': (),
  'ANDI to SR': (),
  'ASL, ASR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'BCHG': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFFFO': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFINS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BKPT': (('VECTOR', 2, 0, 3),),
  'BRA': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BSET': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BSR': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BTST': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'Bcc': (('CONDITION', 11, 8, 4), ('8-BIT DISPLACEMENT', 7, 0, 8)),
  'CALLM': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CAS CAS2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK': (('REGISTER', 11, 9, 3), ('SIZE', 8, 7, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CINV': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'CLR': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPM': (('REGISTER Ax', 11, 9, 3), ('SIZE', 7, 6, 2), ('REGISTER Ay', 2, 0, 3)),
  'CPUSH': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'DBcc': (('CONDITION', 11, 8, 4), ('REGISTER', 2, 0, 3)),
  'DIVS, DIVSL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EOR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EORI to CCR': (),
  'EORI to SR': (),
  'EXG': (('REGISTER Rx', 11, 9, 3), ('OPMODE', 7, 3, 5), ('REGISTER Ry', 2, 0, 3)),
  'EXT, EXTB': (('OPMODE', 8, 6, 3), ('REGISTER', 2, 0, 3)),
  'FRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'FSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ILLEGAL': (),
  'JMP': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'JSR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LEA': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'LSL, LSR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'MOVE': (('SIZE', 13, 12, 2),
           ('REGISTER', 11, 9, 3),
           ('MODE', 8, 6, 3),
           ('MODE', 5, 3, 3),
           ('REGISTER', 2, 0, 3)),
  'MOVE USP': (('dr', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'MOVE from CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE from SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ax', 2, 0, 3),),
  'MOVEA': (('SIZE', 13, 12, 2), ('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEC': (('dr', 0, 0, 1),),
  'MOVEM': (('dr', 10, 10, 1), ('SIZE', 6, 6, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEP': (('DATA REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('ADDRESS REGISTER', 2, 0, 3)),
  'MOVEQ': (('REGISTER', 11, 9, 3), ('DATA', 7, 0, 8)),
  'MOVES': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULS': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NBCD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEG': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEGX': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NOP': (),
  'NOT': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'OR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ORI to CCR': (),
  'ORI to SR': (),
  'PACK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'PBcc': (('SIZE', 6, 6, 1), ('MC68851 CONDITION', 5, 0, 6)),
  'PDBcc': (('COUNT REGISTER', 2, 0, 3),),
  'PEA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH PFLUSHA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSHR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PLOAD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PRESTORE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PSAVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PScc': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTRAPcc': (('OPMODE', 2, 0, 3),),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'RESET': (),
  'ROL, ROR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('REGISTER', 11, 9, 3),
                 ('dr', 8, 8, 1),
                 ('SIZE', 7, 6, 2),
                 ('i/r', 5, 5, 1),
                 ('REGISTER', 2, 0, 3)),
  'RTD': (),
  'RTE': (),
  'RTM': (('D/A', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'RTR': (),
  'RTS': (),
  'SBCD': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'STOP': (),
  'SUB': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBX': (('REGISTER Dy/Ay', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Dx/Ax', 2, 0, 3)),
  'SWAP': (('REGISTER', 2, 0, 3),),
  'Scc': (('CONDITION', 11, 8, 4), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TAS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TRAP': (('VECTOR', 3, 0, 4),),
  'TRAPV': (),
  'TRAPcc': (('CONDITION', 11, 8, 4), ('OPMODE', 2, 0, 3)),
  'TST': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'UNLK': (('REGISTER', 2, 0, 3),),
  'UNPK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'cpBcc': (('ID', 15, 0, 16),),
  'cpDBcc': (('ID', 15, 0, 16),),
  'cpGEN': (('ID', 15, 0, 16),),
  'cpRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpScc': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpTRAPcc': (('ID', 15, 0, 16),)},
 {'ASL, ASR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFCLR': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFEXTS': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFEXTU': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFFFO': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFINS': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFSET': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFTST': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CALLM': (('ARGUMENT COUNT', 7, 0, 8),),
  'CAS CAS2': (('Du', 8, 6, 3), ('Dc', 2, 0, 3)),
  'CHK2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'CMP2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'DBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'DIVS, DIVSL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('WORD DISPLACEMENT', 15, 0, 16),),
  'LSL, LSR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ay', 14, 12, 3),),
  'MOVEC': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('CONTROL REGISTER', 11, 0, 12)),
  'MOVEP': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'MOVES': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('dr', 11, 11, 1)),
  'MULS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PDBcc': (('MC68851 CONDITION', 5, 0, 6),),
  'PFLUSH': (('MODE', 12, 10, 3), ('MASK', 7, 4, 4), ('FC', 3, 0, 4)),
  'PFLUSH PFLUSHA': (('MODE', 12, 10, 3), ('MASK', 7, 5, 3), ('FC', 3, 0, 4)),
  'PFLUSHR': (),
  'PLOAD': (('R/ W', 9, 9, 1), ('FC', 4, 0, 5)),
  'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PScc': (('MC68851 CONDITION', 5, 0, 6),),
  'PTEST': (('LEVEL', 12, 10, 3),
            ('R/ W', 9, 9, 1),
            ('A', 8, 8, 1),
            ('REGISTER', 7, 3, 5),
            ('FC', 2, 0, 3)),
  'PTRAPcc': (('MC68851 CONDITION', 5, 0, 6),),
  'PVALID': (),
  'ROL, ROR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'RTD': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'STOP': (('IMMEDIATE DATA', 15, 0, 16),),
  'TRAPcc': (('OPTIONAL WORD', 15, 0, 16),),
  'cpDBcc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpGEN': (('MODE', 15, 3, 13), ('REGISTER', 2, 0, 3)),
  'cpScc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpTRAPcc': (('COPROCESSOR CONDITION', 5, 0, 6),)},
 {'BCHG': (('BIT NUMBER', 7, 0, 8),),
  'BCLR': (('BIT NUMBER', 7, 0, 8),),
  'BSET': (('BIT NUMBER', 8, 0, 9),),
  'BTST': (('BIT NUMBER', 7, 0, 8),),
  'CAS CAS2': (('SIZE', 10, 9, 2),),
  'DIVS, DIVSL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'MOVE16': (('OPMODE', 4, 3, 2), ('REGISTER Ay', 2, 0, 3)),
  'MULS': (('REGISTER DI', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'MULU': (('REGISTER Dl', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'PDBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'CAS CAS2': (('D/A1', 15, 15, 1), ('Rn1', 14, 12, 3), ('Du1', 8, 6, 3), ('Dc1', 2, 0, 3)),
  'LINK': (('HIGH-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('HIGH-ORDER ADDRESS', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('R/ W', 9, 9, 1),),
  'PTEST': (('R/ W', 9, 9, 1), ('REGISTER', 7, 4, 4), ('FC', 3, 0, 4)),
  'PVALID': (('REGISTER', 2, 0, 3),)},
 {'CAS CAS2': (('D/A2', 15, 15, 1), ('Rn2', 14, 12, 3), ('Du2', 8, 6, 3), ('Dc2', 2, 0, 3)),
  'LINK': (('LOW-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('LOW-ORDER ADDRESS', 15, 0, 16),),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('R/W', 9, 9, 1),),
  'PTEST': (('LEVEL', 12, 10, 3), ('R/ W', 9, 9, 1), ('A-REGISTER', 8, 6, 3), ('FC', 5, 0, 6))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('NUM', 4, 2, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))})
FORM_OPERAND_TYPES = {'ABCD': (('dn', 'dn'), ('predec', 'predec')),
 'ADD': (('ea', 'dn'), ('dn', 'ea')),
 'ADDA': (('ea', 'an'),),
 'ADDI': (('imm', 'ea'),),
 'ADDQ': (('imm', 'ea'),),
 'ADDX': (('dn', 'dn'), ('predec', 'predec')),
 'AND': (('ea', 'dn'), ('dn', 'ea')),
 'ANDI': (('imm', 'ea'),),
 'ANDI to CCR': (('imm', 'ccr'),),
 'ANDI to SR': (('imm', 'sr'),),
 'ASL, ASR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'BCHG': (('dn', 'ea'), ('imm', 'ea')),
 'BCLR': (('dn', 'ea'), ('imm', 'ea')),
 'BFCHG': (('bf_ea',),),
 'BFCLR': (('bf_ea',),),
 'BFEXTS': (('bf_ea', 'dn'),),
 'BFEXTU': (('bf_ea', 'dn'),),
 'BFFFO': (('bf_ea', 'dn'),),
 'BFINS': (('dn', 'bf_ea'),),
 'BFSET': (('bf_ea',),),
 'BFTST': (('bf_ea',),),
 'BKPT': (('imm',),),
 'BRA': (('label',),),
 'BSET': (('dn', 'ea'), ('imm', 'ea')),
 'BSR': (('label',),),
 'BTST': (('dn', 'ea'), ('imm', 'ea')),
 'Bcc': (('label',),),
 'CALLM': (('imm', 'ea'),),
 'CAS CAS2': (('dn', 'dn', 'ea'), ('dn_pair', 'dn_pair', 'unknown')),
 'CHK': (('ea', 'dn'),),
 'CHK2': (('ea', 'rn'),),
 'CINV': (),
 'CLR': (('ea',),),
 'CMP': (('ea', 'dn'),),
 'CMP2': (('ea', 'rn'),),
 'CMPA': (('ea', 'an'),),
 'CMPI': (('imm', 'ea'),),
 'CMPM': (('postinc', 'postinc'),),
 'CPUSH': (),
 'DBcc': (('dn', 'label'),),
 'DIVS, DIVSL': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair'), ('ea', 'dn_pair')),
 'DIVU, DIVUL': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair'), ('ea', 'dn_pair')),
 'EOR': (('dn', 'ea'),),
 'EORI': (('imm', 'ea'),),
 'EORI to CCR': (('imm', 'ccr'),),
 'EORI to SR': (('imm', 'sr'),),
 'EXG': (('dn', 'dn'), ('an', 'an'), ('dn', 'an')),
 'EXT, EXTB': (('dn',), ('dn',), ('dn',)),
 'FRESTORE': (('ea',),),
 'FSAVE': (('ea',),),
 'ILLEGAL': ((),),
 'JMP': (('ea',),),
 'JSR': (('ea',),),
 'LEA': (('ea', 'an'),),
 'LINK': (('an', 'imm'),),
 'LSL, LSR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'MOVE': (('ea', 'ea'),),
 'MOVE USP': (('usp', 'an'), ('an', 'usp')),
 'MOVE from CCR': (('ccr', 'ea'),),
 'MOVE from SR': (('sr', 'ea'),),
 'MOVE to CCR': (('ea', 'ccr'),),
 'MOVE to SR': (('ea', 'sr'),),
 'MOVE16': (('postinc', 'postinc'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown')),
 'MOVEA': (('ea', 'an'),),
 'MOVEC': (('ctrl_reg', 'rn'), ('rn', 'ctrl_reg')),
 'MOVEM': (('reglist', 'ea'), ('ea', 'reglist')),
 'MOVEP': (('dn', 'disp'), ('disp', 'dn')),
 'MOVEQ': (('imm', 'dn'),),
 'MOVES': (('rn', 'ea'), ('ea', 'rn')),
 'MULS': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair')),
 'MULU': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair')),
 'NBCD': (('ea',),),
 'NEG': (('ea',),),
 'NEGX': (('ea',),),
 'NOP': ((),),
 'NOT': (('ea',),),
 'OR': (('ea', 'dn'), ('dn', 'ea')),
 'ORI': (('imm', 'ea'),),
 'ORI to CCR': (('imm', 'ccr'),),
 'ORI to SR': (('imm', 'sr'),),
 'PACK': (('predec', 'predec', 'imm'), ('dn', 'dn', 'imm')),
 'PBcc': (('label',),),
 'PDBcc': (('dn', 'label'),),
 'PEA': (('ea',),),
 'PFLUSH': (('unknown', 'unknown'), ('unknown', 'unknown', 'ea')),
 'PFLUSH PFLUSHA': ((), ('unknown', 'unknown'), ('unknown', 'unknown', 'ea')),
 'PFLUSHR': (('ea',),),
 'PLOAD': (),
 'PMOVE': (('unknown', 'ea'), ('ea', 'unknown')),
 'PRESTORE': (('ea',),),
 'PSAVE': (('ea',),),
 'PScc': (('ea',),),
 'PTEST': (),
 'PTRAPcc': ((), ('imm',), ('imm',)),
 'PVALID': (('unknown', 'ea'), ('an', 'ea')),
 'RESET': ((),),
 'ROL, ROR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'ROXL, ROXR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'RTD': (('imm',),),
 'RTE': ((),),
 'RTM': (('rn',),),
 'RTR': ((),),
 'RTS': ((),),
 'SBCD': (('dn', 'dn'), ('predec', 'predec')),
 'STOP': (('imm',),),
 'SUB': (('ea', 'dn'), ('dn', 'ea')),
 'SUBA': (('ea', 'an'),),
 'SUBI': (('imm', 'ea'),),
 'SUBQ': (('imm', 'ea'),),
 'SUBX': (('dn', 'dn'), ('predec', 'predec')),
 'SWAP': (('dn',),),
 'Scc': (('ea',),),
 'TAS': (('ea',),),
 'TRAP': (('imm',),),
 'TRAPV': ((),),
 'TRAPcc': ((), ('imm',), ('imm',)),
 'TST': (('ea',),),
 'UNLK': (('an',),),
 'UNPK': (('dn', 'dn', 'imm'),),
 'cpBcc': (('label',),),
 'cpDBcc': (('dn', 'label'),),
 'cpGEN': (('unknown',),),
 'cpRESTORE': (('ea',),),
 'cpSAVE': (('ea',),),
 'cpScc': (('ea',),),
 'cpTRAPcc': ((), ('imm',))}
EA_BRIEF_FIELDS = {'D/A': (15, 15, 1),
 'REGISTER': (14, 12, 3),
 'W/L': (11, 11, 1),
 'SCALE': (10, 9, 2),
 'DISPLACEMENT': (7, 0, 8)}
MOVEM_REG_MASKS = {'normal': ['d0',
            'd1',
            'd2',
            'd3',
            'd4',
            'd5',
            'd6',
            'd7',
            'a0',
            'a1',
            'a2',
            'a3',
            'a4',
            'a5',
            'a6',
            'a7'],
 'predecrement': ['a7',
                  'a6',
                  'a5',
                  'a4',
                  'a3',
                  'a2',
                  'a1',
                  'a0',
                  'd7',
                  'd6',
                  'd5',
                  'd4',
                  'd3',
                  'd2',
                  'd1',
                  'd0']}
DEST_REG_FIELD = {'ABCD': (11, 9, 3),
 'ADD': (11, 9, 3),
 'ADDA': (11, 9, 3),
 'ADDX': (11, 9, 3),
 'AND': (11, 9, 3),
 'ASL, ASR': (11, 9, 3),
 'BCHG': (11, 9, 3),
 'BCLR': (11, 9, 3),
 'BSET': (11, 9, 3),
 'BTST': (11, 9, 3),
 'CHK': (11, 9, 3),
 'CMP': (11, 9, 3),
 'CMPA': (11, 9, 3),
 'CMPM': (11, 9, 3),
 'DIVS, DIVSL': (11, 9, 3),
 'DIVU, DIVUL': (11, 9, 3),
 'EOR': (11, 9, 3),
 'EXG': (11, 9, 3),
 'LEA': (11, 9, 3),
 'LSL, LSR': (11, 9, 3),
 'MOVE': (11, 9, 3),
 'MOVEA': (11, 9, 3),
 'MOVEQ': (11, 9, 3),
 'MULS': (11, 9, 3),
 'MULU': (11, 9, 3),
 'OR': (11, 9, 3),
 'PACK': (11, 9, 3),
 'ROL, ROR': (11, 9, 3),
 'ROXL, ROXR': (11, 9, 3),
 'SBCD': (11, 9, 3),
 'SUB': (11, 9, 3),
 'SUBA': (11, 9, 3),
 'SUBX': (11, 9, 3),
 'UNPK': (11, 9, 3)}
BF_MNEMONICS = ('BFCHG', 'BFCLR', 'BFEXTS', 'BFEXTU', 'BFFFO', 'BFINS', 'BFSET', 'BFTST')
BITOP_NAMES = ({0: 'btst', 1: 'bchg', 2: 'bclr', 3: 'bset'}, (7, 6, 2))
IMM_NAMES = ({0: 'ori', 1: 'andi', 2: 'subi', 3: 'addi', 5: 'eori', 6: 'cmpi'}, (11, 9, 3))
SHIFT_NAMES = {0: 'as', 1: 'ls', 2: 'rox', 3: 'ro'}
SHIFT_TYPE_FIELDS = ((4, 3, 2), (10, 9, 2))
SHIFT_FIELDS = ((8, 8, 1), ('r', 'l'), 8)
RM_FIELD = {'ABCD': (3, ('dn,dn', 'predec,predec')),
 'ADDX': (3, ('dn,dn', 'predec,predec')),
 'PACK': (3, ('dn,dn', 'predec,predec')),
 'SBCD': (3, ('dn,dn', 'predec,predec')),
 'SUBX': (3, ('dn,dn', 'predec,predec')),
 'UNPK': (3, ('dn,dn', 'predec,predec'))}
ADDQ_ZERO_MEANS = 8
CONTROL_REGISTERS = {0: 'sfc',
 1: 'dfc',
 2: 'cacr',
 3: 'tc',
 4: 'itt0',
 5: 'itt1',
 6: 'dtt0',
 7: 'dtt1',
 2048: 'usp',
 2049: 'vbr',
 2050: 'caar',
 2051: 'msp',
 2052: 'isp',
 2053: 'mmusr',
 2054: 'urp',
 2055: 'srp'}
SIZE_ENCODINGS_DISASM = {'ADDI': (0, 1, 2, None),
 'ADDQ': (0, 1, 2, None),
 'ADDX': (0, 1, 2, None),
 'ANDI': (0, 1, 2, None),
 'ASL, ASR': (0, 1, 2, None),
 'CAS CAS2': (None, 0, 1, 2),
 'CHK': (None, None, 2, 1),
 'CHK2': (0, 1, 2, None),
 'CLR': (0, 1, 2, None),
 'CMP2': (0, 1, 2, None),
 'CMPI': (0, 1, 2, None),
 'CMPM': (0, 1, 2, None),
 'DIVS, DIVSL': (1, 2, None, None),
 'DIVU, DIVUL': (1, 2, None, None),
 'EORI': (0, 1, 2, None),
 'LSL, LSR': (0, 1, 2, None),
 'MOVE': (None, 0, 2, 1),
 'MOVEA': (None, None, 2, 1),
 'MOVEM': (1, 2, None, None),
 'MOVES': (0, 1, 2, None),
 'MULS': (1, 2, None, None),
 'MULU': (1, 2, None, None),
 'NEG': (0, 1, 2, None),
 'NEGX': (0, 1, 2, None),
 'NOT': (0, 1, 2, None),
 'ORI': (0, 1, 2, None),
 'ROL, ROR': (0, 1, 2, None),
 'ROXL, ROXR': (0, 1, 2, None),
 'SUBI': (0, 1, 2, None),
 'SUBQ': (0, 1, 2, None),
 'SUBX': (0, 1, 2, None),
 'TST': (0, 1, 2, None)}
INSTRUCTION_SIZES = {'ABCD': ('b',),
 'ADD': ('b', 'w', 'l'),
 'ADDA': ('w', 'l'),
 'ADDI': ('b', 'w', 'l'),
 'ADDQ': ('b', 'w', 'l'),
 'ADDX': ('b', 'w', 'l'),
 'AND': ('b', 'w', 'l'),
 'ANDI': ('b', 'w', 'l'),
 'ANDI to CCR': ('b',),
 'ANDI to SR': ('w',),
 'ASL, ASR': ('b', 'w', 'l'),
 'BCHG': ('b', 'l'),
 'BCLR': ('b', 'l'),
 'BFCHG': (),
 'BFCLR': (),
 'BFEXTS': (),
 'BFEXTU': (),
 'BFFFO': (),
 'BFINS': (),
 'BFSET': (),
 'BFTST': (),
 'BKPT': (),
 'BRA': ('b', 'w', 'l'),
 'BSET': ('b', 'l'),
 'BSR': ('b', 'w', 'l'),
 'BTST': ('b', 'l'),
 'Bcc': ('b', 'w', 'l'),
 'CALLM': (),
 'CAS CAS2': ('b', 'w', 'l'),
 'CHK': ('w', 'l'),
 'CHK2': ('b', 'w', 'l'),
 'CINV': (),
 'CLR': ('b', 'w', 'l'),
 'CMP': ('b', 'w', 'l'),
 'CMP2': ('b', 'w', 'l'),
 'CMPA': ('w', 'l'),
 'CMPI': ('b', 'w', 'l'),
 'CMPM': ('b', 'w', 'l'),
 'CPUSH': (),
 'DBcc': ('w',),
 'DIVS, DIVSL': ('w', 'l'),
 'DIVU, DIVUL': ('w', 'l'),
 'EOR': ('b', 'w', 'l'),
 'EORI': ('b', 'w', 'l'),
 'EORI to CCR': ('b',),
 'EORI to SR': ('w',),
 'EXG': ('l',),
 'EXT, EXTB': ('w', 'l'),
 'FRESTORE': (),
 'FSAVE': (),
 'ILLEGAL': (),
 'JMP': (),
 'JSR': (),
 'LEA': ('l',),
 'LINK': ('w', 'l'),
 'LSL, LSR': ('b', 'w', 'l'),
 'MOVE': ('b', 'w', 'l'),
 'MOVE USP': ('l',),
 'MOVE from CCR': ('w',),
 'MOVE from SR': ('w',),
 'MOVE to CCR': ('w',),
 'MOVE to SR': ('w',),
 'MOVE16': (),
 'MOVEA': ('w', 'l'),
 'MOVEC': ('l',),
 'MOVEM': ('w', 'l'),
 'MOVEP': ('w', 'l'),
 'MOVEQ': ('l',),
 'MOVES': ('b', 'w', 'l'),
 'MULS': ('w', 'l'),
 'MULU': ('w', 'l'),
 'NBCD': ('b',),
 'NEG': ('b', 'w', 'l'),
 'NEGX': ('b', 'w', 'l'),
 'NOP': (),
 'NOT': ('b', 'w', 'l'),
 'OR': ('b', 'w', 'l'),
 'ORI': ('b', 'w', 'l'),
 'ORI to CCR': ('b',),
 'ORI to SR': ('w',),
 'PACK': (),
 'PBcc': ('w', 'l'),
 'PDBcc': ('w',),
 'PEA': ('l',),
 'PFLUSH': (),
 'PFLUSH PFLUSHA': (),
 'PFLUSHR': (),
 'PLOAD': (),
 'PMOVE': ('w', 'l'),
 'PRESTORE': (),
 'PSAVE': (),
 'PScc': ('b',),
 'PTEST': (),
 'PTRAPcc': ('w', 'l'),
 'PVALID': ('l',),
 'RESET': (),
 'ROL, ROR': ('b', 'w', 'l'),
 'ROXL, ROXR': ('b', 'w', 'l'),
 'RTD': (),
 'RTE': (),
 'RTM': (),
 'RTR': (),
 'RTS': (),
 'SBCD': ('b',),
 'STOP': (),
 'SUB': ('b', 'w', 'l'),
 'SUBA': ('w', 'l'),
 'SUBI': ('b', 'w', 'l'),
 'SUBQ': ('b', 'w', 'l'),
 'SUBX': ('b', 'w', 'l'),
 'SWAP': ('w',),
 'Scc': ('b',),
 'TAS': ('b',),
 'TRAP': (),
 'TRAPV': (),
 'TRAPcc': ('w', 'l'),
 'TST': ('b', 'w', 'l'),
 'UNLK': (),
 'UNPK': (),
 'cpBcc': ('w', 'l'),
 'cpDBcc': ('w',),
 'cpGEN': (),
 'cpRESTORE': (),
 'cpSAVE': (),
 'cpScc': ('b',),
 'cpTRAPcc': ('w', 'l')}
OPERATION_TYPES = {'ABCD': OperationType.ADD_DECIMAL,
 'ADD': OperationType.ADD,
 'ADDA': OperationType.ADD,
 'ADDI': OperationType.ADD,
 'ADDQ': OperationType.ADD,
 'ADDX': OperationType.ADDX,
 'AND': OperationType.AND,
 'ANDI': OperationType.AND,
 'ANDI to CCR': OperationType.CCR_OP,
 'ANDI to SR': OperationType.SR_OP,
 'ASL, ASR': OperationType.SHIFT,
 'BCHG': OperationType.BIT_TEST,
 'BCLR': OperationType.BIT_TEST,
 'BFCHG': OperationType.BITFIELD,
 'BFCLR': OperationType.BITFIELD,
 'BFEXTS': OperationType.BITFIELD,
 'BFEXTU': OperationType.BITFIELD,
 'BFFFO': OperationType.BITFIELD,
 'BFINS': OperationType.BITFIELD,
 'BFSET': OperationType.BITFIELD,
 'BFTST': OperationType.BITFIELD,
 'BKPT': None,
 'BRA': OperationType.ADD,
 'BSET': OperationType.BIT_TEST,
 'BSR': OperationType.SUB,
 'BTST': OperationType.BIT_TEST,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': OperationType.COMPARE_SWAP,
 'CHK': OperationType.BOUNDS_CHECK,
 'CHK2': OperationType.BOUNDS_CHECK,
 'CINV': OperationType.SR_OP,
 'CLR': OperationType.CLEAR,
 'CMP': OperationType.COMPARE,
 'CMP2': OperationType.BOUNDS_CHECK,
 'CMPA': OperationType.COMPARE,
 'CMPI': OperationType.COMPARE,
 'CMPM': OperationType.COMPARE,
 'CPUSH': OperationType.SR_OP,
 'DBcc': None,
 'DIVS, DIVSL': OperationType.DIVIDE,
 'DIVU, DIVUL': OperationType.DIVIDE,
 'EOR': OperationType.XOR,
 'EORI': OperationType.XOR,
 'EORI to CCR': OperationType.CCR_OP,
 'EORI to SR': OperationType.SR_OP,
 'EXG': OperationType.SWAP,
 'EXT, EXTB': OperationType.SIGN_EXTEND,
 'FRESTORE': OperationType.SR_OP,
 'FSAVE': OperationType.SR_OP,
 'ILLEGAL': OperationType.SUB,
 'JMP': OperationType.MOVE,
 'JSR': OperationType.SUB,
 'LEA': OperationType.MOVE,
 'LINK': OperationType.SUB,
 'LSL, LSR': OperationType.SHIFT,
 'MOVE': OperationType.MOVE,
 'MOVE USP': OperationType.SR_OP,
 'MOVE from CCR': OperationType.CCR_OP,
 'MOVE from SR': OperationType.MOVE,
 'MOVE to CCR': OperationType.CCR_OP,
 'MOVE to SR': OperationType.SR_OP,
 'MOVE16': OperationType.MOVE,
 'MOVEA': OperationType.MOVE,
 'MOVEC': OperationType.SR_OP,
 'MOVEM': OperationType.MOVE,
 'MOVEP': OperationType.MOVE,
 'MOVEQ': OperationType.MOVE,
 'MOVES': OperationType.SR_OP,
 'MULS': OperationType.MULTIPLY,
 'MULU': OperationType.MULTIPLY,
 'NBCD': OperationType.NEGX,
 'NEG': OperationType.NEG,
 'NEGX': OperationType.NEGX,
 'NOP': None,
 'NOT': OperationType.NOT,
 'OR': OperationType.OR,
 'ORI': OperationType.OR,
 'ORI to CCR': OperationType.CCR_OP,
 'ORI to SR': OperationType.SR_OP,
 'PACK': OperationType.ADD,
 'PBcc': OperationType.SR_OP,
 'PDBcc': OperationType.SR_OP,
 'PEA': OperationType.SUB,
 'PFLUSH': OperationType.SR_OP,
 'PFLUSH PFLUSHA': OperationType.SR_OP,
 'PFLUSHR': OperationType.SR_OP,
 'PLOAD': OperationType.SR_OP,
 'PMOVE': OperationType.SR_OP,
 'PRESTORE': OperationType.SR_OP,
 'PSAVE': OperationType.SR_OP,
 'PScc': OperationType.SR_OP,
 'PTEST': OperationType.SR_OP,
 'PTRAPcc': OperationType.SR_OP,
 'PVALID': OperationType.MOVE,
 'RESET': OperationType.SR_OP,
 'ROL, ROR': OperationType.ROTATE,
 'ROXL, ROXR': OperationType.ROTATE_EXTEND,
 'RTD': OperationType.ADD,
 'RTE': OperationType.SR_OP,
 'RTM': None,
 'RTR': OperationType.CCR_OP,
 'RTS': OperationType.ADD,
 'SBCD': OperationType.SUB_DECIMAL,
 'STOP': OperationType.SR_OP,
 'SUB': OperationType.SUB,
 'SUBA': OperationType.SUB,
 'SUBI': OperationType.SUB,
 'SUBQ': OperationType.SUB,
 'SUBX': OperationType.SUBX,
 'SWAP': OperationType.SWAP,
 'Scc': None,
 'TAS': OperationType.TEST,
 'TRAP': OperationType.MOVE,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': OperationType.TEST,
 'UNLK': OperationType.ADD,
 'UNPK': OperationType.ADD,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': OperationType.SR_OP,
 'cpSAVE': OperationType.SR_OP,
 'cpScc': None,
 'cpTRAPcc': None}
OPERATION_CLASSES = {'ABCD': None,
 'ADD': None,
 'ADDA': None,
 'ADDI': None,
 'ADDQ': None,
 'ADDX': None,
 'AND': None,
 'ANDI': None,
 'ANDI to CCR': None,
 'ANDI to SR': None,
 'ASL, ASR': None,
 'BCHG': None,
 'BCLR': None,
 'BFCHG': None,
 'BFCLR': None,
 'BFEXTS': None,
 'BFEXTU': None,
 'BFFFO': None,
 'BFINS': None,
 'BFSET': None,
 'BFTST': None,
 'BKPT': None,
 'BRA': None,
 'BSET': None,
 'BSR': None,
 'BTST': None,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': None,
 'CHK': None,
 'CHK2': None,
 'CINV': None,
 'CLR': None,
 'CMP': None,
 'CMP2': None,
 'CMPA': None,
 'CMPI': None,
 'CMPM': None,
 'CPUSH': None,
 'DBcc': None,
 'DIVS, DIVSL': None,
 'DIVU, DIVUL': None,
 'EOR': None,
 'EORI': None,
 'EORI to CCR': None,
 'EORI to SR': None,
 'EXG': None,
 'EXT, EXTB': None,
 'FRESTORE': None,
 'FSAVE': None,
 'ILLEGAL': None,
 'JMP': None,
 'JSR': None,
 'LEA': OperationClass.LOAD_EFFECTIVE_ADDRESS,
 'LINK': None,
 'LSL, LSR': None,
 'MOVE': None,
 'MOVE USP': None,
 'MOVE from CCR': None,
 'MOVE from SR': None,
 'MOVE to CCR': None,
 'MOVE to SR': None,
 'MOVE16': None,
 'MOVEA': None,
 'MOVEC': None,
 'MOVEM': OperationClass.MULTI_REGISTER_TRANSFER,
 'MOVEP': None,
 'MOVEQ': None,
 'MOVES': None,
 'MULS': None,
 'MULU': None,
 'NBCD': None,
 'NEG': None,
 'NEGX': None,
 'NOP': None,
 'NOT': None,
 'OR': None,
 'ORI': None,
 'ORI to CCR': None,
 'ORI to SR': None,
 'PACK': None,
 'PBcc': None,
 'PDBcc': None,
 'PEA': None,
 'PFLUSH': None,
 'PFLUSH PFLUSHA': None,
 'PFLUSHR': None,
 'PLOAD': None,
 'PMOVE': None,
 'PRESTORE': None,
 'PSAVE': None,
 'PScc': None,
 'PTEST': None,
 'PTRAPcc': None,
 'PVALID': None,
 'RESET': None,
 'ROL, ROR': None,
 'ROXL, ROXR': None,
 'RTD': None,
 'RTE': None,
 'RTM': None,
 'RTR': None,
 'RTS': None,
 'SBCD': None,
 'STOP': None,
 'SUB': None,
 'SUBA': None,
 'SUBI': None,
 'SUBQ': None,
 'SUBX': None,
 'SWAP': None,
 'Scc': None,
 'TAS': None,
 'TRAP': None,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': None,
 'UNLK': None,
 'UNPK': None,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': None,
 'cpSAVE': None,
 'cpScc': None,
 'cpTRAPcc': None}
SOURCE_SIGN_EXTEND = ('ADDA', 'CMPA', 'MOVEA', 'SUBA')
SHIFT_COUNT_MODULI = {'ASL, ASR': 64, 'LSL, LSR': 64, 'ROL, ROR': 64, 'ROXL, ROXR': 64}
PROCESSOR_MINS = {'abcd': '68000',
 'add': '68000',
 'adda': '68000',
 'addi': '68000',
 'addq': '68000',
 'addx': '68000',
 'and': '68000',
 'andi': '68000',
 'asl': '68000',
 'asr': '68000',
 'bcc': '68000',
 'bchg': '68000',
 'bclr': '68000',
 'bfchg': '68020',
 'bfclr': '68020',
 'bfexts': '68020',
 'bfextu': '68020',
 'bfffo': '68020',
 'bfins': '68020',
 'bfset': '68020',
 'bftst': '68020',
 'bkpt': '68000',
 'bra': '68000',
 'bset': '68000',
 'bsr': '68000',
 'btst': '68000',
 'callm': '68020',
 'cas': '68020',
 'cas2': '68020',
 'ccr': '68000',
 'chk': '68000',
 'chk2': '68020',
 'cinv': '68040',
 'clr': '68000',
 'cmp': '68000',
 'cmp2': '68020',
 'cmpa': '68000',
 'cmpi': '68000',
 'cmpm': '68000',
 'cpbcc': '68020',
 'cpdbcc': '68020',
 'cpgen': '68020',
 'cprestore': '68020',
 'cpsave': '68020',
 'cpscc': '68020',
 'cptrapcc': '68020',
 'cpush': '68040',
 'dbcc': '68000',
 'divs': '68000',
 'divsl': '68000',
 'divu': '68000',
 'divul': '68000',
 'eor': '68000',
 'eori': '68000',
 'exg': '68000',
 'ext': '68000',
 'extb': '68000',
 'frestore': '68020',
 'from': '68000',
 'fsave': '68020',
 'illegal': '68000',
 'jmp': '68000',
 'jsr': '68000',
 'lea': '68000',
 'link': '68000',
 'lsl': '68000',
 'lsr': '68000',
 'move': '68000',
 'move16': '68040',
 'movea': '68000',
 'movec': '68010',
 'movem': '68000',
 'movep': '68000',
 'moveq': '68000',
 'moves': '68010',
 'muls': '68000',
 'mulu': '68000',
 'nbcd': '68000',
 'neg': '68000',
 'negx': '68000',
 'nop': '68000',
 'not': '68000',
 'or': '68000',
 'ori': '68000',
 'pack': '68020',
 'pbcc': '68020',
 'pdbcc': '68020',
 'pea': '68000',
 'pflush': '68020',
 'pflusha': '68020',
 'pflushr': '68020',
 'pload': '68020',
 'pmove': '68030',
 'prestore': '68020',
 'psave': '68020',
 'pscc': '68020',
 'ptest': '68030',
 'ptrapcc': '68000',
 'pvalid': '68020',
 'reset': '68000',
 'rol': '68000',
 'ror': '68000',
 'roxl': '68000',
 'roxr': '68000',
 'rtd': '68010',
 'rte': '68000',
 'rtm': '68020',
 'rtr': '68000',
 'rts': '68000',
 'sbcd': '68000',
 'scc': '68000',
 'sr': '68000',
 'stop': '68000',
 'sub': '68000',
 'suba': '68000',
 'subi': '68000',
 'subq': '68000',
 'subx': '68000',
 'swap': '68000',
 'tas': '68000',
 'to': '68000',
 'trap': '68000',
 'trapcc': '68020',
 'trapv': '68000',
 'tst': '68000',
 'unlk': '68000',
 'unpk': '68020',
 'usp': '68000'}
OPMODE_TABLES_BY_VALUE = {'ADD': {0: ('b', '< ea > + Dn → Dn', True, None, None, None, None),
         1: ('w', '< ea > + Dn → Dn', True, None, None, None, None),
         2: ('l', '< ea > + Dn → Dn', True, None, None, None, None),
         4: ('b', 'Dn + < ea > → < ea >', False, None, None, None, None),
         5: ('w', 'Dn + < ea > → < ea >', False, None, None, None, None),
         6: ('l', 'Dn + < ea > → < ea >', False, None, None, None, None)},
 'ADDA': {3: ('w',
              'Word operation; the source operand is sign-extended to a long operand and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'AND': {0: ('b', '< ea > Dn → Dn', True, None, None, None, None),
         1: ('w', '< ea > Dn → Dn', True, None, None, None, None),
         2: ('l', '< ea > Dn → Dn', True, None, None, None, None),
         4: ('b', 'Dn Λ < ea > → < ea >', False, None, None, None, None),
         5: ('w', 'Dn Λ < ea > → < ea >', False, None, None, None, None),
         6: ('l', 'Dn Λ < ea > → < ea >', False, None, None, None, None)},
 'CMP': {0: ('b', 'Dn – < ea >', True, None, None, None, None),
         1: ('w', 'Dn – < ea >', True, None, None, None, None),
         2: ('l', 'Dn – < ea >', True, None, None, None, None)},
 'CMPA': {3: ('w',
              'Word operation; the source operand is sign-extended to a long operand, and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'EOR': {4: ('b', '< ea > ⊕ Dn → < ea >', False, None, None, None, None),
         5: ('w', '< ea > ⊕ Dn → < ea >', False, None, None, None, None),
         6: ('l', '< ea > ⊕ Dn → < ea >', False, None, None, None, None)},
 'EXG': {8: (None, 'Data registers', None, None, None, 'dn', 'dn'),
         9: (None, 'Address registers', None, None, None, 'an', 'an'),
         17: (None, 'Data register and address register', None, None, None, 'dn', 'an')},
 'EXT, EXTB': {2: ('b',
                   'Sign-extend low-order byte of data register to word',
                   None,
                   None,
                   None,
                   None,
                   None),
               3: ('w',
                   'Sign-extend low-order word of data register to long',
                   None,
                   None,
                   None,
                   None,
                   None),
               7: ('b',
                   'Sign-extend low-order byte of data register to long',
                   None,
                   None,
                   None,
                   None,
                   None)},
 'MOVE16': {0: (None, None, None, '(Ay) +', '(xxx).L', None, None),
            1: (None, None, None, '(xxx).L', '(Ay) +', None, None),
            2: (None, None, None, '(Ay)', '(xxx).L', None, None),
            3: (None, None, None, '(xxx).L', '(Ay)', None, None)},
 'MOVEP': {4: ('w', 'Transfer word from memory to register', None, None, None, None, None),
           5: ('l', 'Transfer long from memory to register', None, None, None, None, None),
           6: ('w', 'Transfer word from register to memory', None, None, None, None, None),
           7: ('l', 'Transfer long from register to memory', None, None, None, None, None)},
 'OR': {0: ('b', '< ea > V Dn → Dn', True, None, None, None, None),
        1: ('w', '< ea > V Dn → Dn', True, None, None, None, None),
        2: ('l', '< ea > V Dn → Dn', True, None, None, None, None),
        4: ('b', 'Dn V < ea > → < ea >', False, None, None, None, None),
        5: ('w', 'Dn V < ea > → < ea >', False, None, None, None, None),
        6: ('l', 'Dn V < ea > → < ea >', False, None, None, None, None)},
 'PTRAPcc': {2: ('w', 'Instruction is followed by one operand word', None, None, None, None, None),
             3: ('l', 'Instruction is followed by two operand words', None, None, None, None, None),
             4: (None, 'Instruction has no following operand words', None, None, None, None, None)},
 'SUB': {0: ('b', 'Dn – < ea > → Dn', True, None, None, None, None),
         1: ('w', 'Dn – < ea > → Dn', True, None, None, None, None),
         2: ('l', 'Dn – < ea > → Dn', True, None, None, None, None),
         4: ('b', '< ea > – Dn → < ea >', False, None, None, None, None),
         5: ('w', '< ea > – Dn → < ea >', False, None, None, None, None),
         6: ('l', '< ea > – Dn → < ea >', False, None, None, None, None)},
 'SUBA': {3: ('w',
              'Word operation. The source operand is sign-extended to a long operand and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'TRAPcc': {2: ('w', 'Instruction is followed by word-sized operand', None, None, None, None, None),
            3: ('l',
                'Instruction is followed by long-word-sized operand',
                None,
                None,
                None,
                None,
                None),
            4: (None, 'Instruction has no operand', None, None, None, None, None)}}
CONDITION_FAMILIES = (('b',
  'bcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ('f', 't')),
 ('cpb',
  'cpbcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('cpdb',
  'cpdbcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('cps',
  'cpscc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('cptrap',
  'cptrapcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('db',
  'dbcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('pb',
  'pbcc',
  ('bs', 'bc', 'ls', 'lc', 'ss', 'sc', 'as', 'ac', 'ws', 'wc', 'is', 'ic', 'gs', 'gc', 'cs', 'cc'),
  True,
  ()),
 ('pdb',
  'pdbcc',
  ('bs', 'bc', 'ls', 'lc', 'ss', 'sc', 'as', 'ac', 'ws', 'wc', 'is', 'ic', 'gs', 'gc', 'cs', 'cc'),
  True,
  ()),
 ('ps',
  'pscc',
  ('bs', 'bc', 'ls', 'lc', 'ss', 'sc', 'as', 'ac', 'ws', 'wc', 'is', 'ic', 'gs', 'gc', 'cs', 'cc'),
  True,
  ()),
 ('ptrap',
  'ptrapcc',
  ('bs', 'bc', 'ls', 'lc', 'ss', 'sc', 'as', 'ac', 'ws', 'wc', 'is', 'ic', 'gs', 'gc', 'cs', 'cc'),
  True,
  ()),
 ('s',
  'scc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()),
 ('trap',
  'trapcc',
  ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le'),
  False,
  ()))
CONDITION_CODES = ('t', 'f', 'hi', 'ls', 'cc', 'cs', 'ne', 'eq', 'vc', 'vs', 'pl', 'mi', 'ge', 'lt', 'gt', 'le')
CPU_HIERARCHY = {'order': ['68000', '68010', '68020', '68030', '68040', '68060'],
 'aliases': {'68020up': '68020', 'cf': '68060', 'cfpu': '68060', 'cpu32': '68020'}}
PMMU_CONDITION_CODES = ('bs', 'bc', 'ls', 'lc', 'ss', 'sc', 'as', 'ac', 'ws', 'wc', 'is', 'ic', 'gs', 'gc', 'cs', 'cc')
DEFAULT_OPERAND_SIZE = 'w'
MOVE_FIELDS = ((11, 9, 3), (8, 6, 3), (5, 3, 3), (2, 0, 3))
CPID_FIELD = (9, 3)
