"""Generated runtime Amiga hardware artifact. Do not edit directly."""

from __future__ import annotations

from .runtime_types import HardwareRegisterDef

META = {'source': 'NDK hardware includes',
 'include_dir': 'hardware/',
 'files': {'custom': {'path': 'hardware/custom.i', 'version': 'custom.i 39.1 (18.9.92)'},
           'cia': {'path': 'hardware/cia.i', 'version': 'cia.i 39.1 (18.9.92)'}}}
REGISTER_DEFS: dict[int, HardwareRegisterDef] = {14675968: {'symbol': 'bltddat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 0},
 14675970: {'symbol': 'dmaconr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 2},
 14675972: {'symbol': 'vposr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 4},
 14675974: {'symbol': 'vhposr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 6},
 14675976: {'symbol': 'dskdatr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 8},
 14675978: {'symbol': 'joy0dat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 10},
 14675980: {'symbol': 'joy1dat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 12},
 14675982: {'symbol': 'clxdat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 14},
 14675984: {'symbol': 'adkconr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 16},
 14675986: {'symbol': 'pot0dat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 18},
 14675988: {'symbol': 'pot1dat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 20},
 14675990: {'symbol': 'potinp',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 22},
 14675992: {'symbol': 'serdatr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 24},
 14675994: {'symbol': 'dskbytr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 26},
 14675996: {'symbol': 'intenar',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 28},
 14675998: {'symbol': 'intreqr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 30},
 14676000: {'symbol': 'dskpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 32},
 14676004: {'symbol': 'dsklen',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 36},
 14676006: {'symbol': 'dskdat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 38},
 14676008: {'symbol': 'refptr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 40},
 14676010: {'symbol': 'vposw',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 42},
 14676012: {'symbol': 'vhposw',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 44},
 14676014: {'symbol': 'copcon',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 46},
 14676016: {'symbol': 'serdat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 48},
 14676018: {'symbol': 'serper',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 50},
 14676020: {'symbol': 'potgo',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 52},
 14676022: {'symbol': 'joytest',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 54},
 14676024: {'symbol': 'strequ',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 56},
 14676026: {'symbol': 'strvbl',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 58},
 14676028: {'symbol': 'strhor',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 60},
 14676030: {'symbol': 'strlong',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 62},
 14676032: {'symbol': 'bltcon0',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 64},
 14676034: {'symbol': 'bltcon1',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 66},
 14676036: {'symbol': 'bltafwm',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 68},
 14676038: {'symbol': 'bltalwm',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 70},
 14676040: {'symbol': 'bltcpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 72},
 14676044: {'symbol': 'bltbpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 76},
 14676048: {'symbol': 'bltapt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 80},
 14676052: {'symbol': 'bltdpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 84},
 14676056: {'symbol': 'bltsize',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 88},
 14676059: {'symbol': 'bltcon0l',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 91},
 14676060: {'symbol': 'bltsizv',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 92},
 14676062: {'symbol': 'bltsizh',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 94},
 14676064: {'symbol': 'bltcmod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 96},
 14676066: {'symbol': 'bltbmod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 98},
 14676068: {'symbol': 'bltamod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 100},
 14676070: {'symbol': 'bltdmod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 102},
 14676080: {'symbol': 'bltcdat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 112},
 14676082: {'symbol': 'bltbdat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 114},
 14676084: {'symbol': 'bltadat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 116},
 14676092: {'symbol': 'deniseid',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 124},
 14676094: {'symbol': 'dsksync',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 126},
 14676096: {'symbol': 'cop1lc',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 128},
 14676100: {'symbol': 'cop2lc',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 132},
 14676104: {'symbol': 'copjmp1',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 136},
 14676106: {'symbol': 'copjmp2',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 138},
 14676108: {'symbol': 'copins',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 140},
 14676110: {'symbol': 'diwstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 142},
 14676112: {'symbol': 'diwstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 144},
 14676114: {'symbol': 'ddfstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 146},
 14676116: {'symbol': 'ddfstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 148},
 14676118: {'symbol': 'dmacon',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 150},
 14676120: {'symbol': 'clxcon',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 152},
 14676122: {'symbol': 'intena',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 154},
 14676124: {'symbol': 'intreq',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 156},
 14676126: {'symbol': 'adkcon',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 158},
 14676128: {'symbol': 'aud0',
            'aliases': ('aud',),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 160},
 14676144: {'symbol': 'aud1',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 176},
 14676160: {'symbol': 'aud2',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 192},
 14676176: {'symbol': 'aud3',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 208},
 14676192: {'symbol': 'bplpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 224},
 14676224: {'symbol': 'bplcon0',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 256},
 14676226: {'symbol': 'bplcon1',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 258},
 14676228: {'symbol': 'bplcon2',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 260},
 14676230: {'symbol': 'bplcon3',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 262},
 14676232: {'symbol': 'bpl1mod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 264},
 14676234: {'symbol': 'bpl2mod',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 266},
 14676236: {'symbol': 'bplcon4',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 268},
 14676238: {'symbol': 'clxcon2',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 270},
 14676240: {'symbol': 'bpldat',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 272},
 14676256: {'symbol': 'sprpt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 288},
 14676288: {'symbol': 'spr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 320},
 14676352: {'symbol': 'color',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 384},
 14676416: {'symbol': 'htotal',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 448},
 14676418: {'symbol': 'hsstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 450},
 14676420: {'symbol': 'hbstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 452},
 14676422: {'symbol': 'hbstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 454},
 14676424: {'symbol': 'vtotal',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 456},
 14676426: {'symbol': 'vsstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 458},
 14676428: {'symbol': 'vbstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 460},
 14676430: {'symbol': 'vbstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 462},
 14676432: {'symbol': 'sprhstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 464},
 14676434: {'symbol': 'sprhstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 466},
 14676436: {'symbol': 'bplhstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 468},
 14676438: {'symbol': 'bplhstop',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 470},
 14676440: {'symbol': 'hhposw',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 472},
 14676442: {'symbol': 'hhposr',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 474},
 14676444: {'symbol': 'beamcon0',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 476},
 14676446: {'symbol': 'hsstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 478},
 14676448: {'symbol': 'vsstrt',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 480},
 14676450: {'symbol': 'hcenter',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 482},
 14676452: {'symbol': 'diwhigh',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 484},
 14676476: {'symbol': 'fmode',
            'aliases': (),
            'family': 'custom',
            'include': 'hardware/custom.i',
            'base_symbol': '_custom',
            'offset': 508},
 12574721: {'symbol': 'ciapra',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 0},
 12574977: {'symbol': 'ciaprb',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 256},
 12575233: {'symbol': 'ciaddra',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 512},
 12575489: {'symbol': 'ciaddrb',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 768},
 12575745: {'symbol': 'ciatalo',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 1024},
 12576001: {'symbol': 'ciatahi',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 1280},
 12576257: {'symbol': 'ciatblo',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 1536},
 12576513: {'symbol': 'ciatbhi',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 1792},
 12576769: {'symbol': 'ciatodlow',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 2048},
 12577025: {'symbol': 'ciatodmid',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 2304},
 12577281: {'symbol': 'ciatodhi',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 2560},
 12577793: {'symbol': 'ciasdr',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 3072},
 12578049: {'symbol': 'ciaicr',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 3328},
 12578305: {'symbol': 'ciacra',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 3584},
 12578561: {'symbol': 'ciacrb',
            'aliases': (),
            'family': 'ciaa',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciaa',
            'offset': 3840},
 12570624: {'symbol': 'ciapra',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 0},
 12570880: {'symbol': 'ciaprb',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 256},
 12571136: {'symbol': 'ciaddra',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 512},
 12571392: {'symbol': 'ciaddrb',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 768},
 12571648: {'symbol': 'ciatalo',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 1024},
 12571904: {'symbol': 'ciatahi',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 1280},
 12572160: {'symbol': 'ciatblo',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 1536},
 12572416: {'symbol': 'ciatbhi',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 1792},
 12572672: {'symbol': 'ciatodlow',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 2048},
 12572928: {'symbol': 'ciatodmid',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 2304},
 12573184: {'symbol': 'ciatodhi',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 2560},
 12573696: {'symbol': 'ciasdr',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 3072},
 12573952: {'symbol': 'ciaicr',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 3328},
 12574208: {'symbol': 'ciacra',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 3584},
 12574464: {'symbol': 'ciacrb',
            'aliases': (),
            'family': 'ciab',
            'include': 'hardware/cia.i',
            'base_symbol': '_ciab',
            'offset': 3840}}
