"""Generated runtime M68K decode knowledge artifact. Do not edit directly."""

from __future__ import annotations

from enum import StrEnum

from .runtime_types import BitField, OpmodeEntry

class OperationType(StrEnum):
    ADD = 'add'
    ADD_DECIMAL = 'add_decimal'
    ADDX = 'addx'
    AND = 'and'
    BIT_TEST = 'bit_test'
    BITFIELD = 'bitfield'
    BOUNDS_CHECK = 'bounds_check'
    CCR_OP = 'ccr_op'
    CLEAR = 'clear'
    COMPARE = 'compare'
    COMPARE_SWAP = 'compare_swap'
    DIVIDE = 'divide'
    MOVE = 'move'
    MULTIPLY = 'multiply'
    NEG = 'neg'
    NEGX = 'negx'
    NOT = 'not'
    OR = 'or'
    ROTATE = 'rotate'
    ROTATE_EXTEND = 'rotate_extend'
    SHIFT = 'shift'
    SIGN_EXTEND = 'sign_extend'
    SR_OP = 'sr_op'
    SUB = 'sub'
    SUB_DECIMAL = 'sub_decimal'
    SUBX = 'subx'
    SWAP = 'swap'
    TEST = 'test'
    XOR = 'xor'

OPWORD_BYTES = 2
ALIGN_MASK = 1
DEFAULT_OPERAND_SIZE = 'w'
SIZE_BYTE_COUNT: dict[str, int] = {'b': 1, 'w': 2, 'l': 4}
EA_MODE_ENCODING: dict[str, list[int | None]] = {'dn': [0, None],
 'an': [1, None],
 'ind': [2, None],
 'postinc': [3, None],
 'predec': [4, None],
 'disp': [5, None],
 'index': [6, None],
 'absw': [7, 0],
 'absl': [7, 1],
 'pcdisp': [7, 2],
 'pcindex': [7, 3],
 'imm': [7, 4]}
REG_INDIRECT_MODES = ('disp', 'ind', 'index')
MOVEM_REG_MASKS = {'normal': ['d0',
            'd1',
            'd2',
            'd3',
            'd4',
            'd5',
            'd6',
            'd7',
            'a0',
            'a1',
            'a2',
            'a3',
            'a4',
            'a5',
            'a6',
            'a7'],
 'predecrement': ['a7',
                  'a6',
                  'a5',
                  'a4',
                  'a3',
                  'a2',
                  'a1',
                  'a0',
                  'd7',
                  'd6',
                  'd5',
                  'd4',
                  'd3',
                  'd2',
                  'd1',
                  'd0']}
SP_REG_NUM = 7
NUM_DATA_REGS = 8
NUM_ADDR_REGS = 8
EA_BRIEF_FIELDS: dict[str, tuple[int, int, int]] = {'D/A': (15, 15, 1),
 'REGISTER': (14, 12, 3),
 'W/L': (11, 11, 1),
 'SCALE': (10, 9, 2),
 'DISPLACEMENT': (7, 0, 8)}
EA_FULL_FIELDS = {'D/A': (15, 15, 1),
 'REGISTER': (14, 12, 3),
 'W/L': (11, 11, 1),
 'SCALE': (10, 9, 2),
 'BS': (7, 7, 1),
 'IS': (6, 6, 1),
 'BD SIZE': (5, 4, 2),
 'I/IS': (2, 0, 3)}
EA_FULL_BD_SIZE = {'0': 'reserved', '1': 'null', '2': 'word', '3': 'long'}
ENCODING_COUNTS: dict[str, int] = {'ABCD': 1,
 'ADD': 1,
 'ADDA': 1,
 'ADDI': 1,
 'ADDQ': 1,
 'ADDX': 1,
 'AND': 1,
 'ANDI': 1,
 'ANDI to CCR': 1,
 'ANDI to SR': 1,
 'ASL, ASR': 2,
 'BCHG': 3,
 'BCLR': 3,
 'BFCHG': 2,
 'BFCLR': 2,
 'BFEXTS': 2,
 'BFEXTU': 2,
 'BFFFO': 2,
 'BFINS': 2,
 'BFSET': 2,
 'BFTST': 2,
 'BKPT': 1,
 'BRA': 1,
 'BSET': 3,
 'BSR': 1,
 'BTST': 3,
 'Bcc': 1,
 'CALLM': 2,
 'CAS CAS2': 5,
 'CHK': 1,
 'CHK2': 2,
 'CINV': 1,
 'CLR': 1,
 'CMP': 1,
 'CMP2': 2,
 'CMPA': 1,
 'CMPI': 1,
 'CMPM': 1,
 'CPUSH': 1,
 'DBcc': 2,
 'DIVS, DIVSL': 3,
 'DIVU, DIVUL': 3,
 'EOR': 1,
 'EORI': 1,
 'EORI to CCR': 1,
 'EORI to SR': 1,
 'EXG': 1,
 'EXT, EXTB': 1,
 'FRESTORE': 1,
 'FSAVE': 1,
 'ILLEGAL': 1,
 'JMP': 1,
 'JSR': 1,
 'LEA': 1,
 'LINK': 5,
 'LSL, LSR': 2,
 'MOVE': 1,
 'MOVE USP': 1,
 'MOVE from CCR': 1,
 'MOVE from SR': 1,
 'MOVE to CCR': 1,
 'MOVE to SR': 1,
 'MOVE16': 5,
 'MOVEA': 1,
 'MOVEC': 2,
 'MOVEM': 1,
 'MOVEP': 2,
 'MOVEQ': 1,
 'MOVES': 2,
 'MULS': 3,
 'MULU': 3,
 'NBCD': 1,
 'NEG': 1,
 'NEGX': 1,
 'NOP': 1,
 'NOT': 1,
 'OR': 1,
 'ORI': 1,
 'ORI to CCR': 1,
 'ORI to SR': 1,
 'PACK': 1,
 'PBcc': 1,
 'PDBcc': 3,
 'PEA': 1,
 'PFLUSH': 4,
 'PFLUSH PFLUSHA': 2,
 'PFLUSHR': 2,
 'PLOAD': 2,
 'PMOVE': 16,
 'PRESTORE': 1,
 'PSAVE': 1,
 'PScc': 2,
 'PTEST': 8,
 'PTRAPcc': 2,
 'PVALID': 4,
 'RESET': 1,
 'ROL, ROR': 2,
 'ROXL, ROXR': 2,
 'RTD': 2,
 'RTE': 1,
 'RTM': 1,
 'RTR': 1,
 'RTS': 1,
 'SBCD': 1,
 'STOP': 2,
 'SUB': 1,
 'SUBA': 1,
 'SUBI': 1,
 'SUBQ': 1,
 'SUBX': 1,
 'SWAP': 1,
 'Scc': 1,
 'TAS': 1,
 'TRAP': 1,
 'TRAPV': 1,
 'TRAPcc': 2,
 'TST': 1,
 'UNLK': 1,
 'UNPK': 1,
 'cpBcc': 1,
 'cpDBcc': 2,
 'cpGEN': 2,
 'cpRESTORE': 1,
 'cpSAVE': 1,
 'cpScc': 2,
 'cpTRAPcc': 2}
ENCODING_MASKS: tuple[dict[str, tuple[int, int]], ...] = ({'ABCD': (61936, 49408),
  'ADD': (61440, 53248),
  'ADDA': (61440, 53248),
  'ADDI': (65280, 1536),
  'ADDQ': (61696, 20480),
  'ADDX': (61744, 53504),
  'AND': (61440, 49152),
  'ANDI': (65280, 512),
  'ANDI to CCR': (65535, 572),
  'ANDI to SR': (65535, 636),
  'ASL, ASR': (61464, 57344),
  'BCHG': (61888, 320),
  'BCLR': (61888, 384),
  'BFCHG': (65472, 60096),
  'BFCLR': (65472, 60608),
  'BFEXTS': (65472, 60352),
  'BFEXTU': (65472, 59840),
  'BFFFO': (65472, 60864),
  'BFINS': (65472, 61376),
  'BFSET': (65472, 61120),
  'BFTST': (65472, 59584),
  'BKPT': (65528, 18504),
  'BRA': (65280, 24576),
  'BSET': (61888, 448),
  'BSR': (65280, 24832),
  'BTST': (61888, 256),
  'Bcc': (61440, 24576),
  'CALLM': (65472, 1728),
  'CAS CAS2': (63936, 2240),
  'CHK': (61504, 16384),
  'CHK2': (63936, 192),
  'CINV': (65312, 62464),
  'CLR': (65280, 16896),
  'CMP': (61440, 45056),
  'CMP2': (63936, 192),
  'CMPA': (61440, 45056),
  'CMPI': (65280, 3072),
  'CMPM': (61752, 45320),
  'CPUSH': (65312, 62496),
  'DBcc': (61688, 20680),
  'DIVS, DIVSL': (61888, 33216),
  'DIVU, DIVUL': (61888, 32960),
  'EOR': (61440, 45056),
  'EORI': (65280, 2560),
  'EORI to CCR': (65535, 2620),
  'EORI to SR': (65535, 2684),
  'EXG': (61696, 49408),
  'EXT, EXTB': (65080, 18432),
  'FRESTORE': (61888, 61760),
  'FSAVE': (61888, 61696),
  'ILLEGAL': (65535, 19196),
  'JMP': (65472, 20160),
  'JSR': (65472, 20096),
  'LEA': (61888, 16832),
  'LINK': (65528, 20048),
  'LSL, LSR': (61464, 57352),
  'MOVE': (49152, 0),
  'MOVE USP': (65520, 20064),
  'MOVE from CCR': (65472, 17088),
  'MOVE from SR': (65472, 16576),
  'MOVE to CCR': (65472, 17600),
  'MOVE to SR': (65472, 18112),
  'MOVE16': (65528, 63008),
  'MOVEA': (49600, 64),
  'MOVEC': (65534, 20090),
  'MOVEM': (64384, 18560),
  'MOVEP': (61496, 8),
  'MOVEQ': (61696, 28672),
  'MOVES': (65280, 3584),
  'MULS': (61888, 49600),
  'MULU': (61888, 49344),
  'NBCD': (65472, 18432),
  'NEG': (65280, 17408),
  'NEGX': (65280, 16384),
  'NOP': (65535, 20081),
  'NOT': (65280, 17920),
  'OR': (61440, 32768),
  'ORI': (65280, 0),
  'ORI to CCR': (65535, 60),
  'ORI to SR': (65535, 124),
  'PACK': (61936, 33088),
  'PBcc': (65408, 61568),
  'PDBcc': (65528, 61512),
  'PEA': (65472, 18496),
  'PFLUSH': (65472, 61440),
  'PFLUSH PFLUSHA': (65472, 61440),
  'PFLUSHR': (65472, 61440),
  'PLOAD': (65472, 61440),
  'PMOVE': (65472, 61440),
  'PRESTORE': (65472, 61760),
  'PSAVE': (65472, 61696),
  'PScc': (65472, 61504),
  'PTEST': (65472, 61440),
  'PTRAPcc': (65528, 61560),
  'PVALID': (65472, 61440),
  'RESET': (65535, 20080),
  'ROL, ROR': (61464, 57368),
  'ROXL, ROXR': (61464, 57360),
  'RTD': (65535, 20084),
  'RTE': (65535, 20083),
  'RTM': (65520, 1728),
  'RTR': (65535, 20087),
  'RTS': (65535, 20085),
  'SBCD': (61936, 33024),
  'STOP': (65535, 20082),
  'SUB': (61440, 36864),
  'SUBA': (61440, 36864),
  'SUBI': (65280, 1024),
  'SUBQ': (61696, 20736),
  'SUBX': (61744, 37120),
  'SWAP': (65528, 18496),
  'Scc': (61632, 20672),
  'TAS': (65472, 19136),
  'TRAP': (65520, 20032),
  'TRAPV': (65535, 20086),
  'TRAPcc': (61688, 20728),
  'TST': (65280, 18944),
  'UNLK': (65528, 20056),
  'UNPK': (61936, 33152),
  'cpBcc': (0, 0),
  'cpDBcc': (0, 0),
  'cpGEN': (0, 0),
  'cpRESTORE': (61888, 61760),
  'cpSAVE': (61888, 61696),
  'cpScc': (61888, 61504),
  'cpTRAPcc': (0, 0)},
 {'ASL, ASR': (65216, 57536),
  'BCHG': (65472, 2112),
  'BCLR': (65472, 2176),
  'BFCHG': (61440, 0),
  'BFCLR': (61440, 0),
  'BFEXTS': (32768, 0),
  'BFEXTU': (32768, 0),
  'BFFFO': (32768, 0),
  'BFINS': (32768, 0),
  'BFSET': (61440, 0),
  'BFTST': (61440, 0),
  'BSET': (65472, 2240),
  'BTST': (65472, 2048),
  'CALLM': (65280, 0),
  'CAS CAS2': (65080, 0),
  'CHK2': (4095, 2048),
  'CMP2': (4095, 0),
  'DBcc': (0, 0),
  'DIVS, DIVSL': (65472, 19520),
  'DIVU, DIVUL': (65472, 19520),
  'LINK': (0, 0),
  'LSL, LSR': (65216, 58048),
  'MOVE16': (36863, 32768),
  'MOVEC': (0, 0),
  'MOVEP': (0, 0),
  'MOVES': (2047, 0),
  'MULS': (65472, 19456),
  'MULU': (65472, 19456),
  'PDBcc': (65472, 0),
  'PFLUSH': (58112, 8192),
  'PFLUSH PFLUSHA': (57856, 8192),
  'PFLUSHR': (65535, 40960),
  'PLOAD': (64992, 8192),
  'PMOVE': (57599, 16384),
  'PScc': (65472, 0),
  'PTEST': (57344, 32768),
  'PTRAPcc': (65472, 0),
  'PVALID': (65535, 10240),
  'ROL, ROR': (65216, 59072),
  'ROXL, ROXR': (65216, 58560),
  'RTD': (0, 0),
  'STOP': (0, 0),
  'TRAPcc': (0, 0),
  'cpDBcc': (65472, 0),
  'cpGEN': (0, 0),
  'cpScc': (65472, 0),
  'cpTRAPcc': (65472, 0)},
 {'BCHG': (65280, 0),
  'BCLR': (65280, 0),
  'BSET': (65024, 0),
  'BTST': (65280, 0),
  'CAS CAS2': (63999, 2300),
  'DIVS, DIVSL': (35832, 2048),
  'DIVU, DIVUL': (35832, 0),
  'LINK': (65528, 18440),
  'MOVE16': (65504, 62976),
  'MULS': (35832, 2048),
  'MULU': (35832, 0),
  'PDBcc': (0, 0),
  'PFLUSH': (65504, 62720),
  'PMOVE': (65472, 61440),
  'PTEST': (65472, 61440),
  'PVALID': (65472, 61440)},
 {'CAS CAS2': (3640, 0),
  'LINK': (0, 0),
  'MOVE16': (0, 0),
  'PFLUSH': (65504, 62720),
  'PMOVE': (65023, 24576),
  'PTEST': (64768, 32768),
  'PVALID': (65528, 10240)},
 {'CAS CAS2': (3640, 0),
  'LINK': (0, 0),
  'MOVE16': (0, 0),
  'PMOVE': (65472, 61440),
  'PTEST': (65496, 62792)},
 {'PMOVE': (57599, 0), 'PTEST': (65496, 62792)},
 {'PMOVE': (65472, 61440), 'PTEST': (65472, 61440)},
 {'PMOVE': (65023, 24576), 'PTEST': (57344, 32768)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 0)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 16384)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57827, 24576)},
 {'PMOVE': (65472, 61440)},
 {'PMOVE': (57855, 24576)})
FIELD_MAPS = ({'ABCD': {'REGISTER Rx': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Ry': (2, 0, 3)},
  'ADD': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDX': {'REGISTER Rx': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Ry': (2, 0, 3)},
  'AND': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ANDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ANDI to CCR': {},
  'ANDI to SR': {},
  'ASL, ASR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'BCHG': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BCLR': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BFCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFFFO': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFINS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BKPT': {'VECTOR': (2, 0, 3)},
  'BRA': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BSET': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BSR': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BTST': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'Bcc': {'CONDITION': (11, 8, 4), '8-BIT DISPLACEMENT': (7, 0, 8)},
  'CALLM': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CAS CAS2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CHK': {'REGISTER': (2, 0, 3), 'SIZE': (8, 7, 2), 'MODE': (5, 3, 3)},
  'CHK2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CINV': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'CLR': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMP': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMP2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMPI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPM': {'REGISTER Ax': (11, 9, 3), 'SIZE': (7, 6, 2), 'REGISTER Ay': (2, 0, 3)},
  'CPUSH': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'DBcc': {'CONDITION': (11, 8, 4), 'REGISTER': (2, 0, 3)},
  'DIVS, DIVSL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'DIVU, DIVUL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'EOR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'EORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'EORI to CCR': {},
  'EORI to SR': {},
  'EXG': {'REGISTER Rx': (11, 9, 3), 'OPMODE': (7, 3, 5), 'REGISTER Ry': (2, 0, 3)},
  'EXT, EXTB': {'OPMODE': (8, 6, 3), 'REGISTER': (2, 0, 3)},
  'FRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'FSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ILLEGAL': {},
  'JMP': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'JSR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LEA': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'LSL, LSR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'MOVE': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVE USP': {'dr': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'MOVE from CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE from SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ax': (2, 0, 3)},
  'MOVEA': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVEC': {'dr': (0, 0, 1)},
  'MOVEM': {'dr': (10, 10, 1), 'SIZE': (6, 6, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVEP': {'DATA REGISTER': (11, 9, 3), 'OPMODE': (8, 6, 3), 'ADDRESS REGISTER': (2, 0, 3)},
  'MOVEQ': {'REGISTER': (11, 9, 3), 'DATA': (7, 0, 8)},
  'MOVES': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULS': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MULU': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'NBCD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEG': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEGX': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NOP': {},
  'NOT': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'OR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ORI to CCR': {},
  'ORI to SR': {},
  'PACK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'PBcc': {'SIZE': (6, 6, 1), 'MC68851 CONDITION': (5, 0, 6)},
  'PDBcc': {'COUNT REGISTER': (2, 0, 3)},
  'PEA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH PFLUSHA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSHR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PLOAD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PRESTORE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PSAVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PScc': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTRAPcc': {'OPMODE': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'RESET': {},
  'ROL, ROR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'ROXL, ROXR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'RTD': {},
  'RTE': {},
  'RTM': {'D/A': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'RTR': {},
  'RTS': {},
  'SBCD': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'STOP': {},
  'SUB': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBX': {'REGISTER Dy/Ay': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Dx/Ax': (2, 0, 3)},
  'SWAP': {'REGISTER': (2, 0, 3)},
  'Scc': {'CONDITION': (11, 8, 4), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TAS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TRAP': {'VECTOR': (3, 0, 4)},
  'TRAPV': {},
  'TRAPcc': {'CONDITION': (11, 8, 4), 'OPMODE': (2, 0, 3)},
  'TST': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'UNLK': {'REGISTER': (2, 0, 3)},
  'UNPK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'cpBcc': {'ID': (15, 0, 16)},
  'cpDBcc': {'ID': (15, 0, 16)},
  'cpGEN': {'ID': (15, 0, 16)},
  'cpRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpScc': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpTRAPcc': {'ID': (15, 0, 16)}},
 {'ASL, ASR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCHG': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFCLR': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFEXTS': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFEXTU': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFFFO': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFINS': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFSET': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFTST': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CALLM': {'ARGUMENT COUNT': (7, 0, 8)},
  'CAS CAS2': {'Du': (8, 6, 3), 'Dc': (2, 0, 3)},
  'CHK2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'CMP2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'DBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'DIVS, DIVSL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'DIVU, DIVUL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LINK': {'WORD DISPLACEMENT': (15, 0, 16)},
  'LSL, LSR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ay': (14, 12, 3)},
  'MOVEC': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'CONTROL REGISTER': (11, 0, 12)},
  'MOVEP': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'MOVES': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'dr': (11, 11, 1)},
  'MULS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PDBcc': {'MC68851 CONDITION': (5, 0, 6)},
  'PFLUSH': {'MODE': (12, 10, 3), 'MASK': (7, 4, 4), 'FC': (3, 0, 4)},
  'PFLUSH PFLUSHA': {'MODE': (12, 10, 3), 'MASK': (7, 5, 3), 'FC': (3, 0, 4)},
  'PFLUSHR': {},
  'PLOAD': {'R/ W': (9, 9, 1), 'FC': (4, 0, 5)},
  'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PScc': {'MC68851 CONDITION': (5, 0, 6)},
  'PTEST': {'LEVEL': (12, 10, 3),
            'R/ W': (9, 9, 1),
            'A': (8, 8, 1),
            'REGISTER': (7, 3, 5),
            'FC': (2, 0, 3)},
  'PTRAPcc': {'MC68851 CONDITION': (5, 0, 6)},
  'PVALID': {},
  'ROL, ROR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ROXL, ROXR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'RTD': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'STOP': {'IMMEDIATE DATA': (15, 0, 16)},
  'TRAPcc': {'OPTIONAL WORD': (15, 0, 16)},
  'cpDBcc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpGEN': {'MODE': (15, 3, 13), 'REGISTER': (2, 0, 3)},
  'cpScc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpTRAPcc': {'COPROCESSOR CONDITION': (5, 0, 6)}},
 {'BCHG': {'BIT NUMBER': (7, 0, 8)},
  'BCLR': {'BIT NUMBER': (7, 0, 8)},
  'BSET': {'BIT NUMBER': (8, 0, 9)},
  'BTST': {'BIT NUMBER': (7, 0, 8)},
  'CAS CAS2': {'SIZE': (10, 9, 2)},
  'DIVS, DIVSL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'DIVU, DIVUL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'MOVE16': {'OPMODE': (4, 3, 2), 'REGISTER Ay': (2, 0, 3)},
  'MULS': {'REGISTER DI': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'MULU': {'REGISTER Dl': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'PDBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A1': (15, 15, 1), 'Rn1': (14, 12, 3), 'Du1': (8, 6, 3), 'Dc1': (2, 0, 3)},
  'LINK': {'HIGH-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'HIGH-ORDER ADDRESS': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'R/ W': (9, 9, 1)},
  'PTEST': {'R/ W': (9, 9, 1), 'REGISTER': (7, 4, 4), 'FC': (3, 0, 4)},
  'PVALID': {'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A2': (15, 15, 1), 'Rn2': (14, 12, 3), 'Du2': (8, 6, 3), 'Dc2': (2, 0, 3)},
  'LINK': {'LOW-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'LOW-ORDER ADDRESS': (15, 0, 16)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'R/W': (9, 9, 1)},
  'PTEST': {'LEVEL': (12, 10, 3), 'R/ W': (9, 9, 1), 'A-REGISTER': (8, 6, 3), 'FC': (5, 0, 6)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'NUM': (4, 2, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}})
RAW_FIELDS: tuple[dict[str, tuple[tuple[str, int, int, int], ...]], ...] = ({'ABCD': (('REGISTER Rx', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Ry', 2, 0, 3)),
  'ADD': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDX': (('REGISTER Rx', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Ry', 2, 0, 3)),
  'AND': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ANDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ANDI to CCR': (),
  'ANDI to SR': (),
  'ASL, ASR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'BCHG': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFFFO': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFINS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BKPT': (('VECTOR', 2, 0, 3),),
  'BRA': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BSET': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BSR': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BTST': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'Bcc': (('CONDITION', 11, 8, 4), ('8-BIT DISPLACEMENT', 7, 0, 8)),
  'CALLM': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CAS CAS2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK': (('REGISTER', 11, 9, 3), ('SIZE', 8, 7, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CINV': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'CLR': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPM': (('REGISTER Ax', 11, 9, 3), ('SIZE', 7, 6, 2), ('REGISTER Ay', 2, 0, 3)),
  'CPUSH': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'DBcc': (('CONDITION', 11, 8, 4), ('REGISTER', 2, 0, 3)),
  'DIVS, DIVSL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EOR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EORI to CCR': (),
  'EORI to SR': (),
  'EXG': (('REGISTER Rx', 11, 9, 3), ('OPMODE', 7, 3, 5), ('REGISTER Ry', 2, 0, 3)),
  'EXT, EXTB': (('OPMODE', 8, 6, 3), ('REGISTER', 2, 0, 3)),
  'FRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'FSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ILLEGAL': (),
  'JMP': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'JSR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LEA': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'LSL, LSR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'MOVE': (('SIZE', 13, 12, 2),
           ('REGISTER', 11, 9, 3),
           ('MODE', 8, 6, 3),
           ('MODE', 5, 3, 3),
           ('REGISTER', 2, 0, 3)),
  'MOVE USP': (('dr', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'MOVE from CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE from SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ax', 2, 0, 3),),
  'MOVEA': (('SIZE', 13, 12, 2), ('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEC': (('dr', 0, 0, 1),),
  'MOVEM': (('dr', 10, 10, 1), ('SIZE', 6, 6, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEP': (('DATA REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('ADDRESS REGISTER', 2, 0, 3)),
  'MOVEQ': (('REGISTER', 11, 9, 3), ('DATA', 7, 0, 8)),
  'MOVES': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULS': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NBCD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEG': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEGX': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NOP': (),
  'NOT': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'OR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ORI to CCR': (),
  'ORI to SR': (),
  'PACK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'PBcc': (('SIZE', 6, 6, 1), ('MC68851 CONDITION', 5, 0, 6)),
  'PDBcc': (('COUNT REGISTER', 2, 0, 3),),
  'PEA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH PFLUSHA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSHR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PLOAD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PRESTORE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PSAVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PScc': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTRAPcc': (('OPMODE', 2, 0, 3),),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'RESET': (),
  'ROL, ROR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('REGISTER', 11, 9, 3),
                 ('dr', 8, 8, 1),
                 ('SIZE', 7, 6, 2),
                 ('i/r', 5, 5, 1),
                 ('REGISTER', 2, 0, 3)),
  'RTD': (),
  'RTE': (),
  'RTM': (('D/A', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'RTR': (),
  'RTS': (),
  'SBCD': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'STOP': (),
  'SUB': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBX': (('REGISTER Dy/Ay', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Dx/Ax', 2, 0, 3)),
  'SWAP': (('REGISTER', 2, 0, 3),),
  'Scc': (('CONDITION', 11, 8, 4), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TAS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TRAP': (('VECTOR', 3, 0, 4),),
  'TRAPV': (),
  'TRAPcc': (('CONDITION', 11, 8, 4), ('OPMODE', 2, 0, 3)),
  'TST': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'UNLK': (('REGISTER', 2, 0, 3),),
  'UNPK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'cpBcc': (('ID', 15, 0, 16),),
  'cpDBcc': (('ID', 15, 0, 16),),
  'cpGEN': (('ID', 15, 0, 16),),
  'cpRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpScc': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpTRAPcc': (('ID', 15, 0, 16),)},
 {'ASL, ASR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFCLR': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFEXTS': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFEXTU': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFFFO': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFINS': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFSET': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFTST': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CALLM': (('ARGUMENT COUNT', 7, 0, 8),),
  'CAS CAS2': (('Du', 8, 6, 3), ('Dc', 2, 0, 3)),
  'CHK2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'CMP2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'DBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'DIVS, DIVSL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('WORD DISPLACEMENT', 15, 0, 16),),
  'LSL, LSR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ay', 14, 12, 3),),
  'MOVEC': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('CONTROL REGISTER', 11, 0, 12)),
  'MOVEP': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'MOVES': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('dr', 11, 11, 1)),
  'MULS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PDBcc': (('MC68851 CONDITION', 5, 0, 6),),
  'PFLUSH': (('MODE', 12, 10, 3), ('MASK', 7, 4, 4), ('FC', 3, 0, 4)),
  'PFLUSH PFLUSHA': (('MODE', 12, 10, 3), ('MASK', 7, 5, 3), ('FC', 3, 0, 4)),
  'PFLUSHR': (),
  'PLOAD': (('R/ W', 9, 9, 1), ('FC', 4, 0, 5)),
  'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PScc': (('MC68851 CONDITION', 5, 0, 6),),
  'PTEST': (('LEVEL', 12, 10, 3),
            ('R/ W', 9, 9, 1),
            ('A', 8, 8, 1),
            ('REGISTER', 7, 3, 5),
            ('FC', 2, 0, 3)),
  'PTRAPcc': (('MC68851 CONDITION', 5, 0, 6),),
  'PVALID': (),
  'ROL, ROR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'RTD': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'STOP': (('IMMEDIATE DATA', 15, 0, 16),),
  'TRAPcc': (('OPTIONAL WORD', 15, 0, 16),),
  'cpDBcc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpGEN': (('MODE', 15, 3, 13), ('REGISTER', 2, 0, 3)),
  'cpScc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpTRAPcc': (('COPROCESSOR CONDITION', 5, 0, 6),)},
 {'BCHG': (('BIT NUMBER', 7, 0, 8),),
  'BCLR': (('BIT NUMBER', 7, 0, 8),),
  'BSET': (('BIT NUMBER', 8, 0, 9),),
  'BTST': (('BIT NUMBER', 7, 0, 8),),
  'CAS CAS2': (('SIZE', 10, 9, 2),),
  'DIVS, DIVSL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'MOVE16': (('OPMODE', 4, 3, 2), ('REGISTER Ay', 2, 0, 3)),
  'MULS': (('REGISTER DI', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'MULU': (('REGISTER Dl', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'PDBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'CAS CAS2': (('D/A1', 15, 15, 1), ('Rn1', 14, 12, 3), ('Du1', 8, 6, 3), ('Dc1', 2, 0, 3)),
  'LINK': (('HIGH-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('HIGH-ORDER ADDRESS', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('R/ W', 9, 9, 1),),
  'PTEST': (('R/ W', 9, 9, 1), ('REGISTER', 7, 4, 4), ('FC', 3, 0, 4)),
  'PVALID': (('REGISTER', 2, 0, 3),)},
 {'CAS CAS2': (('D/A2', 15, 15, 1), ('Rn2', 14, 12, 3), ('Du2', 8, 6, 3), ('Dc2', 2, 0, 3)),
  'LINK': (('LOW-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('LOW-ORDER ADDRESS', 15, 0, 16),),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('R/W', 9, 9, 1),),
  'PTEST': (('LEVEL', 12, 10, 3), ('R/ W', 9, 9, 1), ('A-REGISTER', 8, 6, 3), ('FC', 5, 0, 6))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('NUM', 4, 2, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))})
EA_FIELD_SPECS = {'ADD': ((5, 3, 3), (2, 0, 3)),
 'ADDA': ((5, 3, 3), (2, 0, 3)),
 'ADDI': ((5, 3, 3), (2, 0, 3)),
 'ADDQ': ((5, 3, 3), (2, 0, 3)),
 'AND': ((5, 3, 3), (2, 0, 3)),
 'ANDI': ((5, 3, 3), (2, 0, 3)),
 'BCHG': ((5, 3, 3), (2, 0, 3)),
 'BCLR': ((5, 3, 3), (2, 0, 3)),
 'BFCHG': ((5, 3, 3), (2, 0, 3)),
 'BFCLR': ((5, 3, 3), (2, 0, 3)),
 'BFEXTS': ((5, 3, 3), (2, 0, 3)),
 'BFEXTU': ((5, 3, 3), (2, 0, 3)),
 'BFFFO': ((5, 3, 3), (2, 0, 3)),
 'BFINS': ((5, 3, 3), (2, 0, 3)),
 'BFSET': ((5, 3, 3), (2, 0, 3)),
 'BFTST': ((5, 3, 3), (2, 0, 3)),
 'BSET': ((5, 3, 3), (2, 0, 3)),
 'BTST': ((5, 3, 3), (2, 0, 3)),
 'CALLM': ((5, 3, 3), (2, 0, 3)),
 'CAS CAS2': ((5, 3, 3), (2, 0, 3)),
 'CHK': ((5, 3, 3), (2, 0, 3)),
 'CHK2': ((5, 3, 3), (2, 0, 3)),
 'CLR': ((5, 3, 3), (2, 0, 3)),
 'CMP': ((5, 3, 3), (2, 0, 3)),
 'CMP2': ((5, 3, 3), (2, 0, 3)),
 'CMPA': ((5, 3, 3), (2, 0, 3)),
 'CMPI': ((5, 3, 3), (2, 0, 3)),
 'DIVS, DIVSL': ((5, 3, 3), (2, 0, 3)),
 'DIVU, DIVUL': ((5, 3, 3), (2, 0, 3)),
 'EOR': ((5, 3, 3), (2, 0, 3)),
 'EORI': ((5, 3, 3), (2, 0, 3)),
 'FRESTORE': ((5, 3, 3), (2, 0, 3)),
 'FSAVE': ((5, 3, 3), (2, 0, 3)),
 'JMP': ((5, 3, 3), (2, 0, 3)),
 'JSR': ((5, 3, 3), (2, 0, 3)),
 'LEA': ((5, 3, 3), (2, 0, 3)),
 'MOVE': ((5, 3, 3), (2, 0, 3)),
 'MOVE from CCR': ((5, 3, 3), (2, 0, 3)),
 'MOVE from SR': ((5, 3, 3), (2, 0, 3)),
 'MOVE to CCR': ((5, 3, 3), (2, 0, 3)),
 'MOVE to SR': ((5, 3, 3), (2, 0, 3)),
 'MOVEA': ((5, 3, 3), (2, 0, 3)),
 'MOVEM': ((5, 3, 3), (2, 0, 3)),
 'MOVES': ((5, 3, 3), (2, 0, 3)),
 'MULS': ((5, 3, 3), (2, 0, 3)),
 'MULU': ((5, 3, 3), (2, 0, 3)),
 'NBCD': ((5, 3, 3), (2, 0, 3)),
 'NEG': ((5, 3, 3), (2, 0, 3)),
 'NEGX': ((5, 3, 3), (2, 0, 3)),
 'NOT': ((5, 3, 3), (2, 0, 3)),
 'OR': ((5, 3, 3), (2, 0, 3)),
 'ORI': ((5, 3, 3), (2, 0, 3)),
 'PEA': ((5, 3, 3), (2, 0, 3)),
 'PFLUSH': ((5, 3, 3), (2, 0, 3)),
 'PFLUSH PFLUSHA': ((5, 3, 3), (2, 0, 3)),
 'PFLUSHR': ((5, 3, 3), (2, 0, 3)),
 'PLOAD': ((5, 3, 3), (2, 0, 3)),
 'PMOVE': ((5, 3, 3), (2, 0, 3)),
 'PRESTORE': ((5, 3, 3), (2, 0, 3)),
 'PSAVE': ((5, 3, 3), (2, 0, 3)),
 'PScc': ((5, 3, 3), (2, 0, 3)),
 'PTEST': ((5, 3, 3), (2, 0, 3)),
 'PVALID': ((5, 3, 3), (2, 0, 3)),
 'SUB': ((5, 3, 3), (2, 0, 3)),
 'SUBA': ((5, 3, 3), (2, 0, 3)),
 'SUBI': ((5, 3, 3), (2, 0, 3)),
 'SUBQ': ((5, 3, 3), (2, 0, 3)),
 'Scc': ((5, 3, 3), (2, 0, 3)),
 'TAS': ((5, 3, 3), (2, 0, 3)),
 'TST': ((5, 3, 3), (2, 0, 3)),
 'cpRESTORE': ((5, 3, 3), (2, 0, 3)),
 'cpSAVE': ((5, 3, 3), (2, 0, 3)),
 'cpScc': ((5, 3, 3), (2, 0, 3))}
EXT_FIELD_NAMES = {'ASL, ASR': ('MODE', 'REGISTER', 'dr'),
 'BCHG': ('MODE', 'REGISTER'),
 'BCLR': ('MODE', 'REGISTER'),
 'BFCHG': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFCLR': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFEXTS': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFEXTU': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFFFO': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFINS': ('Do', 'Dw', 'OFFSET', 'REGISTER', 'WIDTH'),
 'BFSET': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BFTST': ('Do', 'Dw', 'OFFSET', 'WIDTH'),
 'BSET': ('MODE', 'REGISTER'),
 'BTST': ('MODE', 'REGISTER'),
 'CALLM': ('ARGUMENT COUNT',),
 'CAS CAS2': ('Dc', 'Du'),
 'CHK2': ('D/A', 'REGISTER'),
 'CMP2': ('D/A', 'REGISTER'),
 'DBcc': ('16-BIT DISPLACEMENT',),
 'DIVS, DIVSL': ('MODE', 'REGISTER'),
 'DIVU, DIVUL': ('MODE', 'REGISTER'),
 'LINK': ('WORD DISPLACEMENT',),
 'LSL, LSR': ('MODE', 'REGISTER', 'dr'),
 'MOVE16': ('REGISTER Ay',),
 'MOVEC': ('A/D', 'CONTROL REGISTER', 'REGISTER'),
 'MOVEP': ('16-BIT DISPLACEMENT',),
 'MOVES': ('A/D', 'REGISTER', 'dr'),
 'MULS': ('MODE', 'REGISTER'),
 'MULU': ('MODE', 'REGISTER'),
 'PDBcc': ('MC68851 CONDITION',),
 'PFLUSH': ('FC', 'MASK', 'MODE'),
 'PFLUSH PFLUSHA': ('FC', 'MASK', 'MODE'),
 'PFLUSHR': (),
 'PLOAD': ('FC', 'R/ W'),
 'PMOVE': ('FD', 'P-REGISTER', 'R/ W'),
 'PScc': ('MC68851 CONDITION',),
 'PTEST': ('A', 'FC', 'LEVEL', 'R/ W', 'REGISTER'),
 'PTRAPcc': ('MC68851 CONDITION',),
 'PVALID': (),
 'ROL, ROR': ('MODE', 'REGISTER', 'dr'),
 'ROXL, ROXR': ('MODE', 'REGISTER', 'dr'),
 'RTD': ('16-BIT DISPLACEMENT',),
 'STOP': ('IMMEDIATE DATA',),
 'TRAPcc': ('OPTIONAL WORD',),
 'cpDBcc': ('COPROCESSOR CONDITION',),
 'cpGEN': ('MODE', 'REGISTER'),
 'cpScc': ('COPROCESSOR CONDITION',),
 'cpTRAPcc': ('COPROCESSOR CONDITION',)}
FORM_OPERAND_TYPES: dict[str, tuple[tuple[str, ...], ...]] = {'ABCD': (('dn', 'dn'), ('predec', 'predec')),
 'ADD': (('ea', 'dn'), ('dn', 'ea')),
 'ADDA': (('ea', 'an'),),
 'ADDI': (('imm', 'ea'),),
 'ADDQ': (('imm', 'ea'),),
 'ADDX': (('dn', 'dn'), ('predec', 'predec')),
 'AND': (('ea', 'dn'), ('dn', 'ea')),
 'ANDI': (('imm', 'ea'),),
 'ANDI to CCR': (('imm', 'ccr'),),
 'ANDI to SR': (('imm', 'sr'),),
 'ASL, ASR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'BCHG': (('dn', 'ea'), ('imm', 'ea')),
 'BCLR': (('dn', 'ea'), ('imm', 'ea')),
 'BFCHG': (('bf_ea',),),
 'BFCLR': (('bf_ea',),),
 'BFEXTS': (('bf_ea', 'dn'),),
 'BFEXTU': (('bf_ea', 'dn'),),
 'BFFFO': (('bf_ea', 'dn'),),
 'BFINS': (('dn', 'bf_ea'),),
 'BFSET': (('bf_ea',),),
 'BFTST': (('bf_ea',),),
 'BKPT': (('imm',),),
 'BRA': (('label',),),
 'BSET': (('dn', 'ea'), ('imm', 'ea')),
 'BSR': (('label',),),
 'BTST': (('dn', 'ea'), ('imm', 'ea')),
 'Bcc': (('label',),),
 'CALLM': (('imm', 'ea'),),
 'CAS CAS2': (('dn', 'dn', 'ea'), ('dn_pair', 'dn_pair', 'unknown')),
 'CHK': (('ea', 'dn'),),
 'CHK2': (('ea', 'rn'),),
 'CINV': (),
 'CLR': (('ea',),),
 'CMP': (('ea', 'dn'),),
 'CMP2': (('ea', 'rn'),),
 'CMPA': (('ea', 'an'),),
 'CMPI': (('imm', 'ea'),),
 'CMPM': (('postinc', 'postinc'),),
 'CPUSH': (),
 'DBcc': (('dn', 'label'),),
 'DIVS, DIVSL': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair'), ('ea', 'dn_pair')),
 'DIVU, DIVUL': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair'), ('ea', 'dn_pair')),
 'EOR': (('dn', 'ea'),),
 'EORI': (('imm', 'ea'),),
 'EORI to CCR': (('imm', 'ccr'),),
 'EORI to SR': (('imm', 'sr'),),
 'EXG': (('dn', 'dn'), ('an', 'an'), ('dn', 'an')),
 'EXT, EXTB': (('dn',), ('dn',), ('dn',)),
 'FRESTORE': (('ea',),),
 'FSAVE': (('ea',),),
 'ILLEGAL': ((),),
 'JMP': (('ea',),),
 'JSR': (('ea',),),
 'LEA': (('ea', 'an'),),
 'LINK': (('an', 'imm'),),
 'LSL, LSR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'MOVE': (('ea', 'ea'),),
 'MOVE USP': (('usp', 'an'), ('an', 'usp')),
 'MOVE from CCR': (('ccr', 'ea'),),
 'MOVE from SR': (('sr', 'ea'),),
 'MOVE to CCR': (('ea', 'ccr'),),
 'MOVE to SR': (('ea', 'sr'),),
 'MOVE16': (('postinc', 'postinc'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown'),
            ('unknown', 'unknown')),
 'MOVEA': (('ea', 'an'),),
 'MOVEC': (('ctrl_reg', 'rn'), ('rn', 'ctrl_reg')),
 'MOVEM': (('reglist', 'ea'), ('ea', 'reglist')),
 'MOVEP': (('dn', 'disp'), ('disp', 'dn')),
 'MOVEQ': (('imm', 'dn'),),
 'MOVES': (('rn', 'ea'), ('ea', 'rn')),
 'MULS': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair')),
 'MULU': (('ea', 'dn'), ('ea', 'dn'), ('ea', 'dn_pair')),
 'NBCD': (('ea',),),
 'NEG': (('ea',),),
 'NEGX': (('ea',),),
 'NOP': ((),),
 'NOT': (('ea',),),
 'OR': (('ea', 'dn'), ('dn', 'ea')),
 'ORI': (('imm', 'ea'),),
 'ORI to CCR': (('imm', 'ccr'),),
 'ORI to SR': (('imm', 'sr'),),
 'PACK': (('predec', 'predec', 'imm'), ('dn', 'dn', 'imm')),
 'PBcc': (('label',),),
 'PDBcc': (('dn', 'label'),),
 'PEA': (('ea',),),
 'PFLUSH': (('unknown', 'unknown'), ('unknown', 'unknown', 'ea')),
 'PFLUSH PFLUSHA': ((), ('unknown', 'unknown'), ('unknown', 'unknown', 'ea')),
 'PFLUSHR': (('ea',),),
 'PLOAD': (),
 'PMOVE': (('unknown', 'ea'), ('ea', 'unknown')),
 'PRESTORE': (('ea',),),
 'PSAVE': (('ea',),),
 'PScc': (('ea',),),
 'PTEST': (),
 'PTRAPcc': ((), ('imm',), ('imm',)),
 'PVALID': (('unknown', 'ea'), ('an', 'ea')),
 'RESET': ((),),
 'ROL, ROR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'ROXL, ROXR': (('dn', 'dn'), ('imm', 'dn'), ('ea',)),
 'RTD': (('imm',),),
 'RTE': ((),),
 'RTM': (('rn',),),
 'RTR': ((),),
 'RTS': ((),),
 'SBCD': (('dn', 'dn'), ('predec', 'predec')),
 'STOP': (('imm',),),
 'SUB': (('ea', 'dn'), ('dn', 'ea')),
 'SUBA': (('ea', 'an'),),
 'SUBI': (('imm', 'ea'),),
 'SUBQ': (('imm', 'ea'),),
 'SUBX': (('dn', 'dn'), ('predec', 'predec')),
 'SWAP': (('dn',),),
 'Scc': (('ea',),),
 'TAS': (('ea',),),
 'TRAP': (('imm',),),
 'TRAPV': ((),),
 'TRAPcc': ((), ('imm',), ('imm',)),
 'TST': (('ea',),),
 'UNLK': (('an',),),
 'UNPK': (('dn', 'dn', 'imm'),),
 'cpBcc': (('label',),),
 'cpDBcc': (('dn', 'label'),),
 'cpGEN': (('unknown',),),
 'cpRESTORE': (('ea',),),
 'cpSAVE': (('ea',),),
 'cpScc': (('ea',),),
 'cpTRAPcc': ((), ('imm',))}
OPERATION_TYPES = {'ABCD': OperationType.ADD_DECIMAL,
 'ADD': OperationType.ADD,
 'ADDA': OperationType.ADD,
 'ADDI': OperationType.ADD,
 'ADDQ': OperationType.ADD,
 'ADDX': OperationType.ADDX,
 'AND': OperationType.AND,
 'ANDI': OperationType.AND,
 'ANDI to CCR': OperationType.CCR_OP,
 'ANDI to SR': OperationType.SR_OP,
 'ASL, ASR': OperationType.SHIFT,
 'BCHG': OperationType.BIT_TEST,
 'BCLR': OperationType.BIT_TEST,
 'BFCHG': OperationType.BITFIELD,
 'BFCLR': OperationType.BITFIELD,
 'BFEXTS': OperationType.BITFIELD,
 'BFEXTU': OperationType.BITFIELD,
 'BFFFO': OperationType.BITFIELD,
 'BFINS': OperationType.BITFIELD,
 'BFSET': OperationType.BITFIELD,
 'BFTST': OperationType.BITFIELD,
 'BKPT': None,
 'BRA': OperationType.ADD,
 'BSET': OperationType.BIT_TEST,
 'BSR': OperationType.SUB,
 'BTST': OperationType.BIT_TEST,
 'Bcc': None,
 'CALLM': None,
 'CAS CAS2': OperationType.COMPARE_SWAP,
 'CHK': OperationType.BOUNDS_CHECK,
 'CHK2': OperationType.BOUNDS_CHECK,
 'CINV': OperationType.SR_OP,
 'CLR': OperationType.CLEAR,
 'CMP': OperationType.COMPARE,
 'CMP2': OperationType.BOUNDS_CHECK,
 'CMPA': OperationType.COMPARE,
 'CMPI': OperationType.COMPARE,
 'CMPM': OperationType.COMPARE,
 'CPUSH': OperationType.SR_OP,
 'DBcc': None,
 'DIVS, DIVSL': OperationType.DIVIDE,
 'DIVU, DIVUL': OperationType.DIVIDE,
 'EOR': OperationType.XOR,
 'EORI': OperationType.XOR,
 'EORI to CCR': OperationType.CCR_OP,
 'EORI to SR': OperationType.SR_OP,
 'EXG': OperationType.SWAP,
 'EXT, EXTB': OperationType.SIGN_EXTEND,
 'FRESTORE': OperationType.SR_OP,
 'FSAVE': OperationType.SR_OP,
 'ILLEGAL': OperationType.SUB,
 'JMP': OperationType.MOVE,
 'JSR': OperationType.SUB,
 'LEA': OperationType.MOVE,
 'LINK': OperationType.SUB,
 'LSL, LSR': OperationType.SHIFT,
 'MOVE': OperationType.MOVE,
 'MOVE USP': OperationType.SR_OP,
 'MOVE from CCR': OperationType.CCR_OP,
 'MOVE from SR': OperationType.MOVE,
 'MOVE to CCR': OperationType.CCR_OP,
 'MOVE to SR': OperationType.SR_OP,
 'MOVE16': OperationType.MOVE,
 'MOVEA': OperationType.MOVE,
 'MOVEC': OperationType.SR_OP,
 'MOVEM': OperationType.MOVE,
 'MOVEP': OperationType.MOVE,
 'MOVEQ': OperationType.MOVE,
 'MOVES': OperationType.SR_OP,
 'MULS': OperationType.MULTIPLY,
 'MULU': OperationType.MULTIPLY,
 'NBCD': OperationType.NEGX,
 'NEG': OperationType.NEG,
 'NEGX': OperationType.NEGX,
 'NOP': None,
 'NOT': OperationType.NOT,
 'OR': OperationType.OR,
 'ORI': OperationType.OR,
 'ORI to CCR': OperationType.CCR_OP,
 'ORI to SR': OperationType.SR_OP,
 'PACK': OperationType.ADD,
 'PBcc': OperationType.SR_OP,
 'PDBcc': OperationType.SR_OP,
 'PEA': OperationType.SUB,
 'PFLUSH': OperationType.SR_OP,
 'PFLUSH PFLUSHA': OperationType.SR_OP,
 'PFLUSHR': OperationType.SR_OP,
 'PLOAD': OperationType.SR_OP,
 'PMOVE': OperationType.SR_OP,
 'PRESTORE': OperationType.SR_OP,
 'PSAVE': OperationType.SR_OP,
 'PScc': OperationType.SR_OP,
 'PTEST': OperationType.SR_OP,
 'PTRAPcc': OperationType.SR_OP,
 'PVALID': OperationType.MOVE,
 'RESET': OperationType.SR_OP,
 'ROL, ROR': OperationType.ROTATE,
 'ROXL, ROXR': OperationType.ROTATE_EXTEND,
 'RTD': OperationType.ADD,
 'RTE': OperationType.SR_OP,
 'RTM': None,
 'RTR': OperationType.CCR_OP,
 'RTS': OperationType.ADD,
 'SBCD': OperationType.SUB_DECIMAL,
 'STOP': OperationType.SR_OP,
 'SUB': OperationType.SUB,
 'SUBA': OperationType.SUB,
 'SUBI': OperationType.SUB,
 'SUBQ': OperationType.SUB,
 'SUBX': OperationType.SUBX,
 'SWAP': OperationType.SWAP,
 'Scc': None,
 'TAS': OperationType.TEST,
 'TRAP': OperationType.MOVE,
 'TRAPV': None,
 'TRAPcc': None,
 'TST': OperationType.TEST,
 'UNLK': OperationType.ADD,
 'UNPK': OperationType.ADD,
 'cpBcc': None,
 'cpDBcc': None,
 'cpGEN': None,
 'cpRESTORE': OperationType.SR_OP,
 'cpSAVE': OperationType.SR_OP,
 'cpScc': None,
 'cpTRAPcc': None}
SOURCE_SIGN_EXTEND: tuple[str, ...] = ('ADDA', 'CMPA', 'MOVEA', 'SUBA')
OPMODE_TABLES_BY_VALUE: dict[str, dict[int, OpmodeEntry]] = {'ADD': {0: OpmodeEntry(size='b', description='< ea > + Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size='w', description='< ea > + Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size='l', description='< ea > + Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size='b', description='Dn + < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='w', description='Dn + < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='l', description='Dn + < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'ADDA': {3: OpmodeEntry(size='w', description='Word operation; the source operand is sign-extended to a long operand and', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  7: OpmodeEntry(size='l', description='Long operation', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'AND': {0: OpmodeEntry(size='b', description='< ea > Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size='w', description='< ea > Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size='l', description='< ea > Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size='b', description='Dn Λ < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='w', description='Dn Λ < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='l', description='Dn Λ < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'CMP': {0: OpmodeEntry(size='b', description='Dn – < ea >', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size='w', description='Dn – < ea >', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size='l', description='Dn – < ea >', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'CMPA': {3: OpmodeEntry(size='w', description='Word operation; the source operand is sign-extended to a long operand, and', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  7: OpmodeEntry(size='l', description='Long operation', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'EOR': {4: OpmodeEntry(size='b', description='< ea > ⊕ Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='w', description='< ea > ⊕ Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='l', description='< ea > ⊕ Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'EXG': {8: OpmodeEntry(size=None, description='Data registers', ea_is_source=None, source=None, destination=None, rx_mode='dn', ry_mode='dn'),
  9: OpmodeEntry(size=None, description='Address registers', ea_is_source=None, source=None, destination=None, rx_mode='an', ry_mode='an'),
  17: OpmodeEntry(size=None, description='Data register and address register', ea_is_source=None, source=None, destination=None, rx_mode='dn', ry_mode='an')},
 'EXT, EXTB': {2: OpmodeEntry(size='b', description='Sign-extend low-order byte of data register to word', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  3: OpmodeEntry(size='w', description='Sign-extend low-order word of data register to long', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  7: OpmodeEntry(size='b', description='Sign-extend low-order byte of data register to long', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'MOVE16': {0: OpmodeEntry(size=None, description=None, ea_is_source=None, source='(Ay) +', destination='(xxx).L', rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size=None, description=None, ea_is_source=None, source='(xxx).L', destination='(Ay) +', rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size=None, description=None, ea_is_source=None, source='(Ay)', destination='(xxx).L', rx_mode=None, ry_mode=None),
  3: OpmodeEntry(size=None, description=None, ea_is_source=None, source='(xxx).L', destination='(Ay)', rx_mode=None, ry_mode=None)},
 'MOVEP': {4: OpmodeEntry(size='w', description='Transfer word from memory to register', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='l', description='Transfer long from memory to register', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='w', description='Transfer word from register to memory', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  7: OpmodeEntry(size='l', description='Transfer long from register to memory', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'OR': {0: OpmodeEntry(size='b', description='< ea > V Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size='w', description='< ea > V Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size='l', description='< ea > V Dn → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size='b', description='Dn V < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='w', description='Dn V < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='l', description='Dn V < ea > → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'PTRAPcc': {2: OpmodeEntry(size='w', description='Instruction is followed by one operand word', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  3: OpmodeEntry(size='l', description='Instruction is followed by two operand words', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size=None, description='Instruction has no following operand words', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'SUB': {0: OpmodeEntry(size='b', description='Dn – < ea > → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  1: OpmodeEntry(size='w', description='Dn – < ea > → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  2: OpmodeEntry(size='l', description='Dn – < ea > → Dn', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size='b', description='< ea > – Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  5: OpmodeEntry(size='w', description='< ea > – Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None),
  6: OpmodeEntry(size='l', description='< ea > – Dn → < ea >', ea_is_source=False, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'SUBA': {3: OpmodeEntry(size='w', description='Word operation. The source operand is sign-extended to a long operand and', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None),
  7: OpmodeEntry(size='l', description='Long operation', ea_is_source=True, source=None, destination=None, rx_mode=None, ry_mode=None)},
 'TRAPcc': {2: OpmodeEntry(size='w', description='Instruction is followed by word-sized operand', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  3: OpmodeEntry(size='l', description='Instruction is followed by long-word-sized operand', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None),
  4: OpmodeEntry(size=None, description='Instruction has no operand', ea_is_source=None, source=None, destination=None, rx_mode=None, ry_mode=None)}}
OPERAND_MODE_TABLES: dict[str, tuple[str, dict[int, tuple[str, ...]]]] = {'ABCD': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'ADDX': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'PACK': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'SBCD': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'SUBX': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'UNPK': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')})}
EA_MODE_TABLES = {'ABCD': ((), (), ()),
 'ADD': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'ADDA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'ADDI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ADDQ': ((), ('dn', 'an', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ADDX': ((), (), ()),
 'AND': (('dn',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'ANDI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ANDI to CCR': ((), (), ()),
 'ANDI to SR': ((), (), ()),
 'ASL, ASR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'BCHG': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BCLR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BFCHG': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFCLR': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFEXTS': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFEXTU': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFFFO': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BFINS': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFSET': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl')),
 'BFTST': ((), (), ('dn', 'ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'BKPT': ((), (), ()),
 'BRA': ((), (), ()),
 'BSET': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'BSR': ((), (), ()),
 'BTST': ((),
          ('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          ()),
 'Bcc': ((), (), ()),
 'CALLM': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CAS CAS2': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'CHK': ((),
         (),
         ('dn',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm')),
 'CHK2': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CINV': ((), (), ()),
 'CLR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'CMP': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         (),
         ()),
 'CMP2': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'CMPA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'CMPI': ((),
          ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex'),
          ()),
 'CMPM': ((), (), ()),
 'CPUSH': ((), (), ()),
 'DBcc': ((), (), ()),
 'DIVS, DIVSL': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'DIVU, DIVUL': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'EOR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'EORI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'EORI to CCR': ((), (), ()),
 'EORI to SR': ((), (), ()),
 'EXG': ((), (), ()),
 'EXT, EXTB': ((), (), ()),
 'FRESTORE': ((), (), ('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'FSAVE': ((), (), ('ind', 'predec', 'disp', 'index', 'absw', 'absl')),
 'ILLEGAL': ((), (), ()),
 'JMP': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'JSR': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'LEA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'LINK': ((), (), ()),
 'LSL, LSR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'MOVE': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
          ()),
 'MOVE USP': ((), (), ()),
 'MOVE from CCR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'MOVE from SR': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'MOVE to CCR': (('dn',
                  'ind',
                  'postinc',
                  'predec',
                  'disp',
                  'index',
                  'absw',
                  'absl',
                  'pcdisp',
                  'pcindex',
                  'imm'),
                 (),
                 ()),
 'MOVE to SR': (('dn',
                 'ind',
                 'postinc',
                 'predec',
                 'disp',
                 'index',
                 'absw',
                 'absl',
                 'pcdisp',
                 'pcindex',
                 'imm'),
                (),
                ()),
 'MOVE16': ((), (), ()),
 'MOVEA': (('dn',
            'an',
            'ind',
            'postinc',
            'predec',
            'disp',
            'index',
            'absw',
            'absl',
            'pcdisp',
            'pcindex',
            'imm'),
           (),
           ()),
 'MOVEC': ((), (), ()),
 'MOVEM': ((),
           (),
           ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'MOVEP': ((), (), ()),
 'MOVEQ': ((), (), ()),
 'MOVES': (('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), (), ()),
 'MULS': (('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'MULU': (('dn',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'NBCD': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NEG': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NEGX': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'NOP': ((), (), ()),
 'NOT': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'OR': (('dn',
         'ind',
         'postinc',
         'predec',
         'disp',
         'index',
         'absw',
         'absl',
         'pcdisp',
         'pcindex',
         'imm'),
        ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
        ()),
 'ORI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'ORI to CCR': ((), (), ()),
 'ORI to SR': ((), (), ()),
 'PACK': ((), (), ()),
 'PBcc': ((), (), ()),
 'PDBcc': ((), (), ()),
 'PEA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex')),
 'PFLUSH': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PFLUSH PFLUSHA': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PFLUSHR': ((),
             (),
             ('ind',
              'postinc',
              'predec',
              'disp',
              'index',
              'absw',
              'absl',
              'pcdisp',
              'pcindex',
              'imm')),
 'PLOAD': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PMOVE': ((),
           (),
           ('dn',
            'an',
            'ind',
            'postinc',
            'predec',
            'disp',
            'index',
            'absw',
            'absl',
            'pcdisp',
            'pcindex',
            'imm')),
 'PRESTORE': (('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex'), (), ()),
 'PSAVE': ((), ('ind', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'PScc': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'PTEST': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'PTRAPcc': ((), (), ()),
 'PVALID': ((), (), ('ind', 'disp', 'index', 'absw', 'absl')),
 'RESET': ((), (), ()),
 'ROL, ROR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index')),
 'ROXL, ROXR': ((), (), ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'RTD': ((), (), ()),
 'RTE': ((), (), ()),
 'RTM': ((), (), ()),
 'RTR': ((), (), ()),
 'RTS': ((), (), ()),
 'SBCD': ((), (), ()),
 'STOP': ((), (), ()),
 'SUB': (('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ('ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'),
         ()),
 'SUBA': (('dn',
           'an',
           'ind',
           'postinc',
           'predec',
           'disp',
           'index',
           'absw',
           'absl',
           'pcdisp',
           'pcindex',
           'imm'),
          (),
          ()),
 'SUBI': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'SUBQ': ((), ('dn', 'an', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'SUBX': ((), (), ()),
 'SWAP': ((), (), ()),
 'Scc': ((), (), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'TAS': ((), (), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl')),
 'TRAP': ((), (), ()),
 'TRAPV': ((), (), ()),
 'TRAPcc': ((), (), ()),
 'TST': ((),
         ('dn',
          'an',
          'ind',
          'postinc',
          'predec',
          'disp',
          'index',
          'absw',
          'absl',
          'pcdisp',
          'pcindex',
          'imm'),
         ()),
 'UNLK': ((), (), ()),
 'UNPK': ((), (), ()),
 'cpBcc': ((), (), ()),
 'cpDBcc': ((), (), ()),
 'cpGEN': ((), (), ()),
 'cpRESTORE': ((),
               (),
               ('ind', 'postinc', 'disp', 'index', 'absw', 'absl', 'pcdisp', 'pcindex', 'imm')),
 'cpSAVE': ((), (), ('ind', 'predec', 'disp', 'index', 'absw', 'absl')),
 'cpScc': ((), ('dn', 'ind', 'postinc', 'predec', 'disp', 'index', 'absw', 'absl'), ()),
 'cpTRAPcc': ((), (), ())}
AN_SIZES = {'ABCD': (),
 'ADD': (),
 'ADDA': (),
 'ADDI': (),
 'ADDQ': ('w', 'l'),
 'ADDX': (),
 'AND': (),
 'ANDI': (),
 'ANDI to CCR': (),
 'ANDI to SR': (),
 'ASL, ASR': (),
 'BCHG': (),
 'BCLR': (),
 'BFCHG': (),
 'BFCLR': (),
 'BFEXTS': (),
 'BFEXTU': (),
 'BFFFO': (),
 'BFINS': (),
 'BFSET': (),
 'BFTST': (),
 'BKPT': (),
 'BRA': (),
 'BSET': (),
 'BSR': (),
 'BTST': (),
 'Bcc': (),
 'CALLM': (),
 'CAS CAS2': (),
 'CHK': (),
 'CHK2': (),
 'CINV': (),
 'CLR': (),
 'CMP': (),
 'CMP2': (),
 'CMPA': (),
 'CMPI': (),
 'CMPM': (),
 'CPUSH': (),
 'DBcc': (),
 'DIVS, DIVSL': (),
 'DIVU, DIVUL': (),
 'EOR': (),
 'EORI': (),
 'EORI to CCR': (),
 'EORI to SR': (),
 'EXG': (),
 'EXT, EXTB': (),
 'FRESTORE': (),
 'FSAVE': (),
 'ILLEGAL': (),
 'JMP': (),
 'JSR': (),
 'LEA': (),
 'LINK': (),
 'LSL, LSR': (),
 'MOVE': (),
 'MOVE USP': (),
 'MOVE from CCR': (),
 'MOVE from SR': (),
 'MOVE to CCR': (),
 'MOVE to SR': (),
 'MOVE16': (),
 'MOVEA': (),
 'MOVEC': (),
 'MOVEM': (),
 'MOVEP': (),
 'MOVEQ': (),
 'MOVES': (),
 'MULS': (),
 'MULU': (),
 'NBCD': (),
 'NEG': (),
 'NEGX': (),
 'NOP': (),
 'NOT': (),
 'OR': (),
 'ORI': (),
 'ORI to CCR': (),
 'ORI to SR': (),
 'PACK': (),
 'PBcc': (),
 'PDBcc': (),
 'PEA': (),
 'PFLUSH': (),
 'PFLUSH PFLUSHA': (),
 'PFLUSHR': (),
 'PLOAD': (),
 'PMOVE': (),
 'PRESTORE': (),
 'PSAVE': (),
 'PScc': (),
 'PTEST': (),
 'PTRAPcc': (),
 'PVALID': (),
 'RESET': (),
 'ROL, ROR': (),
 'ROXL, ROXR': (),
 'RTD': (),
 'RTE': (),
 'RTM': (),
 'RTR': (),
 'RTS': (),
 'SBCD': (),
 'STOP': (),
 'SUB': (),
 'SUBA': (),
 'SUBI': (),
 'SUBQ': ('w', 'l'),
 'SUBX': (),
 'SWAP': (),
 'Scc': (),
 'TAS': (),
 'TRAP': (),
 'TRAPV': (),
 'TRAPcc': (),
 'TST': (),
 'UNLK': (),
 'UNPK': (),
 'cpBcc': (),
 'cpDBcc': (),
 'cpGEN': (),
 'cpRESTORE': (),
 'cpSAVE': (),
 'cpScc': (),
 'cpTRAPcc': ()}
IMMEDIATE_RANGES = {'ADDQ': ('DATA', 3, False, 1, 8, 8),
 'ASL, ASR': ('Count/Register', 3, False, 1, 8, 8),
 'BCHG': ('BIT NUMBER', 8, False, 0, 255, None),
 'BCLR': ('BIT NUMBER', 8, False, 0, 255, None),
 'BKPT': ('VECTOR', 3, False, 0, 7, None),
 'BRA': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'BSET': ('BIT NUMBER', 9, False, 0, 511, None),
 'BSR': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'BTST': ('BIT NUMBER', 8, False, 0, 255, None),
 'Bcc': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'CALLM': ('ARGUMENT COUNT', 8, False, 0, 255, None),
 'DBcc': ('16-BIT DISPLACEMENT', 16, False, 0, 65535, None),
 'LINK': ('WORD DISPLACEMENT', 16, True, -32768, 32767, None),
 'LSL, LSR': ('Count/Register', 3, False, 1, 8, 8),
 'MOVE16': ('HIGH-ORDER ADDRESS', 16, False, 0, 65535, None),
 'MOVEQ': ('DATA', 8, True, -128, 127, None),
 'ROL, ROR': ('Count/Register', 3, False, 1, 8, 8),
 'ROXL, ROXR': ('Count/Register', 3, False, 1, 8, 8),
 'RTD': ('16-BIT DISPLACEMENT', 16, False, 0, 65535, None),
 'STOP': ('IMMEDIATE DATA', 16, False, 0, 65535, None),
 'SUBQ': ('DATA', 3, False, 1, 8, 8),
 'TRAP': ('VECTOR', 4, False, 0, 15, None),
 'TRAPcc': ('OPTIONAL WORD', 16, False, 0, 65535, None)}
REGISTER_FIELDS = {'ABCD': ((11, 9, 3), (2, 0, 3)),
 'ADD': ((11, 9, 3), (2, 0, 3)),
 'ADDA': ((11, 9, 3), (2, 0, 3)),
 'ADDI': ((2, 0, 3),),
 'ADDQ': ((2, 0, 3),),
 'ADDX': ((11, 9, 3), (2, 0, 3)),
 'AND': ((11, 9, 3), (2, 0, 3)),
 'ANDI': ((2, 0, 3),),
 'ASL, ASR': ((11, 9, 3), (2, 0, 3)),
 'BCHG': ((11, 9, 3), (2, 0, 3)),
 'BCLR': ((11, 9, 3), (2, 0, 3)),
 'BFCHG': ((2, 0, 3),),
 'BFCLR': ((2, 0, 3),),
 'BFEXTS': ((2, 0, 3),),
 'BFEXTU': ((2, 0, 3),),
 'BFFFO': ((2, 0, 3),),
 'BFINS': ((2, 0, 3),),
 'BFSET': ((2, 0, 3),),
 'BFTST': ((2, 0, 3),),
 'BSET': ((11, 9, 3), (2, 0, 3)),
 'BTST': ((11, 9, 3), (2, 0, 3)),
 'CALLM': ((2, 0, 3),),
 'CAS CAS2': ((2, 0, 3),),
 'CHK': ((11, 9, 3), (2, 0, 3)),
 'CHK2': ((2, 0, 3),),
 'CINV': ((2, 0, 3),),
 'CLR': ((2, 0, 3),),
 'CMP': ((11, 9, 3), (2, 0, 3)),
 'CMP2': ((2, 0, 3),),
 'CMPA': ((11, 9, 3), (2, 0, 3)),
 'CMPI': ((2, 0, 3),),
 'CMPM': ((11, 9, 3), (2, 0, 3)),
 'CPUSH': ((2, 0, 3),),
 'DBcc': ((2, 0, 3),),
 'DIVS, DIVSL': ((11, 9, 3), (2, 0, 3)),
 'DIVU, DIVUL': ((11, 9, 3), (2, 0, 3)),
 'EOR': ((11, 9, 3), (2, 0, 3)),
 'EORI': ((2, 0, 3),),
 'EXG': ((11, 9, 3), (2, 0, 3)),
 'EXT, EXTB': ((2, 0, 3),),
 'FRESTORE': ((2, 0, 3),),
 'FSAVE': ((2, 0, 3),),
 'JMP': ((2, 0, 3),),
 'JSR': ((2, 0, 3),),
 'LEA': ((11, 9, 3), (2, 0, 3)),
 'LINK': ((2, 0, 3),),
 'LSL, LSR': ((11, 9, 3), (2, 0, 3)),
 'MOVE': ((11, 9, 3), (2, 0, 3)),
 'MOVE USP': ((2, 0, 3),),
 'MOVE from CCR': ((2, 0, 3),),
 'MOVE from SR': ((2, 0, 3),),
 'MOVE to CCR': ((2, 0, 3),),
 'MOVE to SR': ((2, 0, 3),),
 'MOVE16': ((2, 0, 3),),
 'MOVEA': ((11, 9, 3), (2, 0, 3)),
 'MOVEM': ((2, 0, 3),),
 'MOVEQ': ((11, 9, 3),),
 'MOVES': ((2, 0, 3),),
 'MULS': ((11, 9, 3), (2, 0, 3)),
 'MULU': ((11, 9, 3), (2, 0, 3)),
 'NBCD': ((2, 0, 3),),
 'NEG': ((2, 0, 3),),
 'NEGX': ((2, 0, 3),),
 'NOT': ((2, 0, 3),),
 'OR': ((11, 9, 3), (2, 0, 3)),
 'ORI': ((2, 0, 3),),
 'PACK': ((11, 9, 3), (2, 0, 3)),
 'PEA': ((2, 0, 3),),
 'PFLUSH': ((2, 0, 3),),
 'PFLUSH PFLUSHA': ((2, 0, 3),),
 'PFLUSHR': ((2, 0, 3),),
 'PLOAD': ((2, 0, 3),),
 'PMOVE': ((2, 0, 3),),
 'PRESTORE': ((2, 0, 3),),
 'PSAVE': ((2, 0, 3),),
 'PScc': ((2, 0, 3),),
 'PTEST': ((2, 0, 3),),
 'PVALID': ((2, 0, 3),),
 'ROL, ROR': ((11, 9, 3), (2, 0, 3)),
 'ROXL, ROXR': ((11, 9, 3), (2, 0, 3)),
 'RTM': ((2, 0, 3),),
 'SBCD': ((11, 9, 3), (2, 0, 3)),
 'SUB': ((11, 9, 3), (2, 0, 3)),
 'SUBA': ((11, 9, 3), (2, 0, 3)),
 'SUBI': ((2, 0, 3),),
 'SUBQ': ((2, 0, 3),),
 'SUBX': ((11, 9, 3), (2, 0, 3)),
 'SWAP': ((2, 0, 3),),
 'Scc': ((2, 0, 3),),
 'TAS': ((2, 0, 3),),
 'TST': ((2, 0, 3),),
 'UNLK': ((2, 0, 3),),
 'UNPK': ((11, 9, 3), (2, 0, 3)),
 'cpRESTORE': ((2, 0, 3),),
 'cpSAVE': ((2, 0, 3),),
 'cpScc': ((2, 0, 3),)}
DEST_REG_FIELD = {'ABCD': (11, 9, 3),
 'ADD': (11, 9, 3),
 'ADDA': (11, 9, 3),
 'ADDX': (11, 9, 3),
 'AND': (11, 9, 3),
 'ASL, ASR': (11, 9, 3),
 'BCHG': (11, 9, 3),
 'BCLR': (11, 9, 3),
 'BSET': (11, 9, 3),
 'BTST': (11, 9, 3),
 'CHK': (11, 9, 3),
 'CMP': (11, 9, 3),
 'CMPA': (11, 9, 3),
 'CMPM': (11, 9, 3),
 'DIVS, DIVSL': (11, 9, 3),
 'DIVU, DIVUL': (11, 9, 3),
 'EOR': (11, 9, 3),
 'EXG': (11, 9, 3),
 'LEA': (11, 9, 3),
 'LSL, LSR': (11, 9, 3),
 'MOVE': (11, 9, 3),
 'MOVEA': (11, 9, 3),
 'MOVEQ': (11, 9, 3),
 'MULS': (11, 9, 3),
 'MULU': (11, 9, 3),
 'OR': (11, 9, 3),
 'PACK': (11, 9, 3),
 'ROL, ROR': (11, 9, 3),
 'ROXL, ROXR': (11, 9, 3),
 'SBCD': (11, 9, 3),
 'SUB': (11, 9, 3),
 'SUBA': (11, 9, 3),
 'SUBX': (11, 9, 3),
 'UNPK': (11, 9, 3)}
DIRECTION_VARIANTS = {'ASL, ASR': ((8, 8, 1), 'as', ('asl', 'asr'), {0: 'r', 1: 'l'}),
 'LSL, LSR': ((8, 8, 1), 'ls', ('lsl', 'lsr'), {0: 'r', 1: 'l'}),
 'ROL, ROR': ((8, 8, 1), 'ro', ('rol', 'ror'), {0: 'r', 1: 'l'}),
 'ROXL, ROXR': ((8, 8, 1), 'rox', ('roxl', 'roxr'), {0: 'r', 1: 'l'})}
SHIFT_FIELDS = {'dr_field': (8, 8, 1), 'dr_values': {0: 'r', 1: 'l'}, 'zero_means': 8}
RM_FIELD = {'ABCD': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'ADDX': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'PACK': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'SBCD': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'SUBX': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'UNPK': (3, {0: 'dn,dn', 1: 'predec,predec'})}
CONTROL_REGISTERS: dict[int, str] = {0: 'sfc',
 1: 'dfc',
 2: 'cacr',
 3: 'tc',
 4: 'itt0',
 5: 'itt1',
 6: 'dtt0',
 7: 'dtt1',
 2048: 'usp',
 2049: 'vbr',
 2050: 'caar',
 2051: 'msp',
 2052: 'isp',
 2053: 'mmusr',
 2054: 'urp',
 2055: 'srp'}
MOVE_FIELDS = ((11, 9, 3), (8, 6, 3), (5, 3, 3), (2, 0, 3))
MOVEM_FIELDS = {'dr': (10, 10, 1), 'size': (6, 6, 1), 'mode': (5, 3, 3), 'register': (2, 0, 3)}
CPID_FIELD = (9, 3)
