"""Generated runtime M68K executor knowledge artifact. Do not edit directly."""

from __future__ import annotations

from enum import StrEnum

from typing import TypeAlias

OpmodeEntry: TypeAlias = tuple[str | None, str | None, bool | None, str | None, str | None, str | None, str | None]
class PrimaryDataSizeKind(StrEnum):
    MULTIPLY = 'multiply'
    DIVIDE = 'divide'
class OperationType(StrEnum):
    ADD = 'add'
    ADD_DECIMAL = 'add_decimal'
    ADDX = 'addx'
    AND = 'and'
    BIT_TEST = 'bit_test'
    BITFIELD = 'bitfield'
    BOUNDS_CHECK = 'bounds_check'
    CCR_OP = 'ccr_op'
    CLEAR = 'clear'
    COMPARE = 'compare'
    COMPARE_SWAP = 'compare_swap'
    DIVIDE = 'divide'
    MOVE = 'move'
    MULTIPLY = 'multiply'
    NEG = 'neg'
    NEGX = 'negx'
    NOT = 'not'
    OR = 'or'
    ROTATE = 'rotate'
    ROTATE_EXTEND = 'rotate_extend'
    SHIFT = 'shift'
    SIGN_EXTEND = 'sign_extend'
    SR_OP = 'sr_op'
    SUB = 'sub'
    SUB_DECIMAL = 'sub_decimal'
    SUBX = 'subx'
    SWAP = 'swap'
    TEST = 'test'
    XOR = 'xor'
class OperationClass(StrEnum):
    LOAD_EFFECTIVE_ADDRESS = 'load_effective_address'
    MULTI_REGISTER_TRANSFER = 'multi_register_transfer'
class ShiftDirection(StrEnum):
    LEFT = 'left'
    RIGHT = 'right'

class ShiftFill(StrEnum):
    ZERO = 'zero'
    SIGN = 'sign'
    ROTATE = 'rotate'
PrimaryDataSize: TypeAlias = tuple[PrimaryDataSizeKind, int, int, int]
ShiftVariantBehavior: TypeAlias = tuple[str, ShiftDirection, ShiftFill, bool]

FIELD_MAPS = ({'ABCD': {'REGISTER Rx': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Ry': (2, 0, 3)},
  'ADD': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ADDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ADDX': {'REGISTER Rx': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Ry': (2, 0, 3)},
  'AND': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ANDI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ASL, ASR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'BCHG': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BCLR': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BFCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFEXTU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFFFO': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFINS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BKPT': {'VECTOR': (2, 0, 3)},
  'BRA': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BSET': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'BSR': {'8-BIT DISPLACEMENT': (7, 0, 8)},
  'BTST': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'Bcc': {'CONDITION': (11, 8, 4), '8-BIT DISPLACEMENT': (7, 0, 8)},
  'CALLM': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CAS CAS2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CHK': {'REGISTER': (2, 0, 3), 'SIZE': (8, 7, 2), 'MODE': (5, 3, 3)},
  'CHK2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CINV': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'CLR': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMP': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMP2': {'SIZE': (10, 9, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'CMPI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CMPM': {'REGISTER Ax': (11, 9, 3), 'SIZE': (7, 6, 2), 'REGISTER Ay': (2, 0, 3)},
  'CPUSH': {'CACHE': (7, 6, 2), 'SCOPE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'DBcc': {'CONDITION': (11, 8, 4), 'REGISTER': (2, 0, 3)},
  'DIVS, DIVSL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'DIVU, DIVUL': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'EOR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'EORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'EXG': {'REGISTER Rx': (11, 9, 3), 'OPMODE': (7, 3, 5), 'REGISTER Ry': (2, 0, 3)},
  'EXT, EXTB': {'OPMODE': (8, 6, 3), 'REGISTER': (2, 0, 3)},
  'FRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'FSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'JMP': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'JSR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LEA': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'LSL, LSR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'MOVE': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVE USP': {'dr': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'MOVE from CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE from SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to CCR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE to SR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ax': (2, 0, 3)},
  'MOVEA': {'SIZE': (13, 12, 2), 'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MOVEC': {'dr': (0, 0, 1)},
  'MOVEM': {'dr': (10, 10, 1), 'SIZE': (6, 6, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVEP': {'DATA REGISTER': (11, 9, 3), 'OPMODE': (8, 6, 3), 'ADDRESS REGISTER': (2, 0, 3)},
  'MOVEQ': {'REGISTER': (11, 9, 3), 'DATA': (7, 0, 8)},
  'MOVES': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULS': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'MULU': {'REGISTER': (2, 0, 3), 'MODE': (5, 3, 3)},
  'NBCD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEG': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NEGX': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'NOT': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'OR': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'ORI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PACK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'PBcc': {'SIZE': (6, 6, 1), 'MC68851 CONDITION': (5, 0, 6)},
  'PDBcc': {'COUNT REGISTER': (2, 0, 3)},
  'PEA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSH PFLUSHA': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PFLUSHR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PLOAD': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PRESTORE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PSAVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PScc': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTRAPcc': {'OPMODE': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ROL, ROR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'ROXL, ROXR': {'REGISTER': (2, 0, 3), 'dr': (8, 8, 1), 'SIZE': (7, 6, 2), 'i/r': (5, 5, 1)},
  'RTM': {'D/A': (3, 3, 1), 'REGISTER': (2, 0, 3)},
  'SBCD': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'SUB': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBA': {'REGISTER': (2, 0, 3), 'OPMODE': (8, 6, 3), 'MODE': (5, 3, 3)},
  'SUBI': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBQ': {'DATA': (11, 9, 3), 'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'SUBX': {'REGISTER Dy/Ay': (11, 9, 3),
           'SIZE': (7, 6, 2),
           'R/M': (3, 3, 1),
           'REGISTER Dx/Ax': (2, 0, 3)},
  'SWAP': {'REGISTER': (2, 0, 3)},
  'Scc': {'CONDITION': (11, 8, 4), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TAS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'TRAP': {'VECTOR': (3, 0, 4)},
  'TRAPcc': {'CONDITION': (11, 8, 4), 'OPMODE': (2, 0, 3)},
  'TST': {'SIZE': (7, 6, 2), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'UNLK': {'REGISTER': (2, 0, 3)},
  'UNPK': {'REGISTER Dy/Ay': (11, 9, 3), 'R/M': (3, 3, 1), 'REGISTER Dx/Ax': (2, 0, 3)},
  'cpBcc': {'ID': (15, 0, 16)},
  'cpDBcc': {'ID': (15, 0, 16)},
  'cpGEN': {'ID': (15, 0, 16)},
  'cpRESTORE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpSAVE': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpScc': {'ID': (11, 9, 3), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'cpTRAPcc': {'ID': (15, 0, 16)}},
 {'ASL, ASR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCHG': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BCLR': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BFCHG': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFCLR': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFEXTS': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFEXTU': {'REGISTER': (14, 12, 3),
             'Do': (11, 11, 1),
             'OFFSET': (10, 6, 5),
             'Dw': (5, 5, 1),
             'WIDTH': (4, 0, 5)},
  'BFFFO': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFINS': {'REGISTER': (14, 12, 3),
            'Do': (11, 11, 1),
            'OFFSET': (10, 6, 5),
            'Dw': (5, 5, 1),
            'WIDTH': (4, 0, 5)},
  'BFSET': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BFTST': {'Do': (11, 11, 1), 'OFFSET': (10, 6, 5), 'Dw': (5, 5, 1), 'WIDTH': (4, 0, 5)},
  'BSET': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'BTST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'CALLM': {'ARGUMENT COUNT': (7, 0, 8)},
  'CAS CAS2': {'Du': (8, 6, 3), 'Dc': (2, 0, 3)},
  'CHK2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'CMP2': {'D/A': (15, 15, 1), 'REGISTER': (14, 12, 3)},
  'DBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'DIVS, DIVSL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'DIVU, DIVUL': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'LINK': {'WORD DISPLACEMENT': (15, 0, 16)},
  'LSL, LSR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MOVE16': {'REGISTER Ay': (14, 12, 3)},
  'MOVEC': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'CONTROL REGISTER': (11, 0, 12)},
  'MOVEP': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'MOVES': {'A/D': (15, 15, 1), 'REGISTER': (14, 12, 3), 'dr': (11, 11, 1)},
  'MULS': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'MULU': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PDBcc': {'MC68851 CONDITION': (5, 0, 6)},
  'PFLUSH': {'MODE': (12, 10, 3), 'MASK': (7, 4, 4), 'FC': (3, 0, 4)},
  'PFLUSH PFLUSHA': {'MODE': (12, 10, 3), 'MASK': (7, 5, 3), 'FC': (3, 0, 4)},
  'PLOAD': {'R/ W': (9, 9, 1), 'FC': (4, 0, 5)},
  'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PScc': {'MC68851 CONDITION': (5, 0, 6)},
  'PTEST': {'LEVEL': (12, 10, 3),
            'R/ W': (9, 9, 1),
            'A': (8, 8, 1),
            'REGISTER': (7, 3, 5),
            'FC': (2, 0, 3)},
  'PTRAPcc': {'MC68851 CONDITION': (5, 0, 6)},
  'ROL, ROR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'ROXL, ROXR': {'dr': (8, 8, 1), 'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'RTD': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'STOP': {'IMMEDIATE DATA': (15, 0, 16)},
  'TRAPcc': {'OPTIONAL WORD': (15, 0, 16)},
  'cpDBcc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpGEN': {'MODE': (15, 3, 13), 'REGISTER': (2, 0, 3)},
  'cpScc': {'COPROCESSOR CONDITION': (5, 0, 6)},
  'cpTRAPcc': {'COPROCESSOR CONDITION': (5, 0, 6)}},
 {'BCHG': {'BIT NUMBER': (7, 0, 8)},
  'BCLR': {'BIT NUMBER': (7, 0, 8)},
  'BSET': {'BIT NUMBER': (8, 0, 9)},
  'BTST': {'BIT NUMBER': (7, 0, 8)},
  'CAS CAS2': {'SIZE': (10, 9, 2)},
  'DIVS, DIVSL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'DIVU, DIVUL': {'REGISTER Dq': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dr': (2, 0, 3)},
  'LINK': {'REGISTER': (2, 0, 3)},
  'MOVE16': {'OPMODE': (4, 3, 2), 'REGISTER Ay': (2, 0, 3)},
  'MULS': {'REGISTER DI': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'MULU': {'REGISTER Dl': (14, 12, 3), 'SIZE': (10, 10, 1), 'REGISTER Dh': (2, 0, 3)},
  'PDBcc': {'16-BIT DISPLACEMENT': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PVALID': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A1': (15, 15, 1), 'Rn1': (14, 12, 3), 'Du1': (8, 6, 3), 'Dc1': (2, 0, 3)},
  'LINK': {'HIGH-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'HIGH-ORDER ADDRESS': (15, 0, 16)},
  'PFLUSH': {'OPMODE': (4, 3, 2), 'REGISTER': (2, 0, 3)},
  'PMOVE': {'R/ W': (9, 9, 1)},
  'PTEST': {'R/ W': (9, 9, 1), 'REGISTER': (7, 4, 4), 'FC': (3, 0, 4)},
  'PVALID': {'REGISTER': (2, 0, 3)}},
 {'CAS CAS2': {'D/A2': (15, 15, 1), 'Rn2': (14, 12, 3), 'Du2': (8, 6, 3), 'Dc2': (2, 0, 3)},
  'LINK': {'LOW-ORDER DISPLACEMENT': (15, 0, 16)},
  'MOVE16': {'LOW-ORDER ADDRESS': (15, 0, 16)},
  'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'FD': (8, 8, 1)},
  'PTEST': {'R/ W': (5, 5, 1), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)},
  'PTEST': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'R/W': (9, 9, 1)},
  'PTEST': {'LEVEL': (12, 10, 3), 'R/ W': (9, 9, 1), 'A-REGISTER': (8, 6, 3), 'FC': (5, 0, 6)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1), 'NUM': (4, 2, 3)}},
 {'PMOVE': {'MODE': (5, 3, 3), 'REGISTER': (2, 0, 3)}},
 {'PMOVE': {'P-REGISTER': (12, 10, 3), 'R/ W': (9, 9, 1)}})
RAW_FIELDS = ({'ABCD': (('REGISTER Rx', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Ry', 2, 0, 3)),
  'ADD': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ADDX': (('REGISTER Rx', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Ry', 2, 0, 3)),
  'AND': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ANDI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ASL, ASR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'BCHG': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFEXTU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFFFO': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFINS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BKPT': (('VECTOR', 2, 0, 3),),
  'BRA': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BSET': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BSR': (('8-BIT DISPLACEMENT', 7, 0, 8),),
  'BTST': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'Bcc': (('CONDITION', 11, 8, 4), ('8-BIT DISPLACEMENT', 7, 0, 8)),
  'CALLM': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CAS CAS2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK': (('REGISTER', 11, 9, 3), ('SIZE', 8, 7, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CHK2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CINV': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'CLR': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMP2': (('SIZE', 10, 9, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CMPM': (('REGISTER Ax', 11, 9, 3), ('SIZE', 7, 6, 2), ('REGISTER Ay', 2, 0, 3)),
  'CPUSH': (('CACHE', 7, 6, 2), ('SCOPE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'DBcc': (('CONDITION', 11, 8, 4), ('REGISTER', 2, 0, 3)),
  'DIVS, DIVSL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EOR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'EXG': (('REGISTER Rx', 11, 9, 3), ('OPMODE', 7, 3, 5), ('REGISTER Ry', 2, 0, 3)),
  'EXT, EXTB': (('OPMODE', 8, 6, 3), ('REGISTER', 2, 0, 3)),
  'FRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'FSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'JMP': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'JSR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LEA': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'LSL, LSR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'MOVE': (('SIZE', 13, 12, 2),
           ('REGISTER', 11, 9, 3),
           ('MODE', 8, 6, 3),
           ('MODE', 5, 3, 3),
           ('REGISTER', 2, 0, 3)),
  'MOVE USP': (('dr', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'MOVE from CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE from SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to CCR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE to SR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ax', 2, 0, 3),),
  'MOVEA': (('SIZE', 13, 12, 2), ('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEC': (('dr', 0, 0, 1),),
  'MOVEM': (('dr', 10, 10, 1), ('SIZE', 6, 6, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVEP': (('DATA REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('ADDRESS REGISTER', 2, 0, 3)),
  'MOVEQ': (('REGISTER', 11, 9, 3), ('DATA', 7, 0, 8)),
  'MOVES': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULS': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('REGISTER', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NBCD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEG': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NEGX': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'NOT': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'OR': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ORI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PACK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'PBcc': (('SIZE', 6, 6, 1), ('MC68851 CONDITION', 5, 0, 6)),
  'PDBcc': (('COUNT REGISTER', 2, 0, 3),),
  'PEA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSH PFLUSHA': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PFLUSHR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PLOAD': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PRESTORE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PSAVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PScc': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTRAPcc': (('OPMODE', 2, 0, 3),),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ROL, ROR': (('REGISTER', 11, 9, 3),
               ('dr', 8, 8, 1),
               ('SIZE', 7, 6, 2),
               ('i/r', 5, 5, 1),
               ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('REGISTER', 11, 9, 3),
                 ('dr', 8, 8, 1),
                 ('SIZE', 7, 6, 2),
                 ('i/r', 5, 5, 1),
                 ('REGISTER', 2, 0, 3)),
  'RTM': (('D/A', 3, 3, 1), ('REGISTER', 2, 0, 3)),
  'SBCD': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'SUB': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBA': (('REGISTER', 11, 9, 3), ('OPMODE', 8, 6, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBI': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBQ': (('DATA', 11, 9, 3), ('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'SUBX': (('REGISTER Dy/Ay', 11, 9, 3),
           ('SIZE', 7, 6, 2),
           ('R/M', 3, 3, 1),
           ('REGISTER Dx/Ax', 2, 0, 3)),
  'SWAP': (('REGISTER', 2, 0, 3),),
  'Scc': (('CONDITION', 11, 8, 4), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TAS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'TRAP': (('VECTOR', 3, 0, 4),),
  'TRAPcc': (('CONDITION', 11, 8, 4), ('OPMODE', 2, 0, 3)),
  'TST': (('SIZE', 7, 6, 2), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'UNLK': (('REGISTER', 2, 0, 3),),
  'UNPK': (('REGISTER Dy/Ay', 11, 9, 3), ('R/M', 3, 3, 1), ('REGISTER Dx/Ax', 2, 0, 3)),
  'cpBcc': (('ID', 15, 0, 16),),
  'cpDBcc': (('ID', 15, 0, 16),),
  'cpGEN': (('ID', 15, 0, 16),),
  'cpRESTORE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpSAVE': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpScc': (('ID', 11, 9, 3), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'cpTRAPcc': (('ID', 15, 0, 16),)},
 {'ASL, ASR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCHG': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BCLR': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BFCHG': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFCLR': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFEXTS': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFEXTU': (('REGISTER', 14, 12, 3),
             ('Do', 11, 11, 1),
             ('OFFSET', 10, 6, 5),
             ('Dw', 5, 5, 1),
             ('WIDTH', 4, 0, 5)),
  'BFFFO': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFINS': (('REGISTER', 14, 12, 3),
            ('Do', 11, 11, 1),
            ('OFFSET', 10, 6, 5),
            ('Dw', 5, 5, 1),
            ('WIDTH', 4, 0, 5)),
  'BFSET': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BFTST': (('Do', 11, 11, 1), ('OFFSET', 10, 6, 5), ('Dw', 5, 5, 1), ('WIDTH', 4, 0, 5)),
  'BSET': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'BTST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'CALLM': (('ARGUMENT COUNT', 7, 0, 8),),
  'CAS CAS2': (('Du', 8, 6, 3), ('Dc', 2, 0, 3)),
  'CHK2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'CMP2': (('D/A', 15, 15, 1), ('REGISTER', 14, 12, 3)),
  'DBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'DIVS, DIVSL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'DIVU, DIVUL': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'LINK': (('WORD DISPLACEMENT', 15, 0, 16),),
  'LSL, LSR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MOVE16': (('REGISTER Ay', 14, 12, 3),),
  'MOVEC': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('CONTROL REGISTER', 11, 0, 12)),
  'MOVEP': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'MOVES': (('A/D', 15, 15, 1), ('REGISTER', 14, 12, 3), ('dr', 11, 11, 1)),
  'MULS': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'MULU': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PDBcc': (('MC68851 CONDITION', 5, 0, 6),),
  'PFLUSH': (('MODE', 12, 10, 3), ('MASK', 7, 4, 4), ('FC', 3, 0, 4)),
  'PFLUSH PFLUSHA': (('MODE', 12, 10, 3), ('MASK', 7, 5, 3), ('FC', 3, 0, 4)),
  'PLOAD': (('R/ W', 9, 9, 1), ('FC', 4, 0, 5)),
  'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PScc': (('MC68851 CONDITION', 5, 0, 6),),
  'PTEST': (('LEVEL', 12, 10, 3),
            ('R/ W', 9, 9, 1),
            ('A', 8, 8, 1),
            ('REGISTER', 7, 3, 5),
            ('FC', 2, 0, 3)),
  'PTRAPcc': (('MC68851 CONDITION', 5, 0, 6),),
  'ROL, ROR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'ROXL, ROXR': (('dr', 8, 8, 1), ('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'RTD': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'STOP': (('IMMEDIATE DATA', 15, 0, 16),),
  'TRAPcc': (('OPTIONAL WORD', 15, 0, 16),),
  'cpDBcc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpGEN': (('MODE', 15, 3, 13), ('REGISTER', 2, 0, 3)),
  'cpScc': (('COPROCESSOR CONDITION', 5, 0, 6),),
  'cpTRAPcc': (('COPROCESSOR CONDITION', 5, 0, 6),)},
 {'BCHG': (('BIT NUMBER', 7, 0, 8),),
  'BCLR': (('BIT NUMBER', 7, 0, 8),),
  'BSET': (('BIT NUMBER', 8, 0, 9),),
  'BTST': (('BIT NUMBER', 7, 0, 8),),
  'CAS CAS2': (('SIZE', 10, 9, 2),),
  'DIVS, DIVSL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'DIVU, DIVUL': (('REGISTER Dq', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dr', 2, 0, 3)),
  'LINK': (('REGISTER', 2, 0, 3),),
  'MOVE16': (('OPMODE', 4, 3, 2), ('REGISTER Ay', 2, 0, 3)),
  'MULS': (('REGISTER DI', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'MULU': (('REGISTER Dl', 14, 12, 3), ('SIZE', 10, 10, 1), ('REGISTER Dh', 2, 0, 3)),
  'PDBcc': (('16-BIT DISPLACEMENT', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PVALID': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'CAS CAS2': (('D/A1', 15, 15, 1), ('Rn1', 14, 12, 3), ('Du1', 8, 6, 3), ('Dc1', 2, 0, 3)),
  'LINK': (('HIGH-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('HIGH-ORDER ADDRESS', 15, 0, 16),),
  'PFLUSH': (('OPMODE', 4, 3, 2), ('REGISTER', 2, 0, 3)),
  'PMOVE': (('R/ W', 9, 9, 1),),
  'PTEST': (('R/ W', 9, 9, 1), ('REGISTER', 7, 4, 4), ('FC', 3, 0, 4)),
  'PVALID': (('REGISTER', 2, 0, 3),)},
 {'CAS CAS2': (('D/A2', 15, 15, 1), ('Rn2', 14, 12, 3), ('Du2', 8, 6, 3), ('Dc2', 2, 0, 3)),
  'LINK': (('LOW-ORDER DISPLACEMENT', 15, 0, 16),),
  'MOVE16': (('LOW-ORDER ADDRESS', 15, 0, 16),),
  'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('FD', 8, 8, 1)),
  'PTEST': (('R/ W', 5, 5, 1), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3)),
  'PTEST': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('R/W', 9, 9, 1),),
  'PTEST': (('LEVEL', 12, 10, 3), ('R/ W', 9, 9, 1), ('A-REGISTER', 8, 6, 3), ('FC', 5, 0, 6))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1), ('NUM', 4, 2, 3))},
 {'PMOVE': (('MODE', 5, 3, 3), ('REGISTER', 2, 0, 3))},
 {'PMOVE': (('P-REGISTER', 12, 10, 3), ('R/ W', 9, 9, 1))})
OPERAND_MODE_TABLES = {'ABCD': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'ADDX': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'PACK': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'SBCD': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'SUBX': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')}),
 'UNPK': ('R/M', {0: ('dn', 'dn'), 1: ('predec', 'predec')})}
REGISTER_FIELDS = {'ABCD': ((11, 9, 3), (2, 0, 3)),
 'ADD': ((11, 9, 3), (2, 0, 3)),
 'ADDA': ((11, 9, 3), (2, 0, 3)),
 'ADDI': ((2, 0, 3),),
 'ADDQ': ((2, 0, 3),),
 'ADDX': ((11, 9, 3), (2, 0, 3)),
 'AND': ((11, 9, 3), (2, 0, 3)),
 'ANDI': ((2, 0, 3),),
 'ASL, ASR': ((11, 9, 3), (2, 0, 3)),
 'BCHG': ((11, 9, 3), (2, 0, 3)),
 'BCLR': ((11, 9, 3), (2, 0, 3)),
 'BFCHG': ((2, 0, 3),),
 'BFCLR': ((2, 0, 3),),
 'BFEXTS': ((2, 0, 3),),
 'BFEXTU': ((2, 0, 3),),
 'BFFFO': ((2, 0, 3),),
 'BFINS': ((2, 0, 3),),
 'BFSET': ((2, 0, 3),),
 'BFTST': ((2, 0, 3),),
 'BSET': ((11, 9, 3), (2, 0, 3)),
 'BTST': ((11, 9, 3), (2, 0, 3)),
 'CALLM': ((2, 0, 3),),
 'CAS CAS2': ((2, 0, 3),),
 'CHK': ((11, 9, 3), (2, 0, 3)),
 'CHK2': ((2, 0, 3),),
 'CINV': ((2, 0, 3),),
 'CLR': ((2, 0, 3),),
 'CMP': ((11, 9, 3), (2, 0, 3)),
 'CMP2': ((2, 0, 3),),
 'CMPA': ((11, 9, 3), (2, 0, 3)),
 'CMPI': ((2, 0, 3),),
 'CMPM': ((11, 9, 3), (2, 0, 3)),
 'CPUSH': ((2, 0, 3),),
 'DBcc': ((2, 0, 3),),
 'DIVS, DIVSL': ((11, 9, 3), (2, 0, 3)),
 'DIVU, DIVUL': ((11, 9, 3), (2, 0, 3)),
 'EOR': ((11, 9, 3), (2, 0, 3)),
 'EORI': ((2, 0, 3),),
 'EXG': ((11, 9, 3), (2, 0, 3)),
 'EXT, EXTB': ((2, 0, 3),),
 'FRESTORE': ((2, 0, 3),),
 'FSAVE': ((2, 0, 3),),
 'JMP': ((2, 0, 3),),
 'JSR': ((2, 0, 3),),
 'LEA': ((11, 9, 3), (2, 0, 3)),
 'LINK': ((2, 0, 3),),
 'LSL, LSR': ((11, 9, 3), (2, 0, 3)),
 'MOVE': ((11, 9, 3), (2, 0, 3)),
 'MOVE USP': ((2, 0, 3),),
 'MOVE from CCR': ((2, 0, 3),),
 'MOVE from SR': ((2, 0, 3),),
 'MOVE to CCR': ((2, 0, 3),),
 'MOVE to SR': ((2, 0, 3),),
 'MOVE16': ((2, 0, 3),),
 'MOVEA': ((11, 9, 3), (2, 0, 3)),
 'MOVEM': ((2, 0, 3),),
 'MOVEQ': ((11, 9, 3),),
 'MOVES': ((2, 0, 3),),
 'MULS': ((11, 9, 3), (2, 0, 3)),
 'MULU': ((11, 9, 3), (2, 0, 3)),
 'NBCD': ((2, 0, 3),),
 'NEG': ((2, 0, 3),),
 'NEGX': ((2, 0, 3),),
 'NOT': ((2, 0, 3),),
 'OR': ((11, 9, 3), (2, 0, 3)),
 'ORI': ((2, 0, 3),),
 'PACK': ((11, 9, 3), (2, 0, 3)),
 'PEA': ((2, 0, 3),),
 'PFLUSH': ((2, 0, 3),),
 'PFLUSH PFLUSHA': ((2, 0, 3),),
 'PFLUSHR': ((2, 0, 3),),
 'PLOAD': ((2, 0, 3),),
 'PMOVE': ((2, 0, 3),),
 'PRESTORE': ((2, 0, 3),),
 'PSAVE': ((2, 0, 3),),
 'PScc': ((2, 0, 3),),
 'PTEST': ((2, 0, 3),),
 'PVALID': ((2, 0, 3),),
 'ROL, ROR': ((11, 9, 3), (2, 0, 3)),
 'ROXL, ROXR': ((11, 9, 3), (2, 0, 3)),
 'RTM': ((2, 0, 3),),
 'SBCD': ((11, 9, 3), (2, 0, 3)),
 'SUB': ((11, 9, 3), (2, 0, 3)),
 'SUBA': ((11, 9, 3), (2, 0, 3)),
 'SUBI': ((2, 0, 3),),
 'SUBQ': ((2, 0, 3),),
 'SUBX': ((11, 9, 3), (2, 0, 3)),
 'SWAP': ((2, 0, 3),),
 'Scc': ((2, 0, 3),),
 'TAS': ((2, 0, 3),),
 'TST': ((2, 0, 3),),
 'UNLK': ((2, 0, 3),),
 'UNPK': ((11, 9, 3), (2, 0, 3)),
 'cpRESTORE': ((2, 0, 3),),
 'cpSAVE': ((2, 0, 3),),
 'cpScc': ((2, 0, 3),)}
RM_FIELD = {'ABCD': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'ADDX': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'PACK': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'SBCD': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'SUBX': (3, {0: 'dn,dn', 1: 'predec,predec'}),
 'UNPK': (3, {0: 'dn,dn', 1: 'predec,predec'})}
IMPLICIT_OPERANDS = {'CLR': 0, 'NBCD': 0, 'NEG': 0, 'NEGX': 0}
OPMODE_TABLES_BY_VALUE = {'ADD': {0: ('b', '< ea > + Dn → Dn', True, None, None, None, None),
         1: ('w', '< ea > + Dn → Dn', True, None, None, None, None),
         2: ('l', '< ea > + Dn → Dn', True, None, None, None, None),
         4: ('b', 'Dn + < ea > → < ea >', False, None, None, None, None),
         5: ('w', 'Dn + < ea > → < ea >', False, None, None, None, None),
         6: ('l', 'Dn + < ea > → < ea >', False, None, None, None, None)},
 'ADDA': {3: ('w',
              'Word operation; the source operand is sign-extended to a long operand and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'AND': {0: ('b', '< ea > Dn → Dn', True, None, None, None, None),
         1: ('w', '< ea > Dn → Dn', True, None, None, None, None),
         2: ('l', '< ea > Dn → Dn', True, None, None, None, None),
         4: ('b', 'Dn Λ < ea > → < ea >', False, None, None, None, None),
         5: ('w', 'Dn Λ < ea > → < ea >', False, None, None, None, None),
         6: ('l', 'Dn Λ < ea > → < ea >', False, None, None, None, None)},
 'CMP': {0: ('b', 'Dn – < ea >', True, None, None, None, None),
         1: ('w', 'Dn – < ea >', True, None, None, None, None),
         2: ('l', 'Dn – < ea >', True, None, None, None, None)},
 'CMPA': {3: ('w',
              'Word operation; the source operand is sign-extended to a long operand, and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'EOR': {4: ('b', '< ea > ⊕ Dn → < ea >', False, None, None, None, None),
         5: ('w', '< ea > ⊕ Dn → < ea >', False, None, None, None, None),
         6: ('l', '< ea > ⊕ Dn → < ea >', False, None, None, None, None)},
 'EXG': {8: (None, 'Data registers', None, None, None, 'dn', 'dn'),
         9: (None, 'Address registers', None, None, None, 'an', 'an'),
         17: (None, 'Data register and address register', None, None, None, 'dn', 'an')},
 'EXT, EXTB': {2: ('b',
                   'Sign-extend low-order byte of data register to word',
                   None,
                   None,
                   None,
                   None,
                   None),
               3: ('w',
                   'Sign-extend low-order word of data register to long',
                   None,
                   None,
                   None,
                   None,
                   None),
               7: ('b',
                   'Sign-extend low-order byte of data register to long',
                   None,
                   None,
                   None,
                   None,
                   None)},
 'MOVE16': {0: (None, None, None, '(Ay) +', '(xxx).L', None, None),
            1: (None, None, None, '(xxx).L', '(Ay) +', None, None),
            2: (None, None, None, '(Ay)', '(xxx).L', None, None),
            3: (None, None, None, '(xxx).L', '(Ay)', None, None)},
 'MOVEP': {4: ('w', 'Transfer word from memory to register', None, None, None, None, None),
           5: ('l', 'Transfer long from memory to register', None, None, None, None, None),
           6: ('w', 'Transfer word from register to memory', None, None, None, None, None),
           7: ('l', 'Transfer long from register to memory', None, None, None, None, None)},
 'OR': {0: ('b', '< ea > V Dn → Dn', True, None, None, None, None),
        1: ('w', '< ea > V Dn → Dn', True, None, None, None, None),
        2: ('l', '< ea > V Dn → Dn', True, None, None, None, None),
        4: ('b', 'Dn V < ea > → < ea >', False, None, None, None, None),
        5: ('w', 'Dn V < ea > → < ea >', False, None, None, None, None),
        6: ('l', 'Dn V < ea > → < ea >', False, None, None, None, None)},
 'PTRAPcc': {2: ('w', 'Instruction is followed by one operand word', None, None, None, None, None),
             3: ('l', 'Instruction is followed by two operand words', None, None, None, None, None),
             4: (None, 'Instruction has no following operand words', None, None, None, None, None)},
 'SUB': {0: ('b', 'Dn – < ea > → Dn', True, None, None, None, None),
         1: ('w', 'Dn – < ea > → Dn', True, None, None, None, None),
         2: ('l', 'Dn – < ea > → Dn', True, None, None, None, None),
         4: ('b', '< ea > – Dn → < ea >', False, None, None, None, None),
         5: ('w', '< ea > – Dn → < ea >', False, None, None, None, None),
         6: ('l', '< ea > – Dn → < ea >', False, None, None, None, None)},
 'SUBA': {3: ('w',
              'Word operation. The source operand is sign-extended to a long operand and',
              True,
              None,
              None,
              None,
              None),
          7: ('l', 'Long operation', True, None, None, None, None)},
 'TRAPcc': {2: ('w', 'Instruction is followed by word-sized operand', None, None, None, None, None),
            3: ('l',
                'Instruction is followed by long-word-sized operand',
                None,
                None,
                None,
                None,
                None),
            4: (None, 'Instruction has no operand', None, None, None, None, None)}}
MOVEM_FIELDS = {'dr': (10, 10, 1), 'size': (6, 6, 1), 'mode': (5, 3, 3), 'register': (2, 0, 3)}
IMMEDIATE_RANGES = {'ADDQ': ('DATA', 3, False, 1, 8, 8),
 'ASL, ASR': ('Count/Register', 3, False, 1, 8, 8),
 'BCHG': ('BIT NUMBER', 8, False, 0, 255, None),
 'BCLR': ('BIT NUMBER', 8, False, 0, 255, None),
 'BKPT': ('VECTOR', 3, False, 0, 7, None),
 'BRA': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'BSET': ('BIT NUMBER', 9, False, 0, 511, None),
 'BSR': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'BTST': ('BIT NUMBER', 8, False, 0, 255, None),
 'Bcc': ('8-BIT DISPLACEMENT', 8, True, -128, 127, None),
 'CALLM': ('ARGUMENT COUNT', 8, False, 0, 255, None),
 'DBcc': ('16-BIT DISPLACEMENT', 16, False, 0, 65535, None),
 'LINK': ('WORD DISPLACEMENT', 16, True, -32768, 32767, None),
 'LSL, LSR': ('Count/Register', 3, False, 1, 8, 8),
 'MOVE16': ('HIGH-ORDER ADDRESS', 16, False, 0, 65535, None),
 'MOVEQ': ('DATA', 8, True, -128, 127, None),
 'ROL, ROR': ('Count/Register', 3, False, 1, 8, 8),
 'ROXL, ROXR': ('Count/Register', 3, False, 1, 8, 8),
 'RTD': ('16-BIT DISPLACEMENT', 16, False, 0, 65535, None),
 'STOP': ('IMMEDIATE DATA', 16, False, 0, 65535, None),
 'SUBQ': ('DATA', 3, False, 1, 8, 8),
 'TRAP': ('VECTOR', 4, False, 0, 15, None),
 'TRAPcc': ('OPTIONAL WORD', 16, False, 0, 65535, None)}
DEST_REG_FIELD = {'ABCD': (11, 9, 3),
 'ADD': (11, 9, 3),
 'ADDA': (11, 9, 3),
 'ADDX': (11, 9, 3),
 'AND': (11, 9, 3),
 'ASL, ASR': (11, 9, 3),
 'BCHG': (11, 9, 3),
 'BCLR': (11, 9, 3),
 'BSET': (11, 9, 3),
 'BTST': (11, 9, 3),
 'CHK': (11, 9, 3),
 'CMP': (11, 9, 3),
 'CMPA': (11, 9, 3),
 'CMPM': (11, 9, 3),
 'DIVS, DIVSL': (11, 9, 3),
 'DIVU, DIVUL': (11, 9, 3),
 'EOR': (11, 9, 3),
 'EXG': (11, 9, 3),
 'LEA': (11, 9, 3),
 'LSL, LSR': (11, 9, 3),
 'MOVE': (11, 9, 3),
 'MOVEA': (11, 9, 3),
 'MOVEQ': (11, 9, 3),
 'MULS': (11, 9, 3),
 'MULU': (11, 9, 3),
 'OR': (11, 9, 3),
 'PACK': (11, 9, 3),
 'ROL, ROR': (11, 9, 3),
 'ROXL, ROXR': (11, 9, 3),
 'SBCD': (11, 9, 3),
 'SUB': (11, 9, 3),
 'SUBA': (11, 9, 3),
 'SUBX': (11, 9, 3),
 'UNPK': (11, 9, 3)}
OPERATION_TYPES = {'ABCD': OperationType.ADD_DECIMAL,
 'ADD': OperationType.ADD,
 'ADDA': OperationType.ADD,
 'ADDI': OperationType.ADD,
 'ADDQ': OperationType.ADD,
 'ADDX': OperationType.ADDX,
 'AND': OperationType.AND,
 'ANDI': OperationType.AND,
 'ANDI to CCR': OperationType.CCR_OP,
 'ANDI to SR': OperationType.SR_OP,
 'ASL, ASR': OperationType.SHIFT,
 'BCHG': OperationType.BIT_TEST,
 'BCLR': OperationType.BIT_TEST,
 'BFCHG': OperationType.BITFIELD,
 'BFCLR': OperationType.BITFIELD,
 'BFEXTS': OperationType.BITFIELD,
 'BFEXTU': OperationType.BITFIELD,
 'BFFFO': OperationType.BITFIELD,
 'BFINS': OperationType.BITFIELD,
 'BFSET': OperationType.BITFIELD,
 'BFTST': OperationType.BITFIELD,
 'BRA': OperationType.ADD,
 'BSET': OperationType.BIT_TEST,
 'BSR': OperationType.SUB,
 'BTST': OperationType.BIT_TEST,
 'CAS CAS2': OperationType.COMPARE_SWAP,
 'CHK': OperationType.BOUNDS_CHECK,
 'CHK2': OperationType.BOUNDS_CHECK,
 'CINV': OperationType.SR_OP,
 'CLR': OperationType.CLEAR,
 'CMP': OperationType.COMPARE,
 'CMP2': OperationType.BOUNDS_CHECK,
 'CMPA': OperationType.COMPARE,
 'CMPI': OperationType.COMPARE,
 'CMPM': OperationType.COMPARE,
 'CPUSH': OperationType.SR_OP,
 'DIVS, DIVSL': OperationType.DIVIDE,
 'DIVU, DIVUL': OperationType.DIVIDE,
 'EOR': OperationType.XOR,
 'EORI': OperationType.XOR,
 'EORI to CCR': OperationType.CCR_OP,
 'EORI to SR': OperationType.SR_OP,
 'EXG': OperationType.SWAP,
 'EXT, EXTB': OperationType.SIGN_EXTEND,
 'FRESTORE': OperationType.SR_OP,
 'FSAVE': OperationType.SR_OP,
 'ILLEGAL': OperationType.SUB,
 'JMP': OperationType.MOVE,
 'JSR': OperationType.SUB,
 'LEA': OperationType.MOVE,
 'LINK': OperationType.SUB,
 'LSL, LSR': OperationType.SHIFT,
 'MOVE': OperationType.MOVE,
 'MOVE USP': OperationType.SR_OP,
 'MOVE from CCR': OperationType.CCR_OP,
 'MOVE from SR': OperationType.MOVE,
 'MOVE to CCR': OperationType.CCR_OP,
 'MOVE to SR': OperationType.SR_OP,
 'MOVE16': OperationType.MOVE,
 'MOVEA': OperationType.MOVE,
 'MOVEC': OperationType.SR_OP,
 'MOVEM': OperationType.MOVE,
 'MOVEP': OperationType.MOVE,
 'MOVEQ': OperationType.MOVE,
 'MOVES': OperationType.SR_OP,
 'MULS': OperationType.MULTIPLY,
 'MULU': OperationType.MULTIPLY,
 'NBCD': OperationType.NEGX,
 'NEG': OperationType.NEG,
 'NEGX': OperationType.NEGX,
 'NOT': OperationType.NOT,
 'OR': OperationType.OR,
 'ORI': OperationType.OR,
 'ORI to CCR': OperationType.CCR_OP,
 'ORI to SR': OperationType.SR_OP,
 'PACK': OperationType.ADD,
 'PBcc': OperationType.SR_OP,
 'PDBcc': OperationType.SR_OP,
 'PEA': OperationType.SUB,
 'PFLUSH': OperationType.SR_OP,
 'PFLUSH PFLUSHA': OperationType.SR_OP,
 'PFLUSHR': OperationType.SR_OP,
 'PLOAD': OperationType.SR_OP,
 'PMOVE': OperationType.SR_OP,
 'PRESTORE': OperationType.SR_OP,
 'PSAVE': OperationType.SR_OP,
 'PScc': OperationType.SR_OP,
 'PTEST': OperationType.SR_OP,
 'PTRAPcc': OperationType.SR_OP,
 'PVALID': OperationType.MOVE,
 'RESET': OperationType.SR_OP,
 'ROL, ROR': OperationType.ROTATE,
 'ROXL, ROXR': OperationType.ROTATE_EXTEND,
 'RTD': OperationType.ADD,
 'RTE': OperationType.SR_OP,
 'RTR': OperationType.CCR_OP,
 'RTS': OperationType.ADD,
 'SBCD': OperationType.SUB_DECIMAL,
 'STOP': OperationType.SR_OP,
 'SUB': OperationType.SUB,
 'SUBA': OperationType.SUB,
 'SUBI': OperationType.SUB,
 'SUBQ': OperationType.SUB,
 'SUBX': OperationType.SUBX,
 'SWAP': OperationType.SWAP,
 'TAS': OperationType.TEST,
 'TRAP': OperationType.MOVE,
 'TST': OperationType.TEST,
 'UNLK': OperationType.ADD,
 'UNPK': OperationType.ADD,
 'cpRESTORE': OperationType.SR_OP,
 'cpSAVE': OperationType.SR_OP}
OPERATION_CLASSES = {'LEA': OperationClass.LOAD_EFFECTIVE_ADDRESS,
 'MOVEM': OperationClass.MULTI_REGISTER_TRANSFER}
SOURCE_SIGN_EXTEND = ('ADDA', 'CMPA', 'MOVEA', 'SUBA')
BIT_MODULI = {'BCHG': (32, 8), 'BCLR': (32, 8), 'BSET': (32, 8), 'BTST': (32, 8)}
SHIFT_COUNT_MODULI = {'ASL, ASR': 64, 'LSL, LSR': 64, 'ROL, ROR': 64, 'ROXL, ROXR': 64}
ROTATE_EXTRA_BITS = {'ROXL, ROXR': 1}
DIRECTION_VARIANTS = {'ASL, ASR': ((8, 8, 1), 'as', ('asl', 'asr'), {0: 'r', 1: 'l'}),
 'LSL, LSR': ((8, 8, 1), 'ls', ('lsl', 'lsr'), {0: 'r', 1: 'l'}),
 'ROL, ROR': ((8, 8, 1), 'ro', ('rol', 'ror'), {0: 'r', 1: 'l'}),
 'ROXL, ROXR': ((8, 8, 1), 'rox', ('roxl', 'roxr'), {0: 'r', 1: 'l'})}
SHIFT_FIELDS = ((8, 8, 1), ('r', 'l'), 8)
SHIFT_VARIANT_BEHAVIORS = {'ASL, ASR': (('ASL', ShiftDirection.LEFT, ShiftFill.ZERO, True), ('ASR', ShiftDirection.RIGHT, ShiftFill.SIGN, True),),
 'LSL, LSR': (('LSL', ShiftDirection.LEFT, ShiftFill.ZERO, False), ('LSR', ShiftDirection.RIGHT, ShiftFill.ZERO, False),),
 'ROL, ROR': (('ROL', ShiftDirection.LEFT, ShiftFill.ROTATE, False), ('ROR', ShiftDirection.RIGHT, ShiftFill.ROTATE, False),),
 'ROXL, ROXR': (('ROXL', ShiftDirection.LEFT, ShiftFill.ROTATE, False), ('ROXR', ShiftDirection.RIGHT, ShiftFill.ROTATE, False),)}
PRIMARY_DATA_SIZES = {'DIVS, DIVSL': (PrimaryDataSizeKind.DIVIDE, 16, 32, 16),
 'DIVU, DIVUL': (PrimaryDataSizeKind.DIVIDE, 16, 32, 16),
 'MULS': (PrimaryDataSizeKind.MULTIPLY, 16, 16, 32),
 'MULU': (PrimaryDataSizeKind.MULTIPLY, 16, 16, 32)}
SIGNED_RESULTS = {'DIVS, DIVSL': True, 'DIVU, DIVUL': False, 'MULS': True, 'MULU': False}
BRANCH_INLINE_DISPLACEMENTS = {'BRA': ('8-BIT DISPLACEMENT', (7, 0, 8), 0, 255, 2, 4),
 'BSR': ('8-BIT DISPLACEMENT', (7, 0, 8), 0, 255, 2, 4),
 'Bcc': ('8-BIT DISPLACEMENT', (7, 0, 8), 0, 255, 2, 4)}
BRANCH_EXTENSION_DISPLACEMENTS = {'DBcc': (2, 2), 'PDBcc': (4, 2), 'cpDBcc': (2, 2)}
